### ISSUE TITLE
Feature request: Support #use toplevel directives in .ml files

### ISSUE THREAD

**Issue by Wilfred** [ocaml-ppx/ocamlformat#1011]
**Is your feature request related to a problem? Please describe.**
It would be really useful if `ocamlformat` could handle files with `#use "foo.ml"` in them.

#523 mentions that shebangs `#!/usr/bin/env ocaml` and `#require "Foo"` are supported, and #731 mentions some others, but `#use` currently isn't supported.

```ocaml
#use "bar.ml"
```

```
$ ocamlformat --enable-outside-detected-project ~/tmp/foo.ml
ocamlformat: ignoring "/Users/wilfred/tmp/foo.ml" (syntax error)
File "/Users/wilfred/tmp/foo.ml", line 1, characters 0-1:
Error: Syntax error
```

**Describe the solution you'd like**
Format files with `#use "foo.ml" in them. I don't think ocamlformat needs to anything with the directive, but it would be nice if it processed the rest of the file.

**Comment by Julow** [comment]
OCamlformat parses directives only in `use-file` mode. You can either rename your file to `foo.mlt`, use `--use-file` or `--name foo.mlt` to tell OCamlformat how to parse this file.

**Comment by Wilfred** [comment]
Is this a common convention for putting `#use` in `.mlt` files? I couldn't find anything when searching for "ocaml mlt" except https://github.com/janestreet/mlt_parser, which doesn't seem to be the same syntax.
