### ISSUE TITLE
Feature request: make --enable-outside-detected-project implicit when inputting via std.in

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1015]
**Is your feature request related to a problem? Please describe.**
When running OCamlformat with standard input, it is required to pass `--enable-outside-detected-project`.

```sh
ᐅ echo "let x = ()" | ocamlformat --profile=conventional --name foo.ml -
File "foo.ml":
Warning: Ocamlformat disabled because [--enable-outside-detected-project] is not set and no project root was found
let x = ()
```

**Describe the solution you'd like**
Perhaps `--enable-outside-detected-project` should be implicit when running OCamlformat this way? I think if the user is providing input from `std.in`, it's likely they're not getting this code from an enclosing OCamlformatted project.

CC. @Julow

**Comment by hartmut27** [comment]
even this is a closed issue, for reference reasons:

`If no config file is found, formatting is disabled` 

but **yet creating an empty ".ocamlformat" file** (0 bytes) the folder where where your source code resides or in the project root folder  **enables formatting**.
