### ISSUE TITLE
Exception "Internal Error: formatting changed ast".

### ISSUE THREAD

**Issue by fpottier** [ocaml-ppx/ocamlformat#105]
Hello,

The following code causes ocamlformat 0.3 to raise an exception with the error message "Internal Error: formatting changed ast". This code is extracted from Coq.

I don't particularly care about this code, but I thought the problem might be worth investigating and fixing.

Thanks!

```
(** val add : int -> int -> int **)

let rec add = (+)

(** val add_carry : int -> int -> int **)

and add_carry x y =
  (fun f2p1 f2p f1 p ->
if p<=1 then f1 () else if p mod 2 = 0 then f2p (p/2) else f2p1 (p/2))
    (fun p ->
    (fun f2p1 f2p f1 p ->
if p<=1 then f1 () else if p mod 2 = 0 then f2p (p/2) else f2p1 (p/2))
      (fun q -> (fun p->1+2*p)
      (add_carry p q))
      (fun q -> (fun p->2*p)
      (add_carry p q))
      (fun _ -> (fun p->1+2*p)
      (succ p))
      y)
    (fun p ->
    (fun f2p1 f2p f1 p ->
if p<=1 then f1 () else if p mod 2 = 0 then f2p (p/2) else f2p1 (p/2))
      (fun q -> (fun p->2*p)
      (add_carry p q))
      (fun q -> (fun p->1+2*p)
      (add p q))
      (fun _ -> (fun p->2*p)
      (succ p))
      y)
    (fun _ ->
    (fun f2p1 f2p f1 p ->
if p<=1 then f1 () else if p mod 2 = 0 then f2p (p/2) else f2p1 (p/2))
      (fun q -> (fun p->1+2*p)
      (succ q))
      (fun q -> (fun p->2*p)
      (succ q))
      (fun _ -> (fun p->1+2*p)
      1)
      y)
    x
```

**Comment by jvillard** [comment]
The cause seems to be the `let ... (** doc comment *) and ...` combination. Minimal example:

```OCaml
let f = ()

(** pesky doc comment *)

and g = ()
```

After `ocamlformat`, the floating doc comment gets attached to `g`:

```OCaml
let f = ()

(** pesky doc comment *)
and g = ()
```

**Comment by jberdine** [comment]
Thanks! @jul was right, floating docstrings in the middle of a group of value bindings were being formatted without a trailing open line, causing the docstring attachment the next time around to conclude that it was not floating, but attached to the succeeding binding, and blowing up over the changed parsetree.

Never mind that the content of the docstrings seems to indicate that they shouldn't be floating in the first place...
