### ISSUE TITLE
Feature request: Allow controlling the indent on documentation comments

### ISSUE THREAD

**Issue by Wilfred** [ocaml-ppx/ocamlformat#1055]
**Is your feature request related to a problem? Please describe.**
ocamlformat indents documentation comments like this:

```
type fun_tparams_kind =
  | FTKtparams
      (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
          baz foo bar baz foo bar baz. *)
  | FTKinstantiated_targs
      (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
          baz foo bar baz foo bar baz. *)
```

It would be nice to be able to configure the level of indentation of these comments.

This style of documentation comments seems to be rare: I struggled to find many examples of individual variants in either Core or Merlin.

**Describe the solution you'd like**
I'd prefer a setting like `--variant-doc-comment-indent`. This would allow formatting like this:

```
type fun_tparams_kind =
  | FTKtparams
    (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
        baz foo bar baz foo bar baz. *)
  | FTKinstantiated_targs
    (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
        baz foo bar baz foo bar baz. *)
```

or like this:

```
type fun_tparams_kind =
  | FTKtparams
  (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
      baz foo bar baz foo bar baz. *)
  | FTKinstantiated_targs
  (** If ft_tparams is empty. Hello world foo bar baz foo bar baz foo bar
      baz foo bar baz foo bar baz. *)
```

**Comment by gpetiot** [comment]
Sorry for the late answer, our current strategy is to avoid adding new options, and so far most people seem happy with the current indentation of doc-comments. So we're unlikely to change it for now but we might reconsider if there is a stronger push from the community. I'm thus closing this issue :)
