### ISSUE TITLE
Feature request: Don't wrap pipelines

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#1080]
The option `break-infix=fit-or-vertical` allows to break before every infix operators if the whole expression does not fit on a single line:

```diff
-           get_succs parent |> Sequence.of_list
+           get_succs parent
+           |> Sequence.of_list
            |> Sequence.filter ~f:(fun n -> not (equal node n))
            |> Sequence.Generator.of_sequence)
```

This works well for pipelines, boolean operators and sometimes list cons/concat but not with most other expressions:

```diff
 let git_clone ~branch ~remote ~output_dir =
   run_and_log
     Cmd.(
-      v "git" % "clone" % "--depth" % "1" % "--branch" % branch % remote
+      v "git"
+      % "clone"
+      % "--depth"
+      % "1"
+      % "--branch"
+      % branch
+      % remote
       % p output_dir)
```

This is clearly not what we want when the operands are short or when the expression is dense (eg. arithmetic, cmdliner's `&` and `$`).

I'd like `fit-or-vertical` in the `default` profile but only for pipelines.
Should we implement that ? How to decide what is a pipeline and what is not ?

There have been discussions before, in https://github.com/ocaml-ppx/ocamlformat/issues/69 then `break-infix` has been added in https://github.com/ocaml-ppx/ocamlformat/pull/150.

**Comment by gpetiot** [comment]
I agree, if we find a good heuristics we could also removes this option in favor of an auto mode (pipes -> fit or vertical, otherwise -> wrap)

**Comment by jberdine** [comment]
I wonder if using the precedence of the operator would be a reasonable criterion. For example, perhaps everything at the [precedence](https://caml.inria.fr/pub/docs/manual-ocaml/expr.html#ss:precedence-and-associativity) of `::` and lower could be treated as fit-or-vertical, and everything of higher precedence could be treated as wrap.

**Comment by jberdine** [comment]
For maximal headaches, the threshold precedence level could be an int configure option. :-P
