### ISSUE TITLE
Bug: bracket of type on newline

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#1086]
On the last commit `647a2159dbde453d96c9e73b3110e89681ca469c`: instead of
```ocaml
type t =
  { a: int
  ; b: int }
```
becomes
```ocaml
type t =
  { a: int
  ; b: int
  }
```
which is unexpected.

Config:
```
if-then-else=fit-or-vertical
break-fun-decl=smart
break-fun-sig=smart
extension-sugar=always
single-case=compact
break-separators=before
break-sequences=true
break-struct=force
break-cases=fit-or-vertical
break-collection-expressions=fit-or-vertical
break-infix=fit-or-vertical
module-item-spacing=compact
doc-comments=before
ocp-indent-compat=true
type-decl=sparse
let-and=sparse
let-open=auto
field-space=loose
extension-sugar=always
max-iters=3
quiet=true
cases-exp-indent=4
break-infix-before-func=false
leading-nested-match-parens=true
# indicate-multiline-delimiters=closing-on-separate-line
indicate-multiline-delimiters=space
indicate-nested-or-patterns=space
sequence-style=before
dock-collection-brackets=false
space-around-variants=true
space-around-records=true
space-around-lists=true
space-around-arrays=true
```

**Comment by Pitometsu** [comment]
I gues the `space-around-records` and `space-around-lists` the reasons of such improper parentheses placement.

**Comment by Pitometsu** [comment]
Maybe it should split to `break-separators=before` and `break-separators=before-and-docked` if you would prefer keep current invariant.

**Comment by Julow** [comment]
I cannot reproduce your first example with that config, what version of `ocamlformat` you were using ?

**Comment by Pitometsu** [comment]
from commit `647a2159dbde453d96c9e73b3110e89681ca469c`

**Comment by Julow** [comment]
I meant what version of ocamlformat you used to get
```ocaml
type t =
  { a: int
  ; b: int }
```
?

**Comment by Pitometsu** [comment]
Oh, the older one, `0.11.0`.

**Comment by Pitometsu** [comment]
Or you can just turn space-around-* off.

**Comment by Julow** [comment]
This is not a regression then, this change is because of the `space-around-*` options you added to your config.
Did you mean to submit a feature request ?

**Comment by Pitometsu** [comment]
It looks inconsistent yet (space around add break-line). Feature request for more intuitive configuration, I guess.
