### ISSUE TITLE
Feature request: include functor without align

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#1087]
By default alignment used almost nowhere. But including functor looks like:
```ocaml
include MyFunctor
          (Int)
          (struct
            type i
            include Int with type t := i
          end)
```
instead of
```ocaml
include MyFunctor
  (Int)
  (struct
    type i
    include Int with type t := i
  end)
```
or
```ocaml
include
  MyFunctor
    (Int)
    (struct
      type i
      include Int with type t := i
    end)
```

**Comment by Pitometsu** [comment]
Also isn't
```ocaml
  (struct
  end)
```
looks weird?
wouldn't
```ocaml
  (struct
   end)
```
be better? (not sure though)

**Comment by gpetiot** [comment]
It looks likt it's already fixed on the `main` branch where we get something like:
```ocaml
include              
  MyFunctor
    (Int)
    (struct
      type i

      include Int
    end)
```
For the second point, aligning on the same column as the opening parenthesis is the expected behavior (I forgot where is the justification, I will add an entry in the FAQ once I find it).
I'm closing this issue.
