### ISSUE TITLE
Error if .ml file contains only comment

### ISSUE THREAD

**Issue by psteckler** [ocaml-ppx/ocamlformat#109]
If I create an .ml file containing only a comment, and nothing else, like
```
(* this is a comment *)
```
and run `ocamlformat` on that file, I see an error:
```
Fatal error: exception ("Internal Error: formatting changed comments"
  (diff ((First "this is a comment"))))
Raised at file "src/import0.ml" (inlined), line 237, characters 22-32
Called from file "src/exn.ml", line 70, characters 6-15
Called from file "src/ocamlformat.ml", line 56, characters 7-170
```

**Comment by psteckler** [comment]
There is a use-case for a comment-only file, by the way. 

I could have an .mli file which does not expose any code in the corresponding .ml file, which might run top-level startup code that no other module calls. A comment in that file might explain that design decision.

**Comment by hhugo** [comment]
related to https://github.com/ocaml-ppx/ocamlformat/issues/32

**Comment by jberdine** [comment]
@psteckler, this does not repro for me on master, and I think it should have been fixed by https://github.com/ocaml-ppx/ocamlformat/commit/f00efadca380e94f38db320d8ac61d52b0c97815 .  Can I ask you to confirm that you see this with master? (Another release is due.)

**Comment by jberdine** [comment]
Optimistically closing, please reopen if it still repros on master or 0.5.
