### ISSUE TITLE
0.12.0 release plans?

### ISSUE THREAD

**Issue by gabelevi** [ocaml-ppx/ocamlformat#1091]
Hi! My team has been using ocamlformat and loves it, but have been having a bit of trouble with https://github.com/ocaml-ppx/ocamlformat/issues/1001, since IDEs tend to strip out trailing whitespace but ocamlformat 0.11.0 keeps adding it back in.

Since this issue is already fixed, would it be possible to release 0.12.0 in the near future?

Thanks!

**Comment by emillon** [comment]
Hi!

Yes, we plan to release 0.12.0 as soon as the similar major bugs are fixed (we're not adding new features anymore). I'll update the milestone so that we can keep track of the remaining bits.

Thanks!

**Comment by nmote** [comment]
For anyone else interested, here's the [0.12 milestone](https://github.com/ocaml-ppx/ocamlformat/milestone/6).

**Comment by emillon** [comment]
0.12.0 is being released this week :tada:, so we can close this. Thanks!
