### ISSUE TITLE
Standardize exchange of comment attachment between ocamlformat and refmt

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#110]
Comments are (the?) one main point that stands between really slick interop between refmt and ocamlformat that would allow seamless translation between concrete syntaxes. Each tool is best at associating comments with abstract syntax phrases in its own output, but the current interop format (serialized parsetree and comment list) does not communicate the comment attachment decisions between tools. It would be better to have a common exchange format to allow each tool to do its own comment attachment and communicate the result to the other.

If refmt were to report the results of its own heuristics for associating comments to parsetree nodes as attributes in the parse tree, for example, then this annotated parsetree could be given to ocamlformat to produce OCaml concrete syntax. Likewise, with such interop attributes, ocamlformat could report its comment association decisions as attributes and pass the resulting annotated parsetree to refmt to produce Reason concrete syntax.

Doing this would not be much work on the ocamlformat side, but last I checked, refmt used an intermediate structure, not the parsetree, when attaching comments, which would make it more (maybe too much) work. Perhaps there is another alternative.

See background discussion in https://github.com/ocaml-ppx/ocamlformat/issues/82 and https://github.com/facebook/reason/issues/516.

**Comment by trefis** [comment]
AFAIK attributes can’t be attached to every node, while comments can be placed anywhere.
That’s probably the reason ( :) ) why refmt has a dedicated structure.

**Comment by jberdine** [comment]
@trefis, you could be right. But I just did a quick check and there are attributes very close to "everywhere" in the parsetree. That is, considering everywhere there is a `Location.t` value, the only case I found where there were no attributes is `with_constraint`. Did you have any others in mind?

**Comment by gpetiot** [comment]
If this is the only case it shouldn't raise too many issues. It could simplify the code to only have to process attributes instead of attributes and comments.
