### ISSUE TITLE
Style suggestion: match with that is combination of all and nested

### ISSUE THREAD

**Issue by badochov** [ocaml-ppx/ocamlformat#1115]
**What is the reason for this new style?**
Option: break-cases
When is is set to nested it can generate oneliner which is unreadable for me, and when it's set  to all case body is not always in newline which is also hard to read for me.

**Describe the solution you'd like**
Either add it as new option or split this into two options one for break before the body other for breaking match with

**Comment by gpetiot** [comment]
This is planned to break the option `break-cases` into smaller (more atomic) options to let the user have more control over the formatting of cases, the code is not ready yet but we are working on it.

**Comment by gpetiot** [comment]
Sorry for the late reply, ocamlformat's current direction is aiming towards removing this kind of options, or at least not adding new ones. The `break-cases = nested` value lives withing the `ocamlformat` profile, it is not impossible to have the formatting of pattern-matching improved in the future for this profile, but for now the users of this profile seem quite satisfied with the way pattern-matching are rendered.
cc @jberdine in case you would like to see a similar change for this profile.

I am closing this issue, @jberdine feel free to reopen of course.
