### ISSUE TITLE
Let's add dune to the list of projects we're tracking for regressions

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1128]
Hi,

Now [dune](https://github.com/ocaml/dune) is using `ocamlformat`, and it's both an important project and a sizable amount of code (63 kloc), so we should track it in `test-branch`.

Thoughts?

**Comment by gpetiot** [comment]
Is the code really different to the one of `infer`, `ocaml`, `ocamlformat` and `js_of_ocaml`? Having more tests is generally a good thing but it can make the diff more difficult to analyze the more redundancy we have in the tests.

**Comment by emillon** [comment]
I think `dune` is a project to look at when changing existing options for example. But you're right, it's maybe not for `test_branch`.

**Comment by Julow** [comment]
`dune` has a very custom config (https://github.com/ocaml/dune/blob/master/.ocamlformat). I think we should add it to `test_branch` !

**Comment by gpetiot** [comment]
Alright let's add it then :)
