### ISSUE TITLE
Bug: fatal errors are swallowed

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1139]
**Describe the bug**
Since https://github.com/ocaml-ppx/ocamlformat/pull/1127 fatal errors such as `Fatal error: exception ("User Error: malformed .ocamlformat file"` that used to `exit 2` with an uncaught exception now just silently succeed without doing anything.

**Comment by emillon** [comment]
Ah, that's not great. I think we'll need to cut a point release for this. @Julow do you know how to fix this?

**Comment by emillon** [comment]
Ah my bad it's not in the release. All good then. Still needs to be fixed though :)

**Comment by Julow** [comment]
A minor release for that is not needed, #1127 is not released.

The error message changed from

```
Fatal error: exception ("User Error: malformed .ocamlformat file" ...
backtrace
```

to

```
ocamlformat: internal error, uncaught exception:
             ("User Error: malformed .ocamlformat file" ...
             backtrace
```

and the exit status changed from `2` to `1`. That's a regression indeed.

I can't reproduce silently succeed without doing anything. What was the full error message ?

**Comment by jberdine** [comment]
Sorry, the 'silently succeeding' I see is through the emacs integration, but on the command line it does exit with status 1.

I'm not sure what is going on in the emacs integration to do that. Can anyone else repro, or is it just here?

**Comment by jberdine** [comment]
I think the problem is that the error output now is sent to stdout instead of stderr

**Comment by Julow** [comment]
@jberdine https://github.com/ocaml-ppx/ocamlformat/pull/1180 should fix this issue. Is it working for you ?
