### ISSUE TITLE
Oddity: Added open line in comment

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1143]
**Describe the bug**
Since https://github.com/ocaml-ppx/ocamlformat/pull/1122, a comment such as
```
  (* 
    blah blah
  *)
```
(Note: there is a space following the `(*`)
gets formatted to
```
  (*

     blah blah
  *)
```
Since there is trailing whitespace in the original, it is perhaps ok, and can be worked around, but flagging for awareness.

**Comment by Julow** [comment]
Since https://github.com/ocaml-ppx/ocamlformat/pull/1138 this doesn't stabilize. I'm looking into it.
