### ISSUE TITLE
Feature request: interpret normal comments like doc comments (as ocp-indent does)

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1165]
**Is your feature request related to a problem? Please describe.**
There is currently a round-trip problem when running code through ocamlformat and then ocp-indent. Consider code like this:
```
type t =
  { field : ty
  (* Here is some verbatim formatted text:
     {v
       starting at column 7
     v}*)
  }
```
If I run it through ocamlformat as of a906b5d993a6f321045546778ca8dfb4e45dfd90, I get the following:
```
type t =
  { field : ty
        (* Here is some verbatim formatted text:
           {v
             starting at column 7
           v}*)
  }
```
The whole comment has been indented uniformly, as ocamlformat puts comments on fields farther to the right than that.
Now if I run that result through ocp-indent, I get this:
```
type t =
  { field : ty
  (* Here is some verbatim formatted text:
     {v
             starting at column 7
           v}*)
  }
```
Now ocp-indent has moved the comment back to the left. However, because it treates `{v ... v}` as a verbatim block, it left it indented further to the right.
If I then save this code, and run it through ocamlformat and ocp-indent again, that comment will move several spaces further to the right, and on and on. The process does not have a fixed point.

For our current workflow at Jane Street of using ocamlformat with ocp-indent, I think we need one of (a) consistent comment handling between ocp-indent and ocamlformat, (b) ocamlformat not to move any whitespace within comments, or (c) ocamlformat to offer editor integration so we can drop ocp-indent. Pretty clearly (a) is preferable to (b), and I expect (c) is a much bigger lift, but any of the above will alleviate the immediate problem for us.

**Comment by gpetiot** [comment]
I had a look at the `js_source.ml` test file postprocessed by `ocp-indent` and didn't find more cases like this. Did you find more that would require a generic fix from us or a specific one for this case would be enough?

**Comment by ceastlund** [comment]
Well, I'd want this to work for other doc-comment forms like `{[` ... `]}`, if that's what you mean.

**Comment by gpetiot** [comment]
I meant if this issue appeared in other ast nodes than in comments attached after a record field.
But I'm not sure adding a special treatment for this when `ocp-indent-compat` is set is a good solution.
On the other hand, this problem would disappear when ocamlformat is able to reformat invalid files and you don't have to rely on your `ocp-indent` post-process step (if you consider the input and output of ocp-indent in this case, the issue lies what ocp-indent does in my opinion).

**Comment by ELLIOTTCABLE** [comment]
I'm commenting based on the name of the issue, not the specific issue they're seeing in Jane Street —

but at the moment, with ocamlformat v0.13.0, a ton of non-documentation comments in the BuckleScript codebase get mangled like this:

```ocaml
(* https://docs.npmjs.com/files/package.json

   Some rules:

   - The name must be less than or equal to 214 characters. This includes the scope for scoped packages.
   - The name can't start with a dot or an underscore.
   - New packages must not have uppercase letters in the name.
   - The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.

   TODO: handle cases like '@angular/core'. its directory structure is like:

   {[
     @angular
     |-------- core
   ]}
*)
```

-->

```ocaml
(* https://docs.npmjs.com/files/package.json

   Some rules:

   - The name must be less than or equal to 214 characters. This includes the
   scope for scoped packages. - The name can't start with a dot or an
   underscore. - New packages must not have uppercase letters in the name. - The
   name ends up being part of a URL, an argument on the command line, and a
   folder name. Therefore, the name can't contain any non-URL-safe characters.

   TODO: handle cases like '@angular/core'. its directory structure is like:

   {[ @angular |-------- core ]} *)
```

Thus, I, too, would really prefer to see a single, unified "language" parsed in all code-comments.

Hope this is relevant!
