### ISSUE TITLE
Bug: indicate-multiline-delimiters = closing-on-separate-line doesn't affect anonymous functions

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#1174]
**Describe the bug**
When ocamlformat 0.12 from opam and `indicate-multiline-delimiters = closing-on-separate-line` is set I would expect an anonymous function or local module open to have its closing paren on a separate line.  For example:
```ocaml
(* ocamlformat --enable-outside-detected-project test.ml --indicate-multiline-delimiters=closing-on-separate-line -m 20 *)
let _ =
  List.map
    (fun x ->
      some code here) (* <- no newline before the closing delimiter *)
    some_list
```

**How to Reproduce**
Using the `ocamlformat` invocation in the comment above and ocamlformat 0.12.  This was run under `/tmp` with no `.ocamlformat` present and appears consistent with the results in the ocamlformat test suite.

It makes it editing paren-wrapped multi-line expressions more difficult than it should be because the last line needs special treatment.

**Comment by gpetiot** [comment]
I'm requalifying this as a style suggestion.

**Comment by hcarty** [comment]
This is a bit of an ongoing pain point with ocamlformat.  Among other things, it makes it hard to track where expressions begin and end, particularly when nested parentheses are involved.  It also makes it harder to edit code in an anonymous function because the last line in the function is special - it carries the closing delimiter with it.

**Comment by gpetiot** [comment]
Sorry for the delay, I will have a look at that when I get the JaneStreet pain points validated and merged.

**Comment by hcarty** [comment]
Thank you @gpetiot!
