### ISSUE TITLE
Style suggestion: space between single line functions

### ISSUE THREAD

**Issue by jzstark** [ocaml-ppx/ocamlformat#1177]
**What is the reason for this new style?**
Similar to #1176, another style issue we found in developing Owl is that single-line functions are often required, such as in [this example](https://github.com/tachukao/owl/blob/6cd62ddcdab29f5f67da537be2d4e0e4df342bb1/test/unit_ndarray_core_generic.ml#L3161). With the current solution, multiple lines of such functions are squeezed together.

**Describe the solution you'd like**
I'm thinking if there is a solution to make at least a line of space between two functions. 

Any help would be quite appreciated!

**Comment by gpetiot** [comment]
Hi, this can be done with `--module-item-spacing=sparse`.

**Comment by gpetiot** [comment]
Closing this one, feel free to re-open if this didn't answer your question.

**Comment by jzstark** [comment]
Thanks a lot for the help! This is exactly the solution I'm looking for.
