### ISSUE TITLE
Bug: Inline records do no wrap properly

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#1184]
**Describe the bug**
The first field in an inline record does not indent properly using ocamlformat 0.12 and the `.ocamlformat` listed below.

**How to Reproduce**
The following code formats as shown with ocamlformat 0.12 and the configuration listed below.
```ocaml
type t =
  | A of {
    x : int;
      y : float;
    }
```
If it was correctly formatted I would expect the `x : int;` to be indented at the same level as the `y : float;`, like this:
```ocaml
type t =
  | A of {
      x : int;
      y : float;
    }
```

`.ocamlformat`
```
version = 0.12
profile = default
break-cases = all
break-fun-decl = fit-or-vertical
break-infix = fit-or-vertical
cases-exp-indent = 2
doc-comments-padding = 1
if-then-else = k-r
indicate-multiline-delimiters = closing-on-separate-line
leading-nested-match-parens = true
let-and = sparse
let-open = preserve
max-indent = 2
module-item-spacing = preserve
parens-ite = true
parens-tuple-patterns = always
parse-docstrings = true
single-case = sparse
type-decl = sparse
wrap-comments = true
```

**Comment by hcarty** [comment]
This may not be limited to inline records, as something similar happens with function definitions.  Using the same `.ocamlformat` listed above with ocamlformat 0.12 produces this output:
```ocaml
let long_function_definition
  first
    second
    third
    fourth
    fifth
    sixth
    seventh
    eighth
    ninth =
  ()
```

**Comment by gpetiot** [comment]
Hi,

this is already fixed on `master` I think it was due to how `max-indent` was previously implemented, here is the output on master with your configuration:
```
type t =
  | A of {
      x : int;
      y : float;
    }

let long_function_definition
  first
  second
  third
  fourth
  fifth
  sixth
  seventh
  eighth
  ninth =
  ()
```

**Comment by gpetiot** [comment]
I'm closing this issue, feel free to re-open if the issue arises again.

**Comment by hcarty** [comment]
Thanks!
