### ISSUE TITLE
Add option to always break pattern match cases

### ISSUE THREAD

**Issue by edwintorok** [ocaml-ppx/ocamlformat#12]
Currently `ocamlformat` reformats this to a single line:
```ocaml
let f x = function
  | C -> 1
  | D -> 2
```

becomes:

`let f x = function C -> 1 | D -> 2`

This is nice for aesthetic reasons, but if this code is checked into version control then it'll suddenly get all reformatted to multiple lines whenever one of the expressions becomes longer, making diffs harder to check for correctness. The programmer might've foreseen the expression becoming more complicated and separated each case on a line of its own in advance.
OTOH it could be that there are only ever 2 values there (like for `'a result`), in which case using the multiline pattern matching would be wasteful and harder to read.

Would be nice if there was a configuration field to keep the original singleline vs multiline choice, provided that it can still meet the column width limit.

**Comment by jberdine** [comment]
It would be interesting to have a mode which attempts to format code in a way that minimizes diff sizes. This has not been high on the list of constraints so far since there is a very strong tension with having a target margin that the formatter attempts to reach but not overshoot. The optimal choice for minimizing diff size is probably to ignore the margin.

Note that ocamlformat formats the abstract syntax, as opposed to tidying up the concrete syntax. This means that any two pieces of code that the parser interprets the same, must format the same. In other words, a goal of ocamlformat is to take control of laying out the concrete syntax away from the programmer.

**Comment by edwintorok** [comment]
Minimizing diff size (ignoring whitespace though when computing the diff) could be an interesting way to gradually introduce `ocamlformat` in largish projects without too much initial churn.

**Comment by jberdine** [comment]
AFAIU, it wouldn't help with the initial conversion unless the project had an extremely uniform style already, and it just happened to be the same as that produced by the auto-formatter. Note that ocamlformat takes the result of the parser and completely ignores the concrete syntax that was parsed. (Small lie, placement of comments may look at the concrete syntax in a limited way.)

**Comment by vjeux** [comment]
For prettier, a JavaScript formatter, one thing I found is that there are patterns that you always want expanded, even if they fit in 80 columns.

For example function definition or class definitions.

```js
function f() {
  return true;
}
```

It seems like for function pattern matching, it's very unlikely you want to inline it. #my2cents

**Comment by jberdine** [comment]
There are definitely cases where always breaking no matter what the margin is the most readable. In OCaml I've seen many one-line anonymous `function`s, and many one-line simple 'getter' functions. I'm not positive either way, but so far as long as the margin isn't set too high (> 80), letting them fit on one line has seemed to work well. With wide (~ 120) margins, it's much easier to get poor formatting as the formatter tries hard to hit the margin.

**Comment by dbuenzli** [comment]
FWIW if I can make a function a oneliner that's what I'll do, in general I prefer compact code and sequences of `let` oneliners; including `match` ones. 

Regarding the idea of minimizing `diff` sizes I think it's a wrong approach: we need OCaml AST diffing, rather than line based diffing. @jberdine with all that knoweldge of OCaml's AST you must now have is `ocamldiff` your next target ;-) ?

**Comment by jberdine** [comment]
Diffing ASTs has certainly come up, but I don't have any plans to implement that, so don't let me hold anyone else back from getting it started! ;-)

**Comment by jberdine** [comment]
@edwintorok, does the `break-cases` option from #251 resolve this for you?

**Comment by edwintorok** [comment]
Thanks, I think it is close enough. I have a bit too many newlines though, maybe if the code after `->` fits on a line it shouldn't be broken, i.e. instead of this:
```ocaml
  let f x = function                                                                                                                                                                           
    | C ->                                                                                                                                                                                     
        1                                                                                                                                                                                      
    | D ->                                                                                                                                                                                     
        2 
```

Have this:
```ocaml
  let f x = function                                                                                                                                                                           
    | C ->1                                                                                                                                                                                      
    | D -> 2 
```

**Comment by jberdine** [comment]
Ok, thanks, so your suggestion is also for a breaking variant of the 'compact' style that breaks between cases but lets each case break naturally.

**Comment by jberdine** [comment]
Well, it is something I spent a while to make sure worked well, and I'd miss it. If it was lost there would be some changes I'd call regressions, but it isn't something that I would classify as a confusion risk. But I also want to keep one-line if-then-else expressions and they are very analogous. Without one-line pattern matches such as `match e with C _ -> true | _ -> false`, a bunch of noisy `isC` functions, one for each constructor in each type, inevitably end up polluting module interfaces.

**Comment by vjeux** [comment]
Fwiw, in a new language I’ve been working on, we’ve added “matches” operator where “a matches B” translates to “a match B -> true | _ -> false”. It’s been very handy.

**Comment by jberdine** [comment]
@vjeux Indeed, I have been tempted to write exactly that as a ppx ast transformer several times. Not as pretty as being builtin, but better than nothing.

**Comment by hhugo** [comment]
> ```ocaml
>   let f x = function                                                                                                                                                                           
>     | C ->                                                                                                                                                                                     
>         1                                                                                                                                                                                      
>     | D ->                                                                                                                                                                                     
>         2 
> ```

@gpetiot, janestreet has more or less the same request. Can we bump priority on this ?

**Comment by gpetiot** [comment]
This change has been done in the (relatively) new break-cases = toplevel that is the preset value on the janestreet profile.

**Comment by hhugo** [comment]
Ok. Should this issue be closed then ?
