### ISSUE TITLE
Feature request: alignment of "of" and arrow in long match

### ISSUE THREAD

**Issue by jzstark** [ocaml-ppx/ocamlformat#1202]
We recently came across several match expression alignment issues in Owl and related projects. For example, in [this](https://github.com/owlbarn/owl_symbolic/blob/master/src/onnx_specs/onnx_pb.ml#L1003-L1010) code the arrows are not aligned. Initially we thought it's perhaps because one or more of the match lines will be too long if they are aligned, but [this line](https://github.com/owlbarn/owl_symbolic/blob/master/src/onnx_specs/onnx_pb.ml#L947) above in the same file is obviously longer but still got aligned. I'm wondering the reason for this behaviour and if there is any way to fix it.

The other thing is that the word "of" is not aligned in type declaration, such as in this [example](https://github.com/owlbarn/owl/blob/master/src/base/neural/owl_neural_neuron.ml#L3156-L3199). It would be great if the "of"s could also be aligned as the arrows.

**Comment by gpetiot** [comment]
Hi, it looks like this is due to a pattern that we forgot to support when computing the length, we have to fix it.

To align type declarations, you can try `--align-constructors-decl` (or `--align-variants-decl` for variants).

**Comment by jzstark** [comment]
Thanks a lot @gpetiot!  The `--align-constructors-decl` works perfectly for alignment of type declarations.

**Comment by ryanrhymes** [comment]
Hope this small issue on pattern matching can be fixed soon :) 

ocamlformat has been applied to owl's whole codebase and helping us in enforcing a consistent style over 130K lines of OCaml code. Very impressive tool!

**Comment by gpetiot** [comment]
Sorry for the late update. The current strategy of ocamlformat does not include maintaining the alignment features, the current options will be deprecated for the 0.20.0 release and removed in the 0.21.0 release. This is not a behavior we plan to encourage and maintain.
Therefore I am closing this issue.
