### ISSUE TITLE
ocaml 4.10 support

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1218]
Hi,

Ocaml 4.10 [is going to be released soon](https://discuss.ocaml.org/t/ocaml-4-10-0-second-beta/5083). In order to support it, there are some things to wait for like having OMP and base working on 4.10, but also [some new language features to format](https://github.com/ocaml/ocaml/blob/b237282e97095f8ac9dfd8c18a03412406bde6e9/Changes#L202-L220). In particular:
- multi-indices for extended indexing operators
- `module _ = E`

We should make sure these are properly supported.

**Comment by xclerc** [comment]
For the record, I think `ocamlformat` does also turn:

    module M (_ : T) : ...

into:

    module M : functor (_ : T) -> ...

which, I would say, is a bit unexpected.

(However, I would have to double check whether it is
still true with the latest version.)

**Comment by emillon** [comment]
If I trust the CI (and I do!), OMP and base have compatible versions and we're now building with 4.10 :tada:
