### ISSUE TITLE
Feature request: uniform treatment of open statements

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1220]
On `master` with the conventional profile, the following diff appears:
```diff
 module M : sig
   open Type_core
-  open Type_core.Make (Monad.Identity)
+  open Type_core.Make(Monad.Identity)
 end = struct
   open Type_core
+
   open Type_core.Make (Monad.Identity)
 end
```

The concrete syntax in the `sig ... end` and the `struct ... end` blocks is identical, but they are formatted differently in two ways:

- `open`s are spaced in structures, but not in signatures.
- Functor arguments are spaced in structures, but not in signatures.

**Describe the solution you'd like**

I think the behaviour should probably be uniform here. Personally, I prefer the spacing of functor arguments as in structures and the more compact `open` lines in signatures, but any solution that unifies them seems preferable to what we have now.

CC. @Julow

**Comment by gpetiot** [comment]
This is fixed on the `conventional` profile now that `module-item-spacing=compact` (#1848), I'm thus closing this issue.
