### ISSUE TITLE
Method comments for multiline methods

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1221]
Hi,

In the default profile, comments attached to a method get formatted after the value. This can cause strange formatting like the following: 

```ocaml
let _ =
  object
    method sequence =
      print_endline "A" ;
      print_endline "B" ;
      print_endline "C" ;
      print_endline "D"
    (** Print several lines *)
  end
```

I don't think we should try to detect how long is the method, but a nicer output would be welcome. 

(this will applies only to method definitions (in expressions, not types), so maybe we can always put these comments before and have the configuration option only apply to the mli part?)

**Comment by jberdine** [comment]
This doesn't reproduce for me. Can you recheck and post your config settings?

**Comment by gpetiot** [comment]
I managed to get this formatting from this input:
```ocaml
let _ =
  object
    (** Print several lines *)
    method sequence =
      print_endline "A" ;
      print_endline "B" ;
      print_endline "C" ;
      print_endline "D"
  end
```
and using the `conventional` profile.

**Comment by gpetiot** [comment]
This code formats to itself:
```ocaml
let _ =              
  object
    (** Comment before *)
    method sequence = fooooooooooooooooooo
    (** Comment after *)
  end
```

the position of doc-comments is rightfully preserved, so I'm closing this issue
