### ISSUE TITLE
Bug: ocamlformat can't process combination of function application, local module opening and attribute

### ISSUE THREAD

**Issue by roddyyaga** [ocaml-ppx/ocamlformat#1226]
ocamlformat doesn't work on the following code (reduced example):
```ocaml
module M = struct
  let f x = x
end

let g=M.f ((let open M in f) [@ocaml.warning "-33"])
```
The error message is `BUG: ast changed` (although I got `BUG: generating invalid ocaml syntax` for the file where this originally occurred).

This is for ocamlformat 0.12 on OCaml 4.07.0 with the default configuration (the same thing also happened on my custom configuration).

**Comment by Julow** [comment]
Thanks for the report. We fixed the issue.
