### ISSUE TITLE
RFC: always preserve char and string escaping

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#1245]
Currently the options `escape-chars` and `escape-strings` have `decimal`, `hexadecimal` and `preserve` values.
Jules' script shows that nobody is using the `hexadecimal` value for any option, and I suspect the ones using `decimal`only have decimal escaping as input.
So we could just keep the `preserve` option. It would only be a simple modification in the code, but it would be more user-friendly to stay closer to the input in this case.
What do you think?

**Comment by Julow** [comment]
I agree with that.

**Comment by Julow** [comment]
This is closed by https://github.com/ocaml-ppx/ocamlformat/pull/1293
