### ISSUE TITLE
ml files are parsed as mlt files

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1248]
Hi,

I noticed a strange thing.

The `Translation_unit.t` we are using to parse `.ml` files actually uses toplevel operations rather than structure ones:

https://github.com/ocaml-ppx/ocamlformat/blob/3a4fabd1b753bbf8320ff7ad276d0b1731b87404/bin/ocamlformat.ml#L25-L33

Compared to say `Migrate_ast.Parse.implementation`, etc.

Is this intended? This seems OK since toplevel files are mostly a superset of implementation files, but still that looks a bit off.

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/pull/1020

**Comment by emillon** [comment]
OK I'll add a note, thanks!

**Comment by Julow** [comment]
The goal was to parse toplevel directives without requiring the users to use `--use-file`. That avoid confusion and weird syntax errors.

**Comment by emillon** [comment]
I think that #1329 clears things up. Thanks!
