### ISSUE TITLE
Bug: (*) is formatted without spaces in some contexts

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1249]
Hi,

In most cases `( * )` is formatted with spaces (that's necessary because otherwise it clashes with comment syntax).

But here's a case where it's not:

    let op = if b then ( * ) else ( + ) in ()

It gets formatted as `if true then (*) else (+)`, which crashes ocamlformat.

This seems to be related to the `~parens:false` param.

This also happens in the following contrived example (which might indicate a larger problem):

    assert ( * )

**Comment by CraigFe** [comment]
Investigating this now.

**Comment by CraigFe** [comment]
Indeed, this is to do with `fmt_expression ~parens:false`. 

We're passing this in a few places (including `Pexp_ifthenelse` and `Pexp_assert`) as a somewhat ad-hoc implementation of docking: i.e. the parent function drops the `(` in the appropriate place and instructs that the child not to drop one with `~parens:false`.

The issue with this approach is that it leaves insufficient context for formatting infix operators: the child function has no way of knowing if it's necessary to pad with spaces or not.

**Comment by CraigFe** [comment]
@emillon: I'm no longer working on this issue as I can't see a solution without major changes to `fmt_expression` or introducing another high-level abstraction in OCamlformat. 

With the current use of `Fmt.t` terms in lots of places, it's difficult to determine where wrapping has occurred (and especially when the wrapping is introduced by a parent function).

I could easily be wrong on this; perhaps @gpetiot or @Julow have ideas for how to approach this.

**Comment by emillon** [comment]
Yes, lack of inspectability is a known limitation of the current approach. Thanks for having a look!
