### ISSUE TITLE
Bug: attributes attached to certain kinds of binops

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1250]
Hi,

`ocamlformat` crashes on the following input:

    let _ = ([] @ []) [@a]

Interestingly, this only happens with some kinds of binary operators. For example `("" ^ "") [@a]` crashes as well, but `(0 + 0) [@a]` works. Part of the reason might be that `0 + 0 [@a]` is parsed with the attribute on the apply, not on the second operand.

**Comment by gpetiot** [comment]
`let _ = f (([] @ []) [@a])` remains unfixed.

**Comment by CraigFe** [comment]
I'm on it.
