### ISSUE TITLE
Feature request: Simpler spacing heuristics for modules

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1253]
**Is your feature request related to a problem? Please describe.**

OCamlformat `conventional` spaces module definitions according to some heuristic of the 'simplicity' of the module being defined. In particular, it seems to decide that any functor application longer than a single line or with more than one argument deserves a space:

```ocaml
module A = Make_A
module B = Make_B (Foo)
module C = Make_C (Foo)

module D = Make_D (Foo) ()

module E = Make_E (Foo) ()

module F = Make_F

module G = Make_G (struct
  let x = 0000_0000_0000_0000_0000_0000_0000_0000_0000
end)

module H = Make_H
module I = Make_I
```

**Describe the solution you'd like**

Personally, it seems better to only space module definitions that require more than a single line:

```ocaml
module A = Make_A
module B = Make_B (Foo)
module C = Make_C (Foo)
module D = Make_D (Foo) ()
module E = Make_E (Foo) ()
module F = Make_F

module G = Make_G (struct
  let x = 0000_0000_0000_0000_0000_0000_0000_0000_0000
end)

module H = Make_H
module I = Make_I
```

**Additional context**

This is similar to https://github.com/ocaml-ppx/ocamlformat/issues/1220 in that it advocates for more consistency & simplicity in spacing heuristics, so that the user is less often left wondering what the formatter is thinking. The situation for `open` statements (described in that issue) also suffers from strange line-spacing heuristics (but not the same ones):

```ocaml
module M : sig
  open Foo
  open Foo(A)
  open Foo(A)(B)

  open Foo.Aaaaaaaaa.Bbbbbbbbb.Ccccccccccc.Ddddddddddd.Eeeeeeeeee

  open Foo(A)
  open Foo
end = struct end
```

**Comment by gpetiot** [comment]
This is fixed on the `conventional` profile now that `module-item-spacing=compact` (#1848), I'm thus closing this issue.
