### ISSUE TITLE
Bug: attributes on tuples can cause ocamlformat to crash

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1256]
Hi,

The following programs cause ocamlformat to crash (due to dropped parens):

    ;;(0, 0)[@a]

and:

    let _ = f ((0, 0)[@a])

**Comment by CraigFe** [comment]
The first case is probematic even without an attribute:
```ocaml
;; (0, 0)
```
→
```ocaml
;;
0, 0
```

**Comment by CraigFe** [comment]
Scratch that, `;; 0, 0` is actually valid. News to me :slightly_smiling_face:
