### ISSUE TITLE
Bug: crash on optional argument rebound to non-variable

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1260]
Hi,

The following program causes ocamlformat to crash:

    let f ?a:(A) = ()

(it tries to format it as `let ?a:A = ()`)

I had to check [the exact parsing rules](https://github.com/ocaml/ocaml/blob/1fd6dc077d63fc8e0b36e2a684dae55a0f3383d4/parsing/parser.mly#L2088-L2091). What they say is that only ppat_var and ppat_any are recognized without parens.

I have to admit it's difficult to find a reasonable use case for this combination of features, but that's valid. A similar situation hapens with `?a:(())` and `?a:(0)`.

**Comment by CraigFe** [comment]
I'm on it.
