### ISSUE TITLE
Bug: AST changed with adjacent docstrings

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1266]
Hi,

The following program crashes ocamlformat:

    (**a*)(**b*)

(it renders each one on its own line, and so in the first case there's a single ptop_def and two in the second case)

**Comment by gpetiot** [comment]
Somewhat related to #1253, we force a break between these 2 structure items, no matter the size. We need to simplify the heuristics deciding whether or not we should break.
