### ISSUE TITLE
Feature request: A little bit more backwards-compatibility with older OCaml versions, particularly for BuckleScript?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#1274]
**Is your feature request related to a problem? Please describe.**
ocamlformat is consistently dropping older versions from the support matrix — and now, it doesn't even *install* on v4.06.1, the newest OCaml release available for BuckleScript (and even that is brand-spanking-new; most of us are still endeavouring to support v4.02.3!)

**Describe the solution you'd like**
It's a long shot; I understand there's a limited amount of development time, and I understand how much it can suck to work within the constraints and limitations of old, archaic releases (*raises hand* hi, JavaScript user here. 😩) … but I'd really like to publish ocamlformat to npm, and encourage adoption of it across the BuckleScript userbase. That's going to be difficult if the only versions I can build and publish are *old* versions, out-of-sync with the available documentation on the web and exhibiting issues already fixed upstream!

If you could find it within your collective hearts to continue supporting all the way back to 4.06.1, I'd really appreciate it — but I also understand how big an ask that is, and won't be offended if this Issue is unceremoniously closed!

**Comment by emillon** [comment]
Hi,

That's only a partial answer to your issue, but note that ocamlformat is "just" a binary (it does not read compiled files or things like that), so it's possible to build it using a recent version of ocaml, and use it with a completely different version of ocaml. Concretely, you can grab ocamlformat 0.14.0, build it with ocaml 4.10.0, put the binary in your $PATH, and use it in a ocaml 4.02.3 project. Opam does not support things like that, but maybe it can work on npm?

**Comment by jberdine** [comment]
The sort of usage that @emillon describes is the sort of thing that [ocaml-secondary-compiler](https://opam.ocaml.org/packages/ocaml-secondary-compiler/) ought to be able to enable.

There is another concern, which is whether concrete source code gets generated that is equivalent to a current compiler but e.g. doesn't parse in an older one. But I I think that so far such cases have been avoided.

**Comment by ELLIOTTCABLE** [comment]
Hm. Again yadda-yadda-yadda re: limited development time and this-is-a-lot-of-work; but it might eventually be worth the effort to keep a support-matrix test-suite? ∀ features, ∀ tuples (build-version, target-version), compile feature on build-version, run and verify result of feature on target-version.

**Comment by gpetiot** [comment]
Hi, ocamlformat now builds on 4.06.1 for some time (at least in our CI).

I understand your pain on being stuck with older versions for Bucklescript, but that sounds like a Bucklescript issue to me.
On our side making sure we are compatible with 4.02.3 (not even talking about parsing this version's asts, just being able to compile) would mean giving up on a lot of newest ocaml features or latests apis of some libraries (`base`, `stdio`, etc). Handling versions prior to 4.08 already imposes us enough constraints that we would love to not have.

About a support-matrix testsuite I don't know if it is possible with ocaml-ci but I can have a look.

**Comment by ELLIOTTCABLE** [comment]
Ah! 4.06.1 is definitely Enough™! That's great news, I just wasn't aware.

I'm gonna go ahead and close this, in that case. <3

**Comment by emillon** [comment]
FTR, here's the compatibility list for 0.14.2:

| ocamlformat | ocaml  | base   | outcome            |
| ----------- | ------ | ------ | ------------------ |
| 0.14.2      | 4.10.0 | 0.14.0 | :x:                |
| 0.14.2      | 4.10.0 | 0.13.2 | :heavy_check_mark: |
| 0.14.2      | 4.10.0 | 0.12.2 | :x:                |
| 0.14.2      | 4.10.0 | 0.11.1 | :x:                |
| 0.14.2      | 4.09.1 | 0.14.0 | :x:                |
| 0.14.2      | 4.09.1 | 0.13.2 | :heavy_check_mark: |
| 0.14.2      | 4.09.1 | 0.12.2 | :heavy_check_mark: |
| 0.14.2      | 4.09.1 | 0.11.1 | :x:                |
| 0.14.2      | 4.08.1 | 0.14.0 | :x:                |
| 0.14.2      | 4.08.1 | 0.13.2 | :heavy_check_mark: |
| 0.14.2      | 4.08.1 | 0.12.2 | :heavy_check_mark: |
| 0.14.2      | 4.08.1 | 0.11.1 | :x:                |
| 0.14.2      | 4.07.1 | 0.14.0 | :x:                |
| 0.14.2      | 4.07.1 | 0.13.2 | :heavy_check_mark: |
| 0.14.2      | 4.07.1 | 0.12.2 | :heavy_check_mark: |
| 0.14.2      | 4.07.1 | 0.11.1 | :x:                |
| 0.14.2      | 4.06.1 | 0.14.0 | :x:                |
| 0.14.2      | 4.06.1 | 0.13.2 | :heavy_check_mark: |
| 0.14.2      | 4.06.1 | 0.12.2 | :heavy_check_mark: |
| 0.14.2      | 4.06.1 | 0.11.1 | :x:                |

**Comment by jberdine** [comment]
Thanks! Am I correct in thinking that this sort of "relational" constraint between compiler and base versions isn't expressible in the language of opam package version constraints?

Would it be a significant loss to just say base = 0.13 and ocaml >= 4.06.1 ? I mean, is it significant that for older versions of ocaml, base 0.12 is also ok?

**Comment by emillon** [comment]
At the moment it's expressed in the opam language, but because base.0.12.2 depends on ocaml < 4.10. But you're right, I don't think there's a way to say that this particular combination isn't possible as ocamlformat dependencies.

For base, we were talking about having an explicit policy with @gpetiot. Supporting just one major version is a bit problematic because it can split the opam universe (you have to upgrade several packages at one time), but we could aim to support the last 2 major versions? This means either not using functions when the API break is in the supported window (e.g. `List.partition_map` for 0.13 & 0.14), or adding a small moving compatibility library like @gpetiot is doing in #1396.

How does that sound?

**Comment by jberdine** [comment]
See my comment on the PR, but in short I'm a bit worried about that plan. As far as I can tell, base simply is not intended to support clients that need compatibility with multiple versions. I think we either need the ability to conditionally compile based on the version of base (maybe via an env var or some configurator magic that I don't understand, hopefully not full-autoconf brute force), or to get rid of the base dependency and move to e.g. stddune or similar.

**Comment by jberdine** [comment]
Would it be flexible enough to support a single version of base for each version of ocaml?
