### ISSUE TITLE
Feature request: consistent formatting of `functor` keyword

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1285]
**Is your feature request related to a problem? Please describe.**

Formatting of `functor` is inconsistent according to whether the argument is named `_` or not:

```ocaml
(* Choice is preserved *)
module M (_ : S) = struct end
module M = functor (_ : S) -> struct end

(* Short form preferred *)
module M (X : S) = struct end
```

Preserving the choice in the `_` case is necessary because the short form is not supported pre-4.09 (https://github.com/ocaml/ocaml/pull/1958). It's odd to me that the choice of identifier causes the formatting to change.

**Describe the solution you'd like**

I can think of two solutions:
1. Preserve the choice in both cases;
1. Add an option to enable `4.09+` only syntax, and use it to use the short form in both cases.

Personally, I prefer the simplicity of the former option, but the latter is more consistent with the formatting of `let x = fun a -> ...`.

**Comment by Julow** [comment]
Keeping the syntax used in the source file makes sense to me.

This shouldn't be a breaking change, so no need to add an option, this can be the default behavior.
