### ISSUE TITLE
Feature request: avoid extra space after certain object types with attributes

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1295]
```ocaml
type t = {foo: unit [@a]}

type t = {foo: < .. > [@a] }
```

The extra space after `[@a]` in the second case is added to avoid outputting `>}` which is a keyword. However, it's not necessary to add the protecting space if the object type has an annotation, as is the case here.

The same is also true of:
- inline record types in variants
- polymorphic variants (the token `>]` has the same problem)
- class parameter lists (weird, since parentheses are added in this case)

```ocaml
type t = A of {foo: unit [@a]}

type t = A of {foo: < .. > [@a] }

type t = [`Foo of unit]

type t = [`Foo of < .. >[@a] ]

let _ =
  object
    inherit [b, unit] foo

    inherit [b, (< f: unit >[@a]) ] foo
  end
```

**Comment by emillon** [comment]
Maybe the labels are not precise enough, but I wouldn't call it a bug when we manage to output something equivalent (unlike the related #1267). That's probably worth fixing, but it's more of a style issue.

**Comment by CraigFe** [comment]
Yep, it's a good point. I've renamed the issue accordingly.

I think I just called it a bug because I'd already looked at the code by that point and decided it was unintentional behaviour :slightly_smiling_face:
