### ISSUE TITLE
Bug: inconsistent spacing before attributes of (polymorphic) variants

### ISSUE THREAD

**Issue by pascutto** [ocaml-ppx/ocamlformat#1297]
Maybe related to https://github.com/ocaml-ppx/ocamlformat/issues/1295 but I'm not certain, so submitting a new issue. Under default profile and 0.13.0, I get the following formatting, where polymorphic variants do not have a space before their attributes, while simple variants do, which does not seem right.
```ocaml
type classic = Variant [@attr]

type polymorphic = [ `Variant[@attr] ]
```
I personally prefer the former (with whitespace) solution, and I don't think it can lead to ambiguous situations.

**Comment by CraigFe** [comment]
The whitespace also helps distinguish attributes attached to the final `constructor_argument` rather than the `constructor_declaration`:

```ocaml
(* With whitespace *)
type t = A of int [@attr] | B of (float[@attr]) | C [@attr]

(* Without whitespace *)
type t = [`A of int[@attr] | `B of (float[@attr]) | `C[@attr]]
```
