### ISSUE TITLE
Add support for the OCaml object language

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#13]
The object language of OCaml is largely unimplemented. Designing the formatting of these constructs would be best done by someone with a lot of experience with them, who knows the readability pitfalls to avoid, etc.

**Comment by emillon** [comment]
A non-intrusive first step could be to support the `a#b` syntax. That would support code that uses object APIs without too much effort. My best guess is that `a#b` can be formatted with the same rules as `a.b`, but this is just a suggestion.

**Comment by hhugo** [comment]
Fyi, I'm working on this.
