### ISSUE TITLE
Bug: disabling through attribute doesn't fully work

### ISSUE THREAD

**Issue by SkySkimmer** [ocaml-ppx/ocamlformat#1318]
**Describe the bug**
On the following file:
~~~ocaml
[@@@ocamlformat "disable"]

module M = struct
end
include M
~~~
with empty `.ocamlformat`, ocamlformat inserts an empty line between `end` and `include` and `ocamlformat --check` exits with `1`.

**Comment by gpetiot** [comment]
Hi, we are aware of this bug, there are some cases where the `disable` is not enforced when printing the spaces/linebreaks between structure_items.
A more reliable alternative is adding the name of your files to not format to an `.ocamlformat-ignore` file.

Taken from the doc:

> If the disable option is not set, an .ocamlformat-ignore file specifies
       files that OCamlFormat should ignore. Each line in an
       .ocamlformat-ignore file specifies a filename relative to the directory
       containing the .ocamlformat-ignore file. Shell-style regular
       expressions are supported. Lines starting with # are ignored and can be
       used as comments.

**Comment by SkySkimmer** [comment]
> A more reliable alternative is adding the name of your files to not format to an .ocamlformat-ignore file.

That doesn't work for my situation where I want to whitelist a directory and disable on a file in that directory
ie `disable=true` in .ocamlformat, `bla/*.ml` in `.ocamlformat-enable` and then the attribute in `bla/foo.ml`

**Comment by gpetiot** [comment]
Is there a reason why you don't list the files to format in `.ocamlformat-enable` ?
```
bla/foo.ml
bla/bar.ml
```
I don't see it more difficult to maintain than adding a disable attribute at the beginning of each file.

**Comment by SkySkimmer** [comment]
Because I only want to disable 1 file out of all of them.
I guess I could put it in a subdirectory and get dune to copy it around maybe

**Comment by gpetiot** [comment]
Did you try:
- `disable=true` in the `.ocamlformat` at your root directory
- `disable=false` in the `bar/.ocamlformat`
- listing files to disable in the `bar/.ocamlformat-disable`

?

**Comment by SkySkimmer** [comment]
I guess not since I tried now and it works. Thanks.
