### ISSUE TITLE
Bug: ast changed when first-class module has attribute

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1333]
**Describe the bug**
```
ocamlformat: Cannot process "ast_changed.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
```

**How to Reproduce**
Formatted with ocamlformat built from 953c48a4f63be421f995fb5d4c4168dccd3d4fea, run with `--profile=janestreet`:
```
let _ = ((module M : S) [@alert "-foo"])
```

**Comment by gpetiot** [comment]
This has been fixed on master. Are there still a lot of comment bugs that make you use this build instead of master?
