### ISSUE TITLE
Bug: definitions in .mlt files are never adjacent

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1334]
**Describe the bug**
Formatting this:
```
open! Core
open! Async
```
...yields this:
```
open! Core

open! Async
```
In `.ml` and `.mli` files, `open` and other one-line declarations do not need blank lines between them. It seems most likely a bug that `.mlt` is treated differently.

**How to Reproduce**
Format with ocamlformat built from 953c48a4f63be421f995fb5d4c4168dccd3d4fea, run with `--profile=janestreet`.

**Comment by gpetiot** [comment]
As well as #1333 this has been fixed on master.
