### ISSUE TITLE
Feature request: preserve spacing before `and` inside an expression

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1341]
**Is your feature request related to a problem? Please describe.**
I recently refactored a series of mutually-recursive definitions into a `let` block to give them access to some shared mutable state. This is when I discovered that OCamlformat will not preserve spacing between mutually-recursive bindings in this position:

```ocaml
(* BEFORE *)
let rec x = a________________________________________________

and y = a____________________________________________________

and z = a____________________________________________________

(* AFTER: oops! not allowed spaces between definitions any more *)
let f () =
  let shared_state = ref false in
  let rec x = a________________________________________________
  and y = a____________________________________________________
  and z = a____________________________________________________ in
  ()
```
In my real-world example, this made the code much harder to read.

**Describe the solution you'd like**
This may be somewhat contentious, I suspect that OCamlformat should be preserving spacing between `Pexp_let` items just as it currently does with nested `let`-bindings:

```ocaml
let _ =
  let x = a____________________________________________________ in

  let y = a____________________________________________________ in
  ()
```

This does leave the question of what to do when the entire `Pexp_let` fits on a single line. In this case I think it's probably fine not to preserve and continue collapsing the `let` and `and` onto the same line:

```ocaml
let _ =
  let x = a and y = a in
  ()
```

**Comment by jberdine** [comment]
I don't think that "preserving" space present in the concrete input is the right first step, but an option to have spaces in the output seems like a good idea. My first inclination is to use `break-before-in` to control this, since it plays an analogous role for non-recursive bindings by placing the `in` alone on an almost-open line between adjacent bindings. That is, the proposal is to generate an open line after a binding in a recursive group if it does not fit on a line and `break-before-in=fit-or-vertical`.

**Comment by CraigFe** [comment]
> I don't think that "preserving" space present in the concrete input is the right first step, but an option to have spaces in the output seems like a good idea.

My expectation is that `let ... and ... in` blocks should behave similarly to `let ... in let ... in` blocks w.r.t. preservation of space. The latter has existing logic for allowing users to force a space (which is consistent with space preservation after `... ;`). I raised the issue mostly because I think the _lack_ of space preservation in this case is a surprising inconsistency. 

(Having said that, when I first found out about space preservation after `let ... in` I didn't like it, so take that with a pinch of salt...)

**Comment by gpetiot** [comment]
Sorry for the late answer.
My take on this is that `let ... and ...` items are toplevel items so it makes sense to have a blank line to separate them to make the code easier to read, we can argue it would be more consistent to do the same when they are local items, but the readability issue is less obvious to me, personally I find it confusing when there is an open line that would be cutting that toplevel let, it blurs the line of the "being able to read the structure of the code just by looking at the left margin" strategy that we tried to enforce in ocamlformat at some point.
We can keep this issue open but there is a low chance we will work on this, as most people are satisfied with how let bindings are handled right now and we wouldn't want to add more subtelties (or options).

**Comment by CraigFe** [comment]
Thanks @gpetiot. In the time since writing this issue, we picked up `module-item-spacing = compact`, meaning the change of spacing when refactoring a recursive group into a local one is now less of a problem for us.

FTR, I think my issue stemmed from the fact that `let ... <blank-line> and ... in` is not preserved by the conventional profile when `let ... in <blank-line> let ... in` _is_, and I was surprised that the two are not similar. However, given that the latter behaviour is [already contentious](https://github.com/ocaml-ppx/ocamlformat/issues/1826), I suspect I have the minority view :slightly_smiling_face:
