### ISSUE TITLE
To discuss: Where to document docstring language

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1347]
I think that the ocamlformat documentation should at least say that odoc is used to parse docstrings, and hence it inherits the accepted language from odoc.

That isn't entirely satisfactory though, since odoc itself does not document the languague it accepts. It does refer to the ocaml manual, but odoc does not accept the full ocamldoc language. This part is perhaps more of an odoc issue than an ocamlformat one, but it might be good to make the ocamlformat documentation self-contained.

For context, I recently ran into this as odoc fails to parse `{C ... }` docstrings which are correct according to the manual. I could not find anywhere that lists the differences between the odoc language and the manual.

**Comment by avsm** [comment]
It sounds entirely appropriate for odoc to document the accepted grammar explicitly. Just tagging @aantron for his opinion on this, since he wrote the carefully hand-crafted parser that odoc is now using.

**Comment by aantron** [comment]
I agree with this. For now, I added it to the TODO list in https://github.com/ocaml/odoc/issues/120#issue-315213156.

**Comment by gpetiot** [comment]
I added a first draft of the docstring documentation in #1922
