### ISSUE TITLE
Wrong commit is tagged 0.14.2

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1365]
The commit tagged 0.14.2 is not an ancestor of master. For version number computation, it really ought to be. Will moving the tag to f0f9606 break the opam package or anything similar?

**Comment by gpetiot** [comment]
I moved the tag on the right commit, the --version value is now fixed. I don't see what could be wrong with the opam package though. Feel free to re-open if you experience some issue.
