### ISSUE TITLE
Bug: newline escapes exceed margin

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1366]
**Describe the bug**
The newline escapes in this string literal are past the 90-character margin:
```
let _ =
  "_ _____________________ ___________ ________ _____________ ________ _____________ _____\n\n\
  \ ___________________ ______ _____ ___________ _______ _____ _____ __ ___ ______ ___"
;;
```

**How to Reproduce**
Style the above file with `ocamlformat --profile=janestreet`, using `ocamlformat` built from f6bc80a4bd46eab0ba37cb9308f22dd04cf86858 (the `gpetiot/janestreet` branch).

**Comment by gpetiot** [comment]
I've investigated a bit, there is indeed an exception when breaking literal strings down to the margin, as we never add a break just before a linebreak character `\n`. It seems to be the expected to always keep the linebreaks at the end of the line.

**Comment by ceastlund** [comment]
I can understand not wanting to break right before newlines, but perhaps a better way to do it is to not consider the newlines a break point, and instead treat them as part of the preceding word. Would it make sense to instead break before `_____\n\n`?
