### ISSUE TITLE
Feature request: Spaces before type annotations

### ISSUE THREAD

**Issue by adamsmd** [ocaml-ppx/ocamlformat#1369]
**Is your feature request related to a problem? Please describe.**

There might already be an option for this, but I haven't been able to find one. If there is, please let me know.

`ocamlformat` puts a space before type annotations, but I want it to not put that space.

Here is what I want:

    fun (x: int) -> (x: int)

Here is what `ocamlformat` produces:

    fun (x : int) -> (x : int)

You can test this with:

    echo 'fun (x: int) -> (x: int)' | ocamlformat --impl --enable-outside-detected-project -

**Describe the solution you'd like**

I'd like an option that makes ocamlformat produces the first and not the second.  Note that this applies to all uses of `:` (colon) for type annotation, not just the examples I give here.

**Comment by gpetiot** [comment]
Sorry for the late reply.
The current direction of ocamlformat is to not add new options, but rather focus on improving the existing preset profiles (default, ocamlformat, janestreet).

I think having a space before the `:` is the most common style in the community but maybe I'm wrong, I'm not opposed to a change like this if the community pushes for it, any thought on this point @samoht @CraigFe @Julow @jberdine ?
