### ISSUE TITLE
Ignore directories (different usecase)

### ISSUE THREAD

**Issue by tcoopman** [ocaml-ppx/ocamlformat#1370]
I know this issue has already been discussed in #865 but I think I have a different use case.
I have a codebase with both frontend and backend in one directory using bucklescript and ocaml.
This means I have a `node_modules` folder. The nature of this folder is so that it should not be added to version control.
So to ignore this folder with ocamlformat, I need to place a `.ocamlformat` file with disable in that directory.

It's not that this doesn't work, but when I delete `node_modules` or clone the repo again, I need to think about adding this file to it again.
Again, it works, but it's not exactly the most ergonomic workflow, so my question is, if this is something you would reconsider or not?

**Comment by gpetiot** [comment]
We are not planning to rework the way files are filtered in ocamlformat for now.
Would it not work for you to locally disable ocamlformat in the parent directory of `node_modules` (placing `disable` in the .ocamlformat file), and then listing the files to format in the `.ocamlformat-enable` file in the same directory?

**Comment by tcoopman** [comment]
I guess for `ocamlformat-enable` that I need to list all files (not directories)? If so, then this is not very practical.
Then I prefer my workaround :-)

**Comment by gpetiot** [comment]
Sorry for the late update, the most correct solution would have been to use an `.ocamlformat-ignore` file (cf. README), not sure why I didn't think of it when I first replied, sorry.
I'm closing this issue.
