### ISSUE TITLE
Automatically format comments

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#14]
- combine multiple full-line comments
```
(* ... *)
(* ... *)
```
together
```
(* ...
   ... *)
```
- remove leading '*' characters, converting e.g.
```
(* ...
 * ... *)
```
to
```
(* ...
   ... *)
```
- wrap lines similar to strings in #11 
- preserve formatting within literal string delimiters such as {| |}

**Comment by jberdine** [comment]
Some slight progress is made on this in 56d48075752c8370b533a06550f1cbdfbe949deb.

**Comment by gpetiot** [comment]
@jberdine Is this issue still relevant 3 years later? I'm not convinced that merging the comments together is a good idea given we check that comments are preserved.
