### ISSUE TITLE
Bug: comment between module and attribute triggers failure

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1409]
**Describe the bug**
ocamlformat fails on this code:
```
module M = struct end (* comment long enough to force line splitting *) [@ocaml.warning ""]
```

**How to Reproduce**
Ran with ocamlformat built from 10aabb33581dd528c06493cb31849300186dba95:
```
$ ocamlformat --profile=janestreet --enable-outside-detected-project --disable-conf-files /tmp/file.mlt 
ocamlformat: Cannot process "/tmp/file.mlt".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: formatting did not stabilize after 10 iterations.
```

**Comment by gpetiot** [comment]
I'm struggling to fix this on master, what makes it difficult is that the comment is attached to the docstring instead of the module structure. Apparently it is fixed with #1193 that reworks the comment attachment.

**Comment by ceastlund** [comment]
FWIW this is not a blocker for us. It only comes up in one place, which I've fixed by moving the comment and added a pointer to this PR. So if it needs to wait on #1193 for release, that's fine.

**Comment by gpetiot** [comment]
Apparently this is fixed on the `master` branch, @ceastlund can you check if this is also the case on the non-minimal code that originally triggered this error?

**Comment by gpetiot** [comment]
Closing this one, feel free to re-open if you encounter this issue again.
