### ISSUE TITLE
Bug: need options with a more consistent granularity

### ISSUE THREAD

**Issue by raphael-proust** [ocaml-ppx/ocamlformat#1446]
**Is your feature request related to a problem? Please describe.**

The config option `dock-collection-brackets` affects arrays, lists and records.  
The config option `break-collection-expressions` affects arrays and lists.  
The config options `space-around-{arrays,lists,records}` each affect one of arrays, lists, or records.

**Describe the solution you'd like**

The notion of collection should be the same across the different options.

Ideally there'd be `affect-X-like-so` options where `X` could be `collections` (meaning all), `arrays`, `lists`, `records` with more specific options taking priorities. Ideally this would apply to all options that affect collections.

**Comment by gpetiot** [comment]
Sorry for the late answer.
Our current strategy is to limit the number of options, and purely aesthetic options are on their way out (using a preset profile will still work, but not mix-and-match of options), so we try to not add new ones (we will communicate soon to give more details for the next releases).
I'm closing this issue then.

**Comment by raphael-proust** [comment]
That's actually good news! I'm perfectly happy with low-granularity of options if they are consistent across all kinds of similar constructs.

:+1:
