### ISSUE TITLE
negative ints in labelled parameter causing syntax error

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#145]
```
let f ?(x= -1) ?(y= f 0) () = x
```
is printed as:
```
let f ?(x=-1) ?(y= f 0) () = x
```
which does not parse (x=-1).

Note that the application is prefixed by a space (y).  What is the rule used by ocamlformat to decide whether to have a space or not after the = in the labelled parameter?

**Comment by jberdine** [comment]
I don't see this behavior (on master), I get:
```
let f ?(x= -1) ?(y= f 0) () = x
```
Can you confirm? But the code is [here](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Fmt_ast.ml#L841).

**Comment by mbarbin** [comment]
Ack, sorry this is a bug introduced by a local change.  My apologies for the noise.
