### ISSUE TITLE
Bug: "ast changed" with valid code

### ISSUE THREAD

**Issue by jchavarri** [ocaml-ppx/ocamlformat#1454]
Ocamlformat version: 0.15.0

**Describe the bug**
Ocamlformat fails to format some valid code.

**How to Reproduce**
Input:
```
let foo = (String.get [@bar]) filename (len - 1) = 'i'
```
Ocamlformat reports :
```
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.

  Code: -32603 
```

Edit: please ignore this part below 😅 
~~Also note something else, if the attribute is removed, ocamlformat succeeds, but the output is missing the `String.get` call:
Input:~~
```
let foo = String.get filename (len - 1) = 'i'
```
~~Output:~~
```
let foo = filename.[len - 1] = 'i'
```
----

The selected options are just `m=120` but can reproduce without that as well.

**Comment by emillon** [comment]
Interesting, it tries to format it as:

    let foo = (String.get [@bar]) filename len - 1 = x

I think that the is an edge case in `fmt_index_op` in the `Special` case.
