### ISSUE TITLE
Feature request: don't merge global config files with project ones

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1459]
I recently added a global `.ocamlformat` config file (inside `$XDG_CONFIG_HOME`) and set ` '(ocamlformat-enable 'enable-outside-detected-project)`, intending to use those styles for files / scripts that don't live inside repositories. I was surprised to find this caused my _projects_ to be reformatted with the global styles, even though those have their own `.ocamlformat` files. Looking at the documentation in the README, this behaviour is expected:

> .ocamlformat files in the containing and all ancestor directories for each input file are used, as well as the global .ocamlformat file defined in `$XDG_CONFIG_HOME/ocamlformat`. The global .ocamlformat file has the lowest priority, then the closer the directory is to the processed file, the higher the priority.

I find this behaviour problematic, since it means that using a global config file makes project formatting non-reproducible across machines. We've recently had some trouble with external contributors accidentally reformatting projects with a different style, and I suspect this is the cause.

Ideally, I would expect the behaviour to be:

 - When inside a detected project, configs are applied in top-down starting from the project root (i.e. excluding the global config file)
 - Otherwise, when `--enable-outside-detected-project` is set, apply the global config file.

Note that it's possible to get around the inheriting behaviour by setting `profile = conventional` in project `.ocamlformat` files, but we recently stopped doing that when it became the default. If the inheritance behaviour is to be kept the way it is, I suggest changing the [recommended `.ocamlformat` file](https://github.com/ocaml-ppx/ocamlformat#what-configuration-should-i-use) to include `profile = conventional` in the interests of reproducibility.

CC @Julow

**Comment by gpetiot** [comment]
I'm a bit worried by changing the meaning of the `--enable-outside-detected-project` option and the `.ocamlformat` config once again will confuse the users that already rely on it with the current semantics, but besides that it sounds like a reasonable suggestion.

**Comment by emillon** [comment]
TBH, I find the notion of a global ocamlformat config file to be a bit dodgy, for that reason.

**Comment by CraigFe** [comment]
> TBH, I find the notion of a global ocamlformat config file to be a bit dodgy, for that reason.

For my use-case at least, a global OCamlformat file is only useful for code that exists outside of projects, so it's just a convenience for experiments / little scripts to avoid needing to copy `.ocamlformat` files everywhere. (I have a single default `opam` switch for the same reason.)

I think the current semantics of global configs are dodgy, but that the notion is not inherently bad. Regardless, the existing semantics affect me as a project maintainer even if I personally choose to avoid global config files and jerry-rig my own solution.

**Comment by jberdine** [comment]
I am not confident that I understand all the use cases that might benefit from combining the global config with project/directory configs. But I don't know of any other than essentially what @CraigFe described. Pinging @avsm as I seem to recall that he wanted to override the per-project configs of everything in a duniverse at some point.

In code bases developed on multiple machines or by multiple people, it is basically necessary to have `profile =` in the config file at the root of the project.

I think that deprecating this merging behavior with a goal to remove it for 1.0 would be a good idea.

One possible subtlety that we need to keep in mind is to keep the current behavior for nested projects, where e.g. there are subdirectories of a project that themselves contain dune-project.

**Comment by CraigFe** [comment]
Discovered this morning: one consequence of the current behaviour is that any `version` field in the global config file must match the `version` fields in all project config files, otherwise OCamlFormat will fail. This is true even if the project config file sets a `profile`.

**Comment by gpetiot** [comment]
@emillon considering the evolution of duniverse/opam-monorepo since the last year, do we need to do something to improve this usecase?

**Comment by emillon** [comment]
I don't think there's anything specific to opam-monorepo here. To reiterate the common sentiment, I think that the only valid use cases for global config are:
- outside projects (so, no merging happens)
- as a template when creating a `.ocamlformat` file in a (new) project. this feature does not exist, but there wouldn't be merging either.
