### ISSUE TITLE
more use of punned record fields

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#146]
1183908325523bb3c260be788bb9001190dbf4ae addressed punned record field in expressions.  The same can be done in patterns:

```diff
-| let foo { bar = (bar : int); baz = (baz : int) } = body
+| let foo { bar : int; baz : int } = body
```
Maybe there are other places in the AST that I am not thinking of at the moment where this applies too.

**Comment by hhugo** [comment]
was fixed by https://github.com/ocaml-ppx/ocamlformat/pull/158
