### ISSUE TITLE
Escaping of invisible chars does not round trip in string litteral 

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#147]
```
let () = print_endline "Hello\xEF\xBB\xBF World."
```
formats (visibly) as:
```
let () = print_endline "Hello World."
```
In fact, the chars still seems to be part of the actual contents on disk, so I do not think there is an issue with the AST comparison check, but they become invisible in the buffer, which causes all sort of confusion.  Some editors may actually decide to remove them, or let the developer accidentally remove them since they are invisible.

**Comment by jberdine** [comment]
Perhaps the easiest approach, if somewhat of a cop-out, is to ignore the string in the parsetree for string literals, and instead read the bytes from the source using e.g. `Cmts.string_between`. It would be a bit of a hack, and doesn't help the use case as a code generator as opposed to a reformatter, but maybe worth it.

**Comment by mbarbin** [comment]
My wording in the issue title is misleading.  I am afraid round tripping introduces the risk of defeating the purpose of auto-formatting in that it may reintroduce debates on distinction without a difference.  Instead, maybe it is fine to choose a deterministic represent for those chars that is visible as opposed to invisible (I do not have intuition whether using hexa or binary is preferable).

**Comment by jberdine** [comment]
I see, the bytes are there, but editors and terminals do not display them. I wonder if that is because they are actually invisible, or if they try to get interpreted according to the locale (i.e. probably utf-8), which fails, so nothing is displayed. `\xEF\xBB\xBF` looks to be the utf-8 byte order mark, and for a few other cases I see some output. Maybe that is a magic 3-bytes that can just be special-cased, or have you seen other cases?

**Comment by hhugo** [comment]
I like the idea of leaving the escaping untouched using `Cmts.string_between`.

**Comment by mbarbin** [comment]
hhugo convinced me off line.  It may be too hard of a problem to come up with a deterministic reverse-engineering process that guess back the intent of the programmer, thus giving back control seems OK.
We suspected you would still want ocamlformat to be allowed to wrap the string and rework line breaks, so the round-trip logic would not be applied to all the range 0-255.

**Comment by mbarbin** [comment]
duplicate of #10
