### ISSUE TITLE
Bug: misalignment of cases in docked `function` match

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1492]
The following snippet is formatted with `ocamlformat.0.15.0`:

```ocaml
;;
f
  (fun _ -> function
    | true ->
        let () = () in
        () | false -> ())
  ()
```

The `| false ->` case is oddly packed onto the same line as the body of the former case in a way that I suspect is unintentional.

**Comment by CraigFe** [comment]
Presumably related to this, the following snippet does not stabilise:

```
;;
f
  (fun _ -> function
    | true ->
        let () = () in
        ()
        (* comment *) | false -> ())
  ()
```

(Happy to split this into a separate issue if you decide that it is unrelated.)

**Comment by gpetiot** [comment]
Hi, I'm not sure this is related indeed.

**Comment by CraigFe** [comment]
Separate issue it is, then: https://github.com/ocaml-ppx/ocamlformat/issues/1493.
