### ISSUE TITLE
Bug: double spaces in document code blocks are not preserved

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1494]
The following diff is suggested by `ocamlformat.0.15.0`, with the `parse-docstrings` option:

```diff
-(** [trim "  "] is [""] *)
+(** [trim " "] is [""] *)
```
Here, Odoc changes the string inside the code block, which changes the semantics of the example being documented. I suspect that code segments in documentation comments should never have their AST changed by formatting (just as is true of the file AST itself).

This seems likely to be an issue with Odoc itself, but I'm reporting here first in case there are any subtleties to OCamlformat's usage of the parser.

**Comment by emillon** [comment]
Thanks for the bug report. The odoc AST seems fine:

```
utop # Odoc_parser.parse_comment_raw ~location:(Location.none.loc_start) ~text:{| [trim "  "] is [""] |};;
- : Odoc_parser.Ast.docs Odoc_model.Error.with_warnings =
...
         value = `Code_span "trim \"  \""};
...
```

But it seems a bit weird to normalize contents like this:

https://github.com/ocaml-ppx/ocamlformat/blob/dce10205f9866b9eea7105d5c4045d3a5d34ccba/lib/Fmt_odoc.ml#L142-L145

If you can investigate with @Julow that'd be great!
