### ISSUE TITLE
String and array operator rewriting can change program semantics

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1500]
Hi,

As of 0.15.0, OCamlformat decides whether to use `a.[i]` or `String.get a i` depending on the context (similarly for `String.set`, `Array.get` and `Array.set`). This works under the assumption that `a.[i]` is parsed as `String.get i`, so both constructs have the same semantics.

However, that's not always true. [If `Clflags.unsafe` is set, the operators are parsed as the unsafe variants](https://github.com/ocaml/ocaml/blob/5e15dd8eb5b3b5f0e66f9166d4de2bcee22aa57d/parsing/parser.mly#L243-L245), e.g. `String.unsafe_get a i`.

Consider the following program:

    let () = String.get "hello world" (-8) |> Char.code |> Printf.printf "%d\n"

Built with the following dune file:

```
(executable
 (name t)
 (flags :standard -unsafe))
```

When executed, it outputs an error:

    Fatal error: exception Invalid_argument("index out of bounds")

This is because `String.get` always does the check.

When reformatting the above program, it gets rewritten to:

    let () = "hello world".[-8] |> Char.code |> Printf.printf "%d\n"

When executed, it outputs `252`, the value of `String_tag` (this is just to show that the program is now unsafe; it could of course cause kind of memory error later in the program).

So, what should we do? Given that the two constructions do not always have the same semantics depending on how the file is compiled, I think that the only valid way to handle the situation is to preserve what can be found in the file.

**Comment by emillon** [comment]
Note that Bigarray functions are affected too through [a different code path](https://github.com/ocaml/ocaml/blob/5e15dd8eb5b3b5f0e66f9166d4de2bcee22aa57d/parsing/parser.mly#L296).

**Comment by gpetiot** [comment]
Good catch, the better solution is maybe to always preserve whatever syntax the user used indeed, as I'm not even sure we should rewrite the unsafe_get into the short infix syntax as well.

**Comment by gpetiot** [comment]
This is one case where it would be handy to have our own copy of the parser so we could define a different node for the infix form and the get application. Right now we would need to look up the source and that would require passing the Source.t around and around in a lot of Ast functions for things such as deciding whether or not we should add parentheses.

**Comment by emillon** [comment]
Maybe we can use a different strategy for some cases. For example, comparing `s.[i]` and `String.get s i`, in the first case 
the `String.get` expression and ident get a ghost loc but not in the second case. (tested on 4.11 and 4.12 which give the same results)
