### ISSUE TITLE
Preserving short-form structure item extensions

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1501]
Hi,

Structure items can benefit from extension sugar as well, but at the moment the long syntax is always used.

For example, `open%ext M` is always rewritten to `[%%ext open M]`. For consistency with what we did in #1293 for `extension-sugar`, I think that we should emit the concrete syntax from the source file.

**Comment by hhugo** [comment]
Subset of #410

**Comment by emillon** [comment]
Ah, I was sure there was an issue for this. Thanks!
