### ISSUE TITLE
Tests do not pass on 4.12

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1508]
Even with the fixes linked in #1505, `dune runtest` doesn't pass.
This is not an exhaustive list, but for example:

Warning syntax changed (can be polyfilled with a postprocessor):

```diff
-Warning 47: illegal payload for attribute 'ocamlformat'.
+Warning 47 [attribute-payload]: illegal payload for attribute 'ocamlformat'.
```

Some comments move:

```diff
-let {a (*a*) : a} = e
+let {a : a (*a*)} = e
```

Functor sugar is not recognized:

```diff
-  module Make : functor (TV : TYPEVIEW with type t = t) -> USERCODE(TV).F
+  module Make (TV : TYPEVIEW with type t = t) : USERCODE(TV).F
```

**Comment by emillon** [comment]
N.B. when we close this issue, let's not forget to update the opam metadata.

**Comment by gpetiot** [comment]
@emillon do you still have non-passing tests?

**Comment by emillon** [comment]
It's all good now!
