### ISSUE TITLE
Some comments are attached differently in 4.12

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1513]
Hi,

For this program:

```ocaml
let {a (*a*) : a} = e
```

The locs are different in 4.12 (since ocaml/ocaml#8987):

```diff
           pattern (./c.ml[1,0+4]..[1,0+17])
             Ppat_record Closed
             [
-              "a" (./c.ml[1,0+5]..[1,0+6])
-                pattern (./c.ml[1,0+5]..[1,0+16])
+              "a" (./c.ml[1,0+5]..[1,0+6]) ghost
+                pattern (./c.ml[1,0+5]..[1,0+16]) ghost
                   Ppat_constraint
-                  pattern (./c.ml[1,0+5]..[1,0+16])
+                  pattern (./c.ml[1,0+5]..[1,0+6])
                     Ppat_var "a" (./c.ml[1,0+5]..[1,0+6])
                   core_type (./c.ml[1,0+15]..[1,0+16])
                     Ptyp_constr "a" (./c.ml[1,0+15]..[1,0+16])
```

This causes a diff in the test suite (part of #1508):

```diff
-let {a (*a*) : a} = e
+let {a : a (*a*)} = e
```

The difference in ghostness is due to the fact that when punning is used, [the pattern is not present in the source, only the label is](https://github.com/ocaml/ocaml/pull/8987/files#r329310705). The change seems innocuous but I wonder if it would make sense to make sure that we don't attach comments to ghost locs.

On the other hand, the difference of loc in the `Ppat_constraint` node might cause the comment to be attached elsewhere:

```
let {a (*a*) : a} = e
     ~~~~~~~~~~~       4.11
     ~                 4.12
```

**Comment by gpetiot** [comment]
I'm losing my hair on this one, to me it's acceptable to change the comment position, if the compiler keeps introducing regressions we cannot have as many workarounds as that.
