### ISSUE TITLE
Bug: extension points no longer format idiomatically

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1522]
**Describe the bug**
Start with this code:
```
[%%test_module let _ = (module struct end)]
```

In ocamlformat built from 10aabb33581dd528c06493cb31849300186dba95 (0.14.x), it gets reformatted to what we would normally write:
```
let%test_module _ = (module struct end)
```

In ocamlformat built from 1bf68a70f1480df80a8ab0bd20a799b8e1df0081 (0.15.x), it does not get reformatted. It says with `[%%test_module ...]` wrapped outside the `let`.

When code generators use `Pprintast`, they print the `%%test_module` version. We then pipe the results through `ocamlformat`, hoping to get something more like the idiomatic `let%test_module` version. We hope we can restore the old behavior so generated code can stay a little more readable.

**How to Reproduce**
Run using `--profile=janestreet`.

**Comment by hhugo** [comment]
In my experience, deciding between the regular vs sugar syntax depends too much on the context. My hunch is that you're use case would be better handled by a ppx_refactor

**Comment by gpetiot** [comment]
Hi, maybe we can make the `janestreet` profile use `extension-sugar=always` if you expect this behavior. We planned to deprecate this option to only keep the "preserve" behavior and remoe the "always" one. Let us know if the solution suggestion by hugo suits you or if we need to keep the `extension-sugar` option in ocamlformat.

**Comment by hhugo** [comment]
I don't think `extension-sugar=always` is something that we want for metaquot code for instance.

**Comment by ceastlund** [comment]
@hhugo: Refactoring the code in-place (via ppx_refactor or any other means) doesn't help, this is unchecked-in, generated code. I just want the generator to produce readable code.

@gpetiot: I agree with Hugo that `extension-sugar=always` is not what I want. I really just want to whitelist a few forms we use like `let%test` and `let%bind`. I disagree with Hugo that these will be context-senstive; I don't think I ever want to see `[%bind let ...]`, for example.

**Comment by hhugo** [comment]
My point is that the formatting will depend on a context that is the ppx extension used. Of course, one could hard-code decisions for a bunch of cases / extension names, hoping that there will not be any name overlap/conflicts between ppxes.

There was similar decision issue regarding position of attributes in the past:  `let [@attr] x = y` vs `let x = y [@@attr]`.
This was resolved by preserving the position in the source. Here again, one can hard code a list of known attribute names (like in https://github.com/ocaml-ppx/ocamlformat/pull/681/commits/c85c870480352b866b2f83a07408e01c0e87c5c0) but it's not ideal.

**Comment by ceastlund** [comment]
After talking to Hugo, it's no longer clear to me that we need or want this. I'm going to close the issue.
