### ISSUE TITLE
Consider making binary releases

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#1539]
I would like to experiment with `ocamlformat` but it takes a bit of work to build if you are not using `opam`. I think making binary releases available would help (esp for Windows, where `opam` is not natively available).

Have you considered this possibility?

**Comment by emillon** [comment]
Yes, I agree this would be valuable. I think that both windows support and artifacts building are on the roadmap for ocaml-ci, which should make that easier. In the meantime I'll check if it's possible to add binaries to an existing release.

**Comment by emillon** [comment]
I tried to build a 0.15.1 exe and add it to the existing release, but the logic to compute the version number does not work on Windows in that version. Starting from 0.16.0 we're using dune-build-info (#1133) which works on Windows. I'll add an exe for 0.16.0 once the release is done (probably by the end of the week).

I'm not super familiar with distributing windows binaries - will a binary built on my machine (in a +mingw64 switch from fdopen's fork) just work or will users need some extra DLLs?

**Comment by nojb** [comment]
> I tried to build a 0.15.1 exe and add it to the existing release, but the logic to compute the version number does not work on Windows in that version. Starting from 0.16.0 we're using dune-build-info (#1133) which works on Windows. I'll add an exe for 0.16.0 once the release is done (probably by the end of the week).

Great, thanks!

> I'm not super familiar with distributing windows binaries - will a binary built on my machine (in a +mingw64 switch from fdopen's fork) just work or will users need some extra DLLs?

I *believe* it should work out-of-the-box.

**Comment by emillon** [comment]
@nojb I just did so. Does https://github.com/ocaml-ppx/ocamlformat/releases/download/0.16.0/ocamlformat-0.16.0.exe work?

**Comment by nojb** [comment]
> @nojb I just did so. Does https://github.com/ocaml-ppx/ocamlformat/releases/download/0.16.0/ocamlformat-0.16.0.exe work?

Yes, it works! Thanks, this is great, and it would be much appreciated if releases from now on were similarly available.

**Comment by gpetiot** [comment]
I think we can close this one!
