### ISSUE TITLE
Bug: Extra spaces in compact profile

### ISSUE THREAD

**Issue by Kakadu** [ocaml-ppx/ocamlformat#1548]
**Describe the bug**
Inserts weird spaces before ; when compact profile is enabled. Pretty sure that it was not intentional

**How to Reproduce**
```
➜  /tmp cat a.ml
let () =
  let xs = [1; 2; 2; 2; 2; 2; 2; 2; 2; 2; 2] in
  print_endline ""; 
  exit 0
➜  /tmp ocamlformat --enable-outside-detected-project --profile=compact a.ml       
let () =
  let xs = [1; 2; 2; 2; 2; 2; 2; 2; 2; 2; 2] in
  print_endline "" ; exit 0
➜  /tmp ocamlformat --version
0.16.0
```

**Comment by gpetiot** [comment]
Hi, the compact profile sets `sequence-style = separator` which adds spaces around the semicolon, you can set `sequence-style = terminator` to remove this space.

**Comment by Kakadu** [comment]
Okay, maybe it's not a bug but usefulness of another switch looks like arcane knowledge...
