### ISSUE TITLE
Feature request: Allow to separatedly control `compact | sparse` for variant or record type decl

### ISSUE THREAD

**Issue by hackwaly** [ocaml-ppx/ocamlformat#1585]
I want to set variant type decl `compact` and record type decl `sparse`.

**Comment by gpetiot** [comment]
Sorry for the late reply, `ocamlformat`'s current direction is aiming towards removing this kind of options, and in a few releases it won't be able to tune this kind of settings outside of what is provided by the profiles. These profiles are constantly improved to get closer the most common styles in the ocaml community, I encourage you to use one of these (default, ocamlformat, janestreet).
I'm thus closing this issue.
