### ISSUE TITLE
Feature request: An option to allow code-blocks in docstrings to pass through unmolested, but still parse/wrap the *rest* of the docstring

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#1597]
**Is your feature request related to a problem? Please describe.**
In writing a parser for a non-OCaml language, `--parse-docstrings` attempts to treat my codeblocks as valid OCaml source-code, thus changing the semantics in their *actual* language. i.e.:

```diff
@@ -70,7 +70,7 @@ and word = string or_subexpr list
     A single shell "word" can actually be composed of multiple quotations or
     subexpressions, as long as they are not separated by whitespace:
 
-    {[ echo "this""is""only""a""single"(echo word)(echo also) ]}
+    {[ echo "this" "is" "only" "a" "single" (echo word) (echo also) ]}
 
     Such a composition is represented in this type, by a series of {!or_subexpr}s in a
     [list]. *)
```

**Describe the solution you'd like**
I understand (and in other circumstances, appreciate!) the purpose behind this behaviour. Unfortunately, it's really problematic in some circumstances (like mine, here.)

Ideally, I'd love it if "is this OCaml and should it be formatted" were determined *per-codeblock*, as it is in Markdown (i.e. `{[ocaml Here is some code ]}`), but such an extension seems rather unlikely.

In the absence of that, I'd at least like to be able to have my docstrings wrapped, and just disable all codeblock-formatting across the entire project; perhaps `--no-parse-docstring-codeblocks`?

(See, relatedly, Prettier's [`--embedded-language-formatting`](https://prettier.io/docs/en/options.html#embedded-language-formatting) option)

**Comment by hhugo** [comment]
What don't you use the verbatim block in this case ? `{v    v}` ?

**Comment by ELLIOTTCABLE** [comment]
Two reasons, approximately in order of importance to me:

1. It's, semantically, code — not simple `<pre>`formatted text; and
2. the documentation-generator produces unhighlighted output. (Which in *some* other cases similar to mine, might actually be desirable; but personally, I'd rather some common, basic language-constructs get best-effort highlighting, than none at all):

<img width="793" alt="Screen Shot 2021-02-05 at 1 21 39" src="https://user-images.githubusercontent.com/200/107002225-82891a80-6750-11eb-8b5e-dd0a17af4268.png">

**Comment by gpetiot** [comment]
Now that we handle odoc-parser's block metadata (#1713), we could choose to only format `@ocaml` blocks.

**Comment by Julow** [comment]
Odoc recently got a syntax for specifying the language of the code block:

```
{@ocaml[
 code here
]}
```

Ocamlformat should match on it indeed but when it's not specified, I think it should be treated as OCaml code anyway. This is what is planned for Odoc and what Mdx does.

You could use any string as language tag. Note that Odoc highlights any code as OCaml for now (todo).

**Comment by gpetiot** [comment]
Should we just filter out the ones that explicitly have a language tag other than OCaml?

**Comment by Julow** [comment]
> Should we just filter out the ones that explicitly have a language tag other than OCaml?

Yes that's what I meant.
