### ISSUE TITLE
Align constructor comments 

### ISSUE THREAD

**Issue by nrolland** [ocaml-ppx/ocamlformat#1632]
Would it be possible to align comments after constructors ?

e.g to go from (with `align-constructors-decl = true` - presented [here](https://tarides.com/blog/2019-06-27-release-of-ocamlformat-0-10#horizontal-alignment), cf [docs](https://github.com/ocaml-ppx/ocamlformat/blob/master/ocamlformat-help.txt)) 

```ocaml
(** A type for points*)
type eitherPoint =
  | TwoD   of float * float  (** point in 2D plane*)
  | ThreeD of float * float * float  (** point in 3D space *)
```

into 
```ocaml
(** A type for points*)
type eitherPoint =
  | TwoD   of float * float          (** point in 2D plane*)
  | ThreeD of float * float * float  (** point in 3D space *)
```

**Comment by gpetiot** [comment]
Hi, we are not sure to keep the `align-*` options into ocamlformat as we are progressing towards the 1.0 release. The main reason is that this kind of style generates a lot of additional changes, e.g. if you add or delete the longest line all the other lines aligned with it will be modified at the same time, and that's not the kind of style we are trying to promote with ocamlformat (even with a flag). As a whole we are trying to reduce the number of options to a minimum before we release 1.0 (still under discussion).

For this reason I am not sure we should work on changing/fixing the behavior of these options.

**Comment by nrolland** [comment]
Hi, I value that the `align-*` reduce superfluous text noise. The resulting improved readability might depends on other visual clues, like, for comments, the coloring of the editor (at play on GitHub in the example above, for instance). with coloring, it's more of an aesthetic than a readability issue.  I defer to you to appraise wether that's overall worth maintaining in the context of this project, and close this issue if need be. thank you for this tool.

**Comment by gpetiot** [comment]
We deprecated the `--align-*` options for the next release (0.20.0), and they will be removed for the 1.0 release, as this is something we planned some time ago.
I am thus closing this issue. (Maybe the behavior you are looking for can be achieved by post-processing the ocamlformat output, but it is not worth maintaining in ocamlformat itself)
