### ISSUE TITLE
Bug: undesirable comment placement after last match case

### ISSUE THREAD

**Issue by mjambon** [ocaml-ppx/ocamlformat#1662]
I can't find a good way to have a comment following the expression in the last match case. See example below.

Input:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok (* "static" *)
```

Output with ocamlformat version b04850d (May 21, 2021) with no options or with `--profile conventional`:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok
(* "static" *)
```

Expected output:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> identifier env tok (* "get" *)
  | `Set tok -> identifier env tok (* "set" *)
  | `Async tok -> identifier env tok (* "async" *)
  | `Static tok -> identifier env tok (* "static" *)
```

A workaround is to place the comment before the expression. It looks like this and it's not that great:
```ocaml
let reserved_identifier (env : env) (x : CST.reserved_identifier) : ident =
  match x with
  | `Get tok -> (* "get" *) identifier env tok
  | `Set tok -> (* "set" *) identifier env tok
  | `Async tok -> (* "async" *) identifier env tok
  | `Static tok -> (* "static" *) identifier env tok
```

**Comment by MisterDA** [comment]
I think I have a similar case in a type declaration (it's the last branch):

```diff
-  | Ldlib of string (* ccomp_type *) * string (* library flag or name given to compilers when they
-                                                 are supposed to invoke the linker *)
+  | Ldlib of string (* ccomp_type *) * string
+(* library flag or name given to compilers when they
+   are supposed to invoke the linker *)
```

**Comment by mjambon** [comment]
Our company, [r2c](r2c.dev), will make an $800 donation to the [charity of your choice](https://www.charitynavigator.org/) when you* deliver this feature.

you = any person or group who does the work. Looks like the core ocamlformat team [is on it](https://github.com/ocaml-ppx/ocamlformat/pull/1667#issuecomment-1015734475).

**Comment by mjambon** [comment]
Hey @gpetiot! Thanks for your work on this issue. Sorry for coming back to this a little late. Please let us know which charity you'd like to support. You just need to pick one from https://www.charitynavigator.org/ and we'll handle the rest. My work email is martin@r2c.dev.
