### ISSUE TITLE
Bug: ocamlformat changes the end-of-lines style on Windows

### ISSUE THREAD

**Issue by MisterDA** [ocaml-ppx/ocamlformat#1666]
**Describe the bug**
On Windows, if I use files using Unix end-of-lines (a single LF character) and run ocamlformat on them, ocamlformat will change the end-of-line to Windows style (CR LF characters), introducing noise in the diff. I'd like ocamlformat to respect the original EOL style, or provide an option to configure the end of line characters.

**How to Reproduce**

This assumes an unix shell in a Cygwin environment on Windows.

```shell
$ dune init executable shaihulud && git init .
$ dos2unix dune shaihulud.ml # convert to Unix style
$ chmod -x dune shaihulud.ml
$ sed -i 's/^/    /g' shaihulud.ml # weird indent so that ocamlformat may process the file
$ dune build @fmt --auto-promote
diff --git a/shaihulud.ml b/.formatted/shaihulud.ml
index 513361f..9cc7de4 100755
--- a/shaihulud.ml
+++ b/.formatted/shaihulud.ml
@@ -1 +1 @@
-             let () = print_endline "Hello, World!"
m+let () = print_endline "Hello, World!"
Promoting _build/default/.formatted/shaihulud.ml to shaihulud.ml.
$ hexdump -C shaihulud.ml
00000000  6c 65 74 20 28 29 20 3d  20 70 72 69 6e 74 5f 65  |let () = print_e|
00000010  6e 64 6c 69 6e 65 20 22  48 65 6c 6c 6f 2c 20 57  |ndline "Hello, W|
00000020  6f 72 6c 64 21 22 0d 0a                           |orld!"..|
00000028
```

You can see that ocamlformat has converted the file to CR LF end-of-lines.

**Comment by hhugo** [comment]
Related to https://github.com/ocaml-ppx/ocamlformat/pull/274
@gpetiot , do you remember why 274 didn't work out ?

**Comment by MisterDA** [comment]
Ah, I didn't see this was already a wontfix.

**Comment by gpetiot** [comment]
I don't remember exactly what was wrong with #274, reading the discussion it seems Josh pushed for a postprocessing solution. It's really not convenient for me to test on windows, but if someone is working on windows and wants to look further on how to fix it in ocamlformat, feel free to work on a patch!

**Comment by jberdine** [comment]
https://github.com/ocaml-ppx/ocamlformat/pull/274 stalled because no-one could test the PR on windows (cygwin does not count). @MisterDA if you are willing to update https://github.com/ocaml-ppx/ocamlformat/pull/274 to master, and can test on windows, then it can move forward. There are no known blockers.

**Comment by MisterDA** [comment]
Yes! I'll see what I can do :)
