### ISSUE TITLE
Feature request: formatting of list syntax like 0.16

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1674]
I appreciate that the 0.16 implementation of sugared list syntax was non-trivial, but I'm going to open this as a means of remembering that it would be good to find an implementation that can produce the 0.16 output without just reverting https://github.com/ocaml-ppx/ocamlformat/pull/1567 (which fixes comment attachment issues).

Was there anything written summarizing what blocked fixing those issues without the heavier approach of https://github.com/ocaml-ppx/ocamlformat/pull/1567?

**Comment by gpetiot** [comment]
@emillon given the diff of the 0.19.0 preview I think it may be worth it to fix this one before releasing 0.19.0
