### ISSUE TITLE
Bug: misaligned higher-order functor parameters

### ISSUE THREAD

**Issue by craigfe** [ocaml-ppx/ocamlformat#1678]
The following example formats to itself with `ocamlformat.0.18.0`:

```ocaml
module F1 (G : functor (_ : T) ->
  T) (A : sig
  val x : int
end) =
struct end

module F2 (G : functor (_ : T) ->
  T_________________________________________________________________________)
                                                                            (A : sig
  val x : int
end) =
struct end

module F3
    (G : functor
      (_ : T____________________________________________)
      (_ : T____________________________________________)
      ->
  T) (A : sig
  val x : int
end) =
struct end
```

It appears that using immediate `functor ..` types confuses OCamlformat's normal placement strategy for functor parameters, resulting in a variety of unusual indentation. I'm not sure entirely what I'd expect this to format to, but roughly speaking:
 - In the first case, `F1`, I'd expect `G` to not break, and `A` to either start on the subsequent line or dock after `G`.
 - For `F2`, I'd expect `A` to start much further to the left.
 - For `F3`, I'd expect the `T` result type of `G` to be indented by another couple of levels (and perhaps `A` to start on its own line, left-aligned with `G`).

I don't know whether these are known limitations of the placement strategy, in which case feel free to reclassify this issue as a feature request or close it altogether.

**Comment by Julow** [comment]
Should be fixed, thanks for reporting.
