### ISSUE TITLE
Windows binary for ocamlformat 0.18 ?

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#1700]
The latest release did not include a Windows binary. Would you consider making one, as with the previous versions? Thanks!

**Comment by gpetiot** [comment]
Hi, I've just uploaded the binary here: https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.18.0
Please let us know if everything is working as expected!

**Comment by nojb** [comment]
> Hi, I've just uploaded the binary here: https://github.com/ocaml-ppx/ocamlformat/releases/tag/0.18.0
> Please let us know if everything is working as expected!

It doesn't work for me, and the binary seems to be ELF instead of PE:

![image](https://user-images.githubusercontent.com/113560/124320740-be4bd300-db7c-11eb-887f-beb33d182769.png)

Thanks!

**Comment by gpetiot** [comment]
Oh right! Well I have no idea how to do that then, I tried to install ocaml-windows without any success. I think @emillon had a look at how to compile ocamlformat on windows (doesn't work for me either)

**Comment by emillon** [comment]
Sure, I'll build and upload a binary.

**Comment by emillon** [comment]
Done: https://github.com/ocaml-ppx/ocamlformat/releases/download/0.18.0/ocamlformat-0.18.0.exe

**Comment by nojb** [comment]
> Done: https://github.com/ocaml-ppx/ocamlformat/releases/download/0.18.0/ocamlformat-0.18.0.exe

Thanks! Now that #1702 has been merged the process of building the Windows binary will hopefully become easier :)
