### ISSUE TITLE
Bug: ast changed

### ISSUE THREAD

**Issue by bcc32** [ocaml-ppx/ocamlformat#1746]
**Describe the bug**
ocamlformat 0.19.0 fails with "Bug: ast changed" on a file with nested sequence (`;`) operators

**How to Reproduce**

Example file:

```ocaml
let () = (((((); ()); ()); ()); ())
```

This bug also occurs if you replace `()` expressions with some arbitrary expression.

```ocaml
let () =
  (
    (foo;foo);
    foo
  )
;;
```

This bug happens when there is more than a single level of `;`-sequencing.

Options:

```
--profile=janestreet
--enable-outside-detected-project
--disable-conf-files
--impl
```

**Comment by bcc32** [comment]
On the other hand, a snippet like this works fine:

```ocaml
let () =
  (
    (let x = x in foo;foo);
    foo
  )
;;
```

**Comment by gpetiot** [comment]
Hi, this has been recently fixed with #1731

**Comment by gpetiot** [comment]
I'm closing this issue, feel free to reopen if you notice some cases are not properly handled on the `master` branch

**Comment by bcc32** [comment]
Thanks!
