### ISSUE TITLE
Bug: quadratic behaviour with nested lists in argument position

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#1750]
The following example shows a quadratic behaviour in `ocamlformat`: if you add an extra `all [`, the running time roughly doubles.
```
let _ =
  all
    [
      f
       (all
        [
          all
            [
              all
                [
                  all
                    [
                      all
                        [
                          all
                            [
                             all
                               [
                                 all
                                   [
                                     all
                                       [
                                         all
                                           [
                                             all
                                               [
                                                 all
                                                   [
                                                     all
                                                       [
                                                         all
                                                          [
                                                            identify]]]]]]]]]]]]]])]
```

**Comment by gpetiot** [comment]
@emillon After profiling it looks like the slowdown comes from the infix operators `Fmt.( $ )`, tried removing the Staged abstraction and further flatten the list formatting but the performance is still as bad

**Comment by emillon** [comment]
I just had a look. Part of the issue in this particular case is that there's a code path that triggers layout on a subexpression (`Cmts.preserve` does this):

https://github.com/ocaml-ppx/ocamlformat/blob/68e3256b5551933d5b12a1215e61318b40a85d29/lib/Fmt_ast.ml#L1392-L1403

So the first layer checks if the expression is simple by triggering layout on the second layer, which... and after checking that, it still has layout again (for real now!) the second layer, etc.

By adding a cache on the function that computes if a given expression breaks, the runtime on this file becomes instantaneous (6s -> 40ms). I'm not sure that it's the best solution, but it works here!

**Comment by nojb** [comment]
> By adding a cache on the function that computes if a given expression breaks, the runtime on this file becomes instantaneous (6s -> 40ms). I'm not sure that it's the best solution, but it works here!

Do you have a branch with your patch? I would like to try it on some other files where `ocamlformat` feels a bit slow.

**Comment by emillon** [comment]
I just pushed that to https://github.com/emillon/ocamlformat/tree/breaks-cache.

I haven't tried to repro, but it looks like heavily nested patterns and nested arrays could suffer from the same issue since they're donig this sublayout too.

**Comment by emillon** [comment]
(note that the cache might not be correct in the presence of comments)

**Comment by nojb** [comment]
> I just pushed that to https://github.com/emillon/ocamlformat/tree/breaks-cache.
> 

Thanks. For info, on a file where `ocamlformat` feels slow (~ 0.59s to reformat a file which is already formatted), the patch brings it down to ~0.48s.
