### ISSUE TITLE
Bug: regression between 0.18.0 and 0.19.0

### ISSUE THREAD

**Issue by dinosaure** [ocaml-ppx/ocamlformat#1767]
Currently, `ocamlformat.0.19.0` tries to update my test on [`mrmime`](https://github.com/mirage/mrmime) and reformats contents (specially inside `{| ... |}`). A simple `dune build @fmt --auto` with `ocamlformat.0.19.0` invalids my test. So I'm stuck on `ocamlformat.0.18.0` (which does not try to reformat `{| ... |}`).

**Comment by nojb** [comment]
If you are referring to the problem of changing newlines, it is fixed in #1754

**Comment by dinosaure** [comment]
Hmmhmm, I will try `ocamlformat~master` soon so and give you a feedback.

**Comment by dinosaure** [comment]
Ok, I can confirm that with 8ef1c9f, I can safely reformat `mrmime`. Thanks!
