### ISSUE TITLE
ocamlformat plugin support?

### ISSUE THREAD

**Issue by bikallem** [ocaml-ppx/ocamlformat#1769]
Is there a way to hook in to the `ocamlformat` binary via external plugins? My use case is the following. I have written a sql ppx using the `{%sql| select * from user; |}` extension. I want to format the text inside the `{%sql| .. |}` extension when formatting my OCaml. It would be awesome if ocamlformat could provide a way to hook in to formatting when it encounters ppx like `%sql`. So the after mentioned sql could be formatted as such below,
```
{%sql|
     select 
          name
        ; age
        ; number
        ; address
     from
       user;
     |}
```
Perhaps a plugin system ?

**Comment by emillon** [comment]
Yes, I don't think that this is a great idea at this stage at this would ossify a lot of the formatting API.

**Comment by bikallem** [comment]
closing this for now.
