### ISSUE TITLE
Bug: `type nonrec` inside extension point fails to style

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1771]
**Describe the bug**
```ocaml
[%%foo: type nonrec t = t]
```
Styling the code above produces the error message below.
```
ocamlformat: Cannot process "file.mli".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: generating invalid ocaml syntax.
```

**How to Reproduce**
Style with release 0.19.0 using `--profile=janestreet`.

**Comment by gpetiot** [comment]
I can't reproduce this bug, it formats correctly on 0.19.0 with this profile for me.

**Comment by ceastlund** [comment]
Oh, my mistake. I was on an older version than I thought. Glad to hear it's fixed in newer ones.
