### ISSUE TITLE
Bug: .ocamlformat-ignore glob patterns do not work on Windows

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#1773]
```bash
$ ls -a
.  ..  .ocamlformat  .ocamlformat-ignore  a.ml
$ cat .ocamlformat
$ cat .ocamlformat-ignore
*.ml
$ cat a.ml
let _ =
1
$ ocamlformat a.ml
let _ = 1 # BUG: a.ml should be ignored!
```
Note that this is only about glob patterns, literal filenames work fine (they were fixed in #1752).

**Comment by nojb** [comment]
Root cause seems to step from `ocaml-re`, see https://github.com/ocaml/ocaml-re/pull/197

**Comment by gpetiot** [comment]
It looks like your fix is included in ocaml-re 1.10.0 https://github.com/ocaml/ocaml-re/releases/tag/1.10.0 if you confirm it's fixed we can add the `re >= 1.10.0` dependency to ocamlformat

**Comment by nojb** [comment]
> It looks like your fix is included in ocaml-re 1.10.0 https://github.com/ocaml/ocaml-re/releases/tag/1.10.0 if you confirm it's fixed we can add the `re >= 1.10.0` dependency to ocamlformat

Thanks for the ping. Actually the fix included in 1.10.0 was only partial. A fuller fix was merged after that one in https://github.com/ocaml/ocaml-re/pull/198 and will be included in the next release 1.10.1 (and will require a tiny patch to `ocamlformat`). I will open a PR here once 1.10.1 is out with the modification. Thanks!

cc @rgrinberg

**Comment by gpetiot** [comment]
ocamlformat now requires `ocaml-re.1.10.3` (#2133), are there still some Windows-specific things to fix or can we close this issue?

**Comment by nojb** [comment]
> ocamlformat now requires `ocaml-re.1.10.3` (#2133), are there still some Windows-specific things to fix or can we close this issue?

Hi. Sorry, this had dropped out of my radar. Yes, `ocamlformat` needed a tiny patch if I remember correctly. I will try to revisit this soon and submit a PR to `ocamlformat`.
