### ISSUE TITLE
AST of sequences is allowed to change

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#1787]
```ocaml
let _ = (A; B); C
```

The code above formats to the code below since https://github.com/ocaml-ppx/ocamlformat/pull/1731:

```ocaml
let _ = A ; B ; C
```

In the first case, the AST looks like:
```
  sequence (sequence (A, B), C)
```

and in the second case:
```
  sequence (A, sequence (B, C))
```

This change might be benign but it seems not to be made on purpose so I think it's worth talking about it.

**Comment by hhugo** [comment]
This was made on purpose, see the normalization logic https://github.com/ocaml-ppx/ocamlformat/blob/main/lib/Normalize.ml#L258

**Comment by gpetiot** [comment]
According to the discussion in #1815 I think we can close this issue

**Comment by Julow** [comment]
> This was made on purpose, see the normalization logic https://github.com/ocaml-ppx/ocamlformat/blob/main/lib/Normalize.ml#L258

This normalization code is new since https://github.com/ocaml-ppx/ocamlformat/pull/1731 and there weren't a lot of discussion at the time.

I disagree that OCamlformat should be allowed to change the AST, even if there's no semantic change (if we disregard PPXes and bugs in the compiler). This is a surprising behavior to me but it's also potential bugs added into the logic that prevent ocamlformat from adding bugs to programs.

**Comment by hhugo** [comment]
The normalization was present since commit one https://github.com/ocaml-ppx/ocamlformat/commit/beec55abfbd5a6b35827df39d08c869bd11274f#diff-f559b09d84ab952148d07ed98e08cb263222ad143bd5d39c6ba5c577e5bf85beR54

**Comment by hhugo** [comment]
It was removed by https://github.com/ocaml-ppx/ocamlformat/pull/1672

**Comment by Julow** [comment]
Thanks for the clarification.
