### ISSUE TITLE
Bug: parentheses not being eliminated

### ISSUE THREAD

**Issue by Kakadu** [ocaml-ppx/ocamlformat#1799]
Parenthesis are not being eliminated. OCamlformat 0.19. I expect that they should. Am I wrong?

```ocaml
let __ = (get_op op) e_lhs
```

```ocaml
➜  /tmp ocamlformat /tmp/xxx.ml --enable-outside-detected-project
let __ = (get_op op) e_lhs
```
Standart configuration, no `.ocamlformat` file.

**Comment by jberdine** [comment]
It is intended that parentheses in such cases are preserved. With the parens `(f a) b` is two single-argument function applications, while without `f a b` is a single two-argument function application. These are almost always treated equivalently, but not always. See e.g. https://github.com/ocaml/ocaml/issues/7832.

**Comment by jberdine** [comment]
That said, if you or anyone knows some criterion that ocamlformat could apply to the parsetree (before typing) to distinguish the cases where it matters vs not to the type-checker, it would be good to normalize away the parens in the latter case.
