### ISSUE TITLE
Feature request: align-record-decl

### ISSUE THREAD

**Issue by rbjorklin** [ocaml-ppx/ocamlformat#1821]
**Current `ocamlformat` output:**
```ocaml
type example = {
  field1 : int;
  another_field : float;
  yet_another_field : string;
}
```

**Suggested `ocamlformat` output with `align-record-decl=true` :**
```ocaml
type example = {
  field1            : int;
  another_field     : float;
  yet_another_field : string;
}
```

**Comment by gpetiot** [comment]
Hi, this is not the direction we are pushing ocamlformat towards, we recently deprecated the options `align-cases`, `align-constructors-decl` and `align-variants-decl`.

The justification is twofold:
- if we add or remove a line in an aligned block, the whole block will get reformatted and that's generating an excessive diff
- this feature makes the maintenance of ocamlformat more difficult and hinders some cleaning/simplification of the code

**Comment by rbjorklin** [comment]
Those are fair and valid arguments. Thanks for taking the time to respond and your efforts in moving ocamlformat forward!
