### ISSUE TITLE
RFC: make 'break-cases=nested' default and deprecate other values

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#1882]
Similar to #1874 in this PR I would like to start a discussion to choose a unique behavior for the current option `break-cases`, in an effort to pick a single value for each option (#1881).
Among all of `break-cases` current values, I think `nested` would be the best if we had to choose only one, as you can see the diff compared from `break-cases=fit`:
```diff
let ends_line t (l : Location.t) =
   match find_token_after t ~filter:(fun _ -> true) l.loc_end with
-  | None -> true
+  | None ->
+      true
   | Some (_, next) ->
       assert (Location.compare next l > 0);
       next.loc_start.pos_lnum > l.loc_end.pos_lnum
```
All cases are broken after the arrow, so short branches are aligned with the long ones (thout would still break with `fit` but not the short ones).

It would be nice to have some feedback about our main users:
@emillon would it be feasible to use `nested` on dune instead of `all`?
@ceastlund would it be feasible to use `nested` in the janestreet profile instead of `fit-or-vertical`?
@tmattio @CraigFe would it be feasible to use `nested` in mirage and irmin and platform projects?

Disclaimer: this option is one of the most difficult to maintain (along with `--if-then-else`, see #1874), since it has a lot of interactions with other options (docking, exp grouping, etc.), and the values of `break-cases` are so different one to another that they cannot be easily factorized.

**Comment by gpetiot** [comment]
Here is the direction we are taking for this option:

 - `fit`, `fit-or-vertical` and `nested| are preserved since they are used in the `default`, `ocamlformat` or `janestreet` profiles;
 - `toplevel` and `all` will be deprecated starting form the `ocamlformat.0.20.0` release, then removed in the following one. If you are using one of these please consider switching to a supported profile.

We don't exclude making improvements to the remaining values of this option of course.

**Comment by mjambon** [comment]
What should we use instead of `break-cases = all` since it's now deprecated? We would like no more than one case per line, or the closest solution to that.
