### ISSUE TITLE
Reorder labeled anonymous function arguments

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#19]
ocamlformat knows how to treat `fun` or `function` arguments specially if they are the last arg in an application. E.g.:
```
List.exists r1N ~f:(function
  | Rtag (_, _, _, t1N) -> List.exists t1N ~f
  | Rinherit t1 -> typ == t1 )
```
instead of:
```
List.exists
  ~f:(function
      | Rtag (_, _, _, t1N) -> List.exists t1N ~f
      | Rinherit t1 -> typ == t1)
  r1N
```

It would be helpful if the formatter detected cases such as the second above and reordered a single labeled anonymous function argument to the last position.

**Comment by trefis** [comment]
> It would be helpful if the formatter detected cases such as the second above and reordered a single labeled anonymous function argument to the last position.

I'm really not keen on the idea.

I'd like it better if there was an option to format things like:
```ocaml
List.exists (function
  | Rtag (_, _, _, t1N) -> List.exists t1N ~f
  | Rinherit t1 -> typ == t1
) r1N
```
which is (I believe) a fairly common style.

**Comment by gpetiot** [comment]
I'm not a fan of moving arguments as well, @Julow do we agree on closing this one?

**Comment by Julow** [comment]
I don't think we should change the AST, this is out of scope.
