### ISSUE TITLE
Cons-lists no longer reformatted to "traditional" list

### ISSUE THREAD

**Issue by cwong-ocaml** [ocaml-ppx/ocamlformat#1912]
**Is your feature request related to a problem? Please describe.**

At 2d6fc3f11, running `ocamlformat --profile=janestreet --enable-outside-detected-project` on the following input:

```ocaml
let x = 1 :: 2 :: 3 :: 4 :: []
```

makes no change.

**Describe the solution you'd like**

Previous versions of ocamlformat (at least, 6620833ca, but presumably earlier as well) would reformat this to

```ocaml
let x = [1; 2; 3; 4]
```

I think we'd definitely prefer this styling in general. This also occurs with lists that would be wrapped, e.g

```ocaml
let x = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" :: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" :: "ccccccccccccccccccccccccccc" :: []
```

becoming

```ocaml
let x =
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" 
  :: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
  :: "ccccccccccccccccccccccccccc"
  :: []
```

rather than

```ocaml
let x =
  [ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" 
  ; "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
  ; "ccccccccccccccccccccccccccc"
  ]
```

**Comment by gpetiot** [comment]
Regardless of whether or not this change was good, here is the explanation: originally the ocaml parser would produce lists using the `::` operator whether brackets are used or not, then ocamlformat would unfold these lists to rewrite them using brackets as long as there was no attributes attached to the list elements.

We made the choice to customize the ocaml parser to directly produce a bracketed-list (as a new construct) when it was read from the source, removing our analysis-and-rewriting code in ocamlformat. So now, bracketed lists are preserved and `::` lists are preserved, which offers the advantage of being the least surprising behavior for users imho.

**Comment by cwong-ocaml** [comment]
Can we get that turned off in the janestreet profile? Thanks.

**Comment by gpetiot** [comment]
Alright, before I work on this @ceastlund can you also confirm that is what you want for the janestreet profile?

**Comment by ceastlund** [comment]
Yes, thanks for checking. These days @bcc32 and @cwong-ocaml work with me on ocamlformat, you can take requests from them as official.

**Comment by gpetiot** [comment]
Thanks for confirming :)

**Comment by hhugo** [comment]
@gpetiot, I believe this should be solved similarly to the turning BeginEnd nodes into parens
