### ISSUE TITLE
Bug: Unknown option "margin-check"

### ISSUE THREAD

**Issue by vphantom** [ocaml-ppx/ocamlformat#1917]
**Describe the bug**

In v0.19, `ocamlformat --help` mentions `--margin-check` however I was surprised that it is not recognized in `.ocamlformat`. Is this the desired behavior? If so, maybe the man page should note that it's only for the command line.

**How to Reproduce**

Create an `.ocamlformat` file which includes the line:

```text
margin-check
```

…and run `ocamlformat` on any file.

**Comment by jberdine** [comment]
It should not be set in configuration files, it is a debugging aid. Note that "it is known" that the margin can be violated in a number of situations, so it would only be asking for failures to set it in a configuration file.

**Comment by vphantom** [comment]
I understand. Should we then make the man page explicit about it? It wasn't obvious to me that some of these options weren't appropriate for config files.
https://github.com/ocaml-ppx/ocamlformat/blob/54f41596355394cd0ce08435c21c3cc3d1f7eda3/lib/Conf.ml#L1248
