### ISSUE TITLE
Issue with formatting in module type 

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#194]
This work
```
module S = struct
  (* comment *)
  (** Doc comments *)
  let  x : t = 3
end
```
But this does not
```
module type S = sig
  (* comment *)
  (** Doc comments *)
  val x : t 
end
```
and formats into 
```
module type S = sig
  val x : t(* comment *)
  
  (** Doc comments *)
end
```
note that the doc comment is not attached anymore

**Comment by jberdine** [comment]
This is showing a weakness of the ability to convert from one placement style for docstrings to another. Running with `--doc-comments=before` works, but it should not be necessary.
