### ISSUE TITLE
Feature request: run ocamlformat on mld files

### ISSUE THREAD

**Issue by MisterDA** [ocaml-ppx/ocamlformat#1965]
I'm starting to write readmes and manuals for my opam packages written in mld, that odoc/odig pick up and render nicely. The documents typically contain embedded OCaml code in the form of snippets or examples:

```
{@ocaml[
let the = fun () -> begin
  (* ... *)
  end
]}
```

Could it be possible to have ocamlformat run on the embedded OCaml snippets? It would make them more readable for the end-reader of the documentation and for the author as well. Even better, ocamlformat could have full support of mld files since I believe is able to reformat documentation in OCaml source code, and do simple stuff such as break lines and reformat code snippets.

**Comment by gpetiot** [comment]
This should be handled with #1941, but in .mli files not .mld, don't hesitate to give some feedback for this PR.
.mld is a different usecase though, I've opened https://github.com/realworldocaml/mdx/pull/361 but this probably needs to live outside of mdx to not depend on ocamlformat.
