### ISSUE TITLE
ocamlformat-rpc: asynchronous IO

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-ppx/ocamlformat#1966]
The current API is married to synchronous IO and requires using stdlib's channels. It would be preferable if the library was functorized to allow for users to insert their own (usually monadic) IO.

**Comment by tvfmmfvt** [comment]
Hi. I'm new to ML and not adopting to fix but are there IO in core ocaml comparable to Haskell's writer to be aware of ? My understanding is that ghc has some overheavy lift optimizations and I'd like to be able to avoid. Thank you.
