### ISSUE TITLE
Bug: Build Failing

### ISSUE THREAD

**Issue by LoganLieou** [ocaml-ppx/ocamlformat#1972]
**Describe the bug**
I ran `opam install ocamlformat` I don't know what's going on but the build is failing, someone please help.

**How to Reproduce**
- run `opam install ocamlformat`
- os: mac os 12.0.1

<img width="1420" alt="Screen Shot 2022-01-06 at 3 14 35 PM" src="https://user-images.githubusercontent.com/91910704/148453218-d65c3b5e-80b3-4ff6-b8e9-a2dd3f75af0d.png">

**Comment by gpetiot** [comment]
Hi, it looks like the `odoc-parser.1.0.0` dependency is missing

**Comment by LoganLieou** [comment]
It seems that `odoc-parser.1.0.0` is already installed and I get the same output as above
after running `opam install ocamlformat

<img width="838" alt="Screen Shot 2022-01-06 at 3 29 30 PM" src="https://user-images.githubusercontent.com/91910704/148454841-29345661-602e-46e6-b63c-9949cf927085.png">
`

**Comment by LoganLieou** [comment]
after running the command `opam unpin odoc-parser` I get this error, it seems that odoc-parser isn't pinned

<img width="372" alt="Screen Shot 2022-01-07 at 3 32 15 PM" src="https://user-images.githubusercontent.com/91910704/148610159-4f933f73-fd32-4488-9a90-4e74ca4c9a90.png">

**Comment by gpetiot** [comment]
That's weird. How about `ocamlformat.0.20.0`, does it get installed without any issue?

The package has been tested on a few OS including macos when it was published on opam: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/c1772d2d1bb6a83220f4acb3434432d585a54820/variant/opam-2.1,distributions,macos-homebrew,ocamlformat.0.20.1

Maybe try uninstalling the package before reinstalling it (I guess you already tried), what about setting up a new opam switch to start fresh?
