### ISSUE TITLE
Bug: Ast changed

### ISSUE THREAD

**Issue by maurobringolf** [ocaml-ppx/ocamlformat#1987]
This is my first bug report here, the error message suggested I should report this case. Please let me know if you need additional information.

I got an error when trying to autoformat my code using `ocamlformat`. I looked at the file causing the error and manually reduced it to a small (though non-sense) code snippet that reproduces the error:

```ocaml
let g _ = ()

let f (x : unit) : unit =
  (((g ""); g ""); g "")
```

The error output is:

```raw
ocamlformat: Cannot process "file.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
```

Interestingly enough, with only two nested sequence operations the error disappears:

```ocaml
let g _ = ()

let f (x : unit) : unit =
  ((g ""); g "")
  
(* Becomes autoformatted *)
let g _ = ()

let f (x : unit) : unit =
  g "";
  g ""
```

I am not writing these extra parenthesis by hand but they are produced by a custom ppx I wrote, so I cannot simply remove them.

I am using `ocamlformat` version 0.19.0 with dune in OCaml 4.11.2. My config is:

```
assignment-operator = end-line
let-and = sparse
line-endings = lf
parens-tuple = always
type-decl = sparse
wrap-comments = true
```

**Comment by gpetiot** [comment]
This is fixed since `ocamlformat.0.20.0` (with #1731 I guess), but please let us know if you find similar bugs on the latest version.

**Comment by maurobringolf** [comment]
Thanks, `0.20.1` works. Sorry for the outdated report!
