### ISSUE TITLE
[Req] Flag to ignore errors

### ISSUE THREAD

**Issue by pakoito** [ocaml-ppx/ocamlformat#203]
I currently have a codebase that mixes classes and regular files that I'd like formatted in one go. At the moment, all the errors when `Fatal error: exception ("Internal Error: classes not implemented")` create an empty file that's not cleaned up and pollutes the repository.

I'd like to have an option `--ignore-errors` that skips files with errors, or just logs them to console.

**Comment by hcarty** [comment]
One option you could use for now is to add a `[@@@ocamlformat.disable]` annotation to the source files which don't format properly. This will cause ocamlformat to leave their code unmodified.

Have you tried the latest `master`branch of ocamlformat? There have been several class- and object-related fixes which may help as well.

**Comment by pakoito** [comment]
I have not. Is it possible to pin the latest master from opam? Or does it require to build from source?

I'm fairly new to the ecosystem :D

**Comment by hcarty** [comment]
`opam pin add ocamlformat --dev-repo` should do it. That will give you a build from the latest commit to `master`.

**Comment by pakoito** [comment]
Thanks! What's the command to pin it back to a release version?

**Comment by hcarty** [comment]
`opam pin remove ocamlformat`

**Comment by pakoito** [comment]
Perfect. Thanks again ^^

**Comment by pakoito** [comment]
Should I close this ticket, or is it a suggestion worth considering?

**Comment by pakoito** [comment]
Ping

**Comment by hhugo** [comment]
Keep it open. I'd love to have this as well. I might even have a patch for it already.

**Comment by hhugo** [comment]
I think we can close this one now that #243 is merged:
- process all files instead of stopping at the first error.
- accept a `--quiet` flag to quiet errors due to invalid source files.

**Comment by pakoito** [comment]
Thank you @hhugo! That's two coffees I owe you this week ^^
