### ISSUE TITLE
Flag to work with folders

### ISSUE THREAD

**Issue by pakoito** [ocaml-ppx/ocamlformat#204]
I currently use `find` and `ls` with `xargs` to feed `ocamlformat`. It'd be great if I could just say `-f /path/to/code --inplace` and let ocamlformat pick up all `ml` and `mli` files there.

**Comment by jberdine** [comment]
It's not built into ocamlformat, but in case it is helpful, in infer we use the following [Makefile](https://github.com/facebook/infer/blob/1efc44c27f326e1b9f60c2345b1d22a57d9512aa/Makefile#L148) rule:
```
fmt:
	parallel $(OCAMLFORMAT_EXE) -i ::: $$(git diff --name-only $$(git merge-base origin/master HEAD) | grep "\.mli\?$$")
```

**Comment by jberdine** [comment]
I think this is a valid request, so I wouldn't just close it. I'm unlikely to get to it myself, but it makes sense to use it to gather feedback about how many people would find it useful, record work-arounds, etc. Or maybe there is a better place to record such information, the wiki maybe?

I'm not sure where the boundary should be between what ocamlformat handles internally versus what is done by the code integrating it into individual workflows. I imagine that we could replicate the functionality of `find` to implement this feature on the very outside level of ocamlformat, but I'm not sure that we should. For example, do we scan for all the ml and mli files, and only those or also allow some configuration for other extensions, and then what about needing to exclude some directories (for performance if not correctness)? That is a slippery slope to replicating more of `find` than I'd like.

**Comment by jberdine** [comment]
I wonder if this is still relevant now that there is the dune integration. Thoughts?

**Comment by emillon** [comment]
Yes, I think we can close it for now. A standalone mode would be nice but at the moment `dune` does this: https://dune.readthedocs.io/en/stable/formatting.html
