### ISSUE TITLE
Feature request: OCamlFormat as a library

### ISSUE THREAD

**Issue by MisterDA** [ocaml-ppx/ocamlformat#2053]
I'm hacking on a code generator that produces OCaml. The produced OCaml is rather ugly, I'm wondering if I could call OCamlFormat as a library, give it the AST (a compiler-libs or a ppxlib ast) and have OCamlFormat prettify my code before outputting it to a file. It would be more practical in my opinion than calling OCamlFormat as a subprocess.

**Comment by gpetiot** [comment]
Since 0.21.0 it should be possible to use ocamlformat as a library (https://v3.ocaml.org/p/ocamlformat/0.21.0/doc/Ocamlformat/Translation_unit/index.html)

The RPC is also available (https://v3.ocaml.org/p/ocamlformat-rpc/0.21.0/doc/index.html) but maybe not as easy to use.

**Comment by MisterDA** [comment]
Thanks! I asked because `odig doc ocamlformat` doesn't show the module entrypoint.

**Comment by gpetiot** [comment]
Feel free to report any problem with the api in another issue. I will probably add a page in the manual to help with the api entry point.
