### ISSUE TITLE
Fatal error: formatting changed ast

### ISSUE THREAD

**Issue by edwintorok** [ocaml-ppx/ocamlformat#21]
I have tested ocamlformat on 5000+ OCaml files from https://github.com/xapi-project.

[These files](https://gist.github.com/edwintorok/79465424260b2172a28125f2a946b968/archive/master.zip) fail when running `ocamlformat -i --no-warn-error`:
 ```
Fatal error: exception ("Internal Error: formatting changed ast" ("output file" api_server.ml))
Raised at file "src/import0.ml" (inlined), line 234, characters 22-32
Called from file "src/exn.ml", line 70, characters 6-15
Called from file "list.ml", line 85, characters 12-15
Called from file "src/list0.ml", line 28, characters 40-75
```

**Comment by jberdine** [comment]
Excellent, thank you very much, this is very helpful! I'll look into what the underlying issues are.

**Comment by edwintorok** [comment]
Thanks, I quite like this safety feature of `ocamlformat`. Might be worth pointing out somewhere in the documentation that when it finishes successfully the ASTs have been checked to be identical.

**Comment by jberdine** [comment]
Thanks, good suggestion. Note that the check is not quite 'identical', see (the comments in) [Normalize](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Normalize.ml) for the few ways in which the ASTs are permitted to differ.

**Comment by avsm** [comment]
Another failure with the same issue is this file from ocaml-dockerfile: https://github.com/avsm/ocaml-dockerfile/blob/957ea1ab48335c8b95d65c274edb8b09cacd906f/src-opam/dockerfile_distro.ml

**Comment by jberdine** [comment]
Except for #32, these should be fixed now.
