### ISSUE TITLE
Bug: calling ocamlformat on one or multiple files does not yield the same result

### ISSUE THREAD

**Issue by vbmithr** [ocaml-ppx/ocamlformat#2127]
Calling ocamlformat on one or multiple files does not yield the same result, i.e. `find ocaml -regex ".*\.mli?$"|xargs ocamlformat -i` does not indent like `for i in $(find ocaml -regex ".*\.mli?$"); do ocamlformat -i $i; done`. More info on request ;)

**Comment by Julow** [comment]
This works fine in my testing. Is here any error output ? In case of error, it is possible that the for-loop stops but xargs doesn't. The for-loop might also be problematic if a path contain a space.

Do you have more complicated commands in practice ?

**Comment by gpetiot** [comment]
Same, no issue for me. Can you provide a minimal input where the formatting is different? If that is indeed a for/xargs issue, there is not much we can do.

**Comment by vbmithr** [comment]
Ok, will try to provide a minimal example. Thanks for looking into this.

**Comment by vbmithr** [comment]
I managed to trace in my codebase when it was happening: the exact scenario is when you launch `ocamlformat -i project1/**/*.ml{,i} project2/**/*.ml{,i}` in a directory that contains project1 with `profile = janestreet` and project2 with `profile = ocamlformat`. The ordering is important, if I switch the order of directories in the command, the problem does not appear. It looks like the janestreet style is "leaking" in the following directory.

**Comment by gpetiot** [comment]
I tried with some content: (should reflect changes of the profiles)
```
let _ =
  ( xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  , yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy )
```
and having project1/x.ml the janestreet profile, project2/ using the ocamlformat profile, I get the same results with either:
- `find . -regex ".*\.mli?$"|xargs ocamlformat -i`
- `for i in $(find . -regex ".*\.mli?$"); do ocamlformat -i $i; done`
- `ocamlformat project1/x.ml project2/x.ml -i`
- `ocamlformat project2/x.ml project1/x.ml -i`

Are you sure no other configuration is interfering? Try the `--print-config` option, it should tell if the configuration is modified by something else. But I'm running out of ideas.

**Comment by vbmithr** [comment]
Ok, I will try to produce an example then.

**Comment by hhugo** [comment]
@vbmithr, It would help if you could provide examples of formatting differences. 

@gpetiot, There exists toplevel state that need to be reset between each file (e.g. `Ast.init` does some of it). A quick grep in the codebase show that we have `max_indent` in `Fmt.ml`, and `set_max_indent` is not always called in `Translation_unit`.

**Comment by hhugo** [comment]
I'm not able to reproduce. note that `make project1` already changes the code for me.
What version of ocamlformat do you use ?

**Comment by vbmithr** [comment]
0.24.1

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/pull/2099 made the Janestreet profile set max_indent. @gpetiot my comment above very likely explain the bug.

**Comment by gpetiot** [comment]
I still can't reproduce the issue even with your archive and the same release ocamlformat 0.24.1, but based on what Hugo suggested @vbmithr can you try this branch: #2131?

**Comment by hhugo** [comment]
The instruction provided by @vbmithr is slightly wrong. You need to call `make all` instead of `make`

**Comment by vbmithr** [comment]
The patch indeed fixes the issue. Thanks :)
