### ISSUE TITLE
Bug: cannot install ocamlformat v0.24.1 in a project that uses also odoc

### ISSUE THREAD

**Issue by mooreryan** [ocaml-ppx/ocamlformat#2134]
**Describe the bug**

I would like to update to the latest ocamlformat, in some of my projects.  However, those projects also use odoc for building docs.  But they are not compatible due to the dependency on odoc-parser.

(I don't know if this really is a bug or not, or even something that can be fixed...if it isn't sorry for the noise!)

**How to Reproduce**

Set up a clean switch and try to install the packages.

```
$ opam switch create a_test ocaml-base-compiler.4.14.0
$ eval $(opam env --switch=a_test)
$ opam update
$ opam install ocamlformat.0.24.1 odoc

[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler = 4.14.0 → ocaml = 4.14.0
    - odoc → ocaml < 4.08.0
    You can temporarily relax the switch invariant with `--update-invariant'
  * No agreement on the version of odoc-parser:
    - ocamlformat >= 0.24.1 → odoc-parser >= 2.0.0
    - odoc → odoc-parser < 2.0.0

No solution found, exiting
```

ocamlformat requires odoc-parser >= 2, whereas odoc requires odoc-parser < 2.

**Comment by gpetiot** [comment]
Hi,

ocamlformat 0.24.1 requires odoc-parser 2.0.0 indeed. If you use odoc-parser 1.0.0 (as odoc itself has not be made compatible with 2.0.0 yet but I'm working on it) you should use ocamlformat 0.23.0.

The only difference between 0.23.0 and 0.24.1 is the version of odoc-parser they support, no new feature, and no bug fixed.

**Comment by mooreryan** [comment]
Thanks, in that case, I will use 0.23 for now.
