### ISSUE TITLE
Feature request: Emacs mode's indent setup should be guarded by a user option

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ocamlformat#2158]
`ocamlformat.el` overrides `indent-line-function` and what the “Return” key does (when ocamlformat's version is above 0.19.0), this is way too aggressive (especially for a feature that seems so brittle/broken?).

There should be a user configuration (`defcustom`) to enable this.

----

In the meantime, what ocamlformat.el does can be undone by adding another hook and enforce that it runs after ocamlformat's one (i.e. `DEPTH` = 99):

```elisp
(defun undo-ocamlformat-indentation-mess ()
  (interactive)
  (setq indent-line-function 'indent-relative)
  (local-set-key (kbd "RET") 'newline))

(add-hook 'tuareg-mode-hook 'undo-ocamlformat-indentation-mess 99)
```

**Comment by gpetiot** [comment]
Thank you for the report. This feature has been removed in https://github.com/ocaml-ppx/ocamlformat/pull/2333, so I'm closing this issue, but feel free to re-open if the problem persists.
