### ISSUE TITLE
Feature request: better formatting for function arguments

### ISSUE THREAD

**Issue by mimoo** [ocaml-ppx/ocamlformat#2192]
I'm looking at some code in the repository I'm working on that looks like this:

```ocaml
Impls.Step.generate_witness_conv
            ~f:(fun { Impls.Step.Proof_inputs.auxiliary_inputs; public_inputs }
                    next_statement_hashed ->
              let%map.Promise proof =
                Backend.Tick.Proof.create_async ~primary:public_inputs
                  ~auxiliary:auxiliary_inputs
                  ~message:(Lazy.force prev_challenge_polynomial_commitments)
                  pk
              in
              (proof, next_statement_hashed) )
            ~input_typ:Impls.Step.Typ.unit ~return_typ:input
            (fun () () ->
              Impls.Step.handle
                (fun () -> conv_inv (branch_data.main ~step_domains ()))
                handler ) 
```

IMO this is not readable, for several reasons, but here what's relevant is the formatting. 
The main problem is that it is not clear what are the arguments to functions (`generate_witness_conv` and `create_async`).
I am not sure what a good way to solve this would be, but here's one way to make the arguments stand out:

```ocaml
Impls.Step.generate_witness_conv
    ~f:(fun 
            { Impls.Step.Proof_inputs.auxiliary_inputs; public_inputs }
            next_statement_hashed 
        ->
        let%map.Promise proof = Backend.Tick.Proof.create_async
            ~primary:public_inputs
            ~auxiliary:auxiliary_inputs
            ~message:(Lazy.force prev_challenge_polynomial_commitments)
            pk
        in
        (proof, next_statement_hashed))
    ~input_typ:Impls.Step.Typ.unit 
    ~return_typ:input
    (fun () () ->
        Impls.Step.handle
        (fun () -> conv_inv (branch_data.main ~step_domains ()))
        handler) 
```

What I did: 

* when a function has arguments that can't stand on the same line as the function name, then each argument should be started on a new line (especially the first one)
* when a function has a body that can't stand on the same line as the function signature, it should be started on a new line

**Comment by gpetiot** [comment]
We obtain something very close by setting `wrap-fun-args = false`:

```ocaml
let _ =                                
  Impls.Step.generate_witness_conv
    ~f:
      (fun { Impls.Step.Proof_inputs.auxiliary_inputs; public_inputs }
           next_statement_hashed ->
      let%map.Promise proof =
        Backend.Tick.Proof.create_async
          ~primary:public_inputs
          ~auxiliary:auxiliary_inputs
          ~message:(Lazy.force prev_challenge_polynomial_commitments)
          pk
      in
      (proof, next_statement_hashed))
    ~input_typ:Impls.Step.Typ.unit
    ~return_typ:input
    (fun () () ->
      Impls.Step.handle
        (fun () -> conv_inv (branch_data.main ~step_domains ()))
        handler)
```

**Comment by gpetiot** [comment]
I'm closing this issue, but feel free to reopen if my answer is not satisfying.

**Comment by mimoo** [comment]
I can't reopen myself, but I'm against customizing formatting options in projects and I think there's a good argument that this should be the default behavior : o

**Comment by gpetiot** [comment]
That's the direction we are taking, the default profile will become more diff-friendly and more "vertical", while the current setting of the default profile might be renamed `mirage` (as the settings are decided by the mirage team anyway).

**Comment by mimoo** [comment]
awesome to hear! looking forward :)

**Comment by mooreryan** [comment]
> the default profile will become more diff-friendly and more "vertical",

Does that mean the `ocamlformat` profile will become the new default?

**Comment by gpetiot** [comment]
No, a new profile will be created and will become the new default.
