### ISSUE TITLE
Feature request: why require an .ocamlformat at the root?

### ISSUE THREAD

**Issue by mimoo** [ocaml-ppx/ocamlformat#2197]
Hello!

I was wondering why formatting doesn't work until an `.ocamlformat` is placed at the root. This seems counter intuitive :o at least I don't know any other language formatter that does that

**Comment by gpetiot** [comment]
We plan to make ocamlformat usable without having an `.ocamlformat` file in the project, but only when ocamlformat is more "stable", that means when:
- the default profile is switched to something more diff-friendly (#2020)
- ocamlformat.1.0 is released

I cannot make any guess at when it will be though, a lot of work is still necessary to get to the new profile.

**Comment by hhugo** [comment]
Having ocamlformat work when no `.ocamlformat` is present would be very annoying when working on codebases not using ocamlformat (such as the OCaml compiler codebase). I'm not sure how other languages deal with this.

**Comment by gpetiot** [comment]
Nothing definitive but I guess it would be fitting to use dune's formatting stanza (https://dune.readthedocs.io/en/latest/dune-files.html#formatting).

**Comment by gpetiot** [comment]
Since your question has been answered I'm closing this issue.

#2092 will track the progress on this feature.

**Comment by mimoo** [comment]
>  I'm not sure how other languages deal with this.

I would say most languages' community use the default formatter so it's not an issue (and usually bad practice anyway to not use a formatter)
