### ISSUE TITLE
Bug: multiple kinds of formatting apparently broken at tip of main

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#2208]
If I format `(<) x y` or `{x=x}`, I used to get back `x < y` and `{x}`, whitespace notwithstanding. Now ocamlformat leaves the original forms as-is. This is true at tip of `main` but was not true at `0.24.1`. I'm not sure when the regression got introduced.

**Comment by gpetiot** [comment]
This should be fixed by #2210 so I'm closing this issue, but feel free to reopen @ceastlund if we missed some cases.
