### ISSUE TITLE
Q: is there a `Ocamlformat.format_string : string -> string` function ?

### ISSUE THREAD

**Issue by JoanThibault** [ocaml-ppx/ocamlformat#2224]
Hi,

I went through the documentation, and did not find something like this.
That is a function which simply takes a input a string representing some ocaml term and return it in a well formatted way.
I am guessing it exists, I just could not find it.

Best,

Joan

**Comment by gpetiot** [comment]
Hi, there is not something as simple as that, as you need to specify how to parse the string and provide a conf, but there is: `Translation_unit.parse_and_format` ([doc](https://ocaml.org/p/ocamlformat/0.24.1/doc/Ocamlformat/Translation_unit/index.html)).

We may have a ocamlformat-lib package in the near future though, we can polish the API when it happens.

**Comment by gpetiot** [comment]
Closing this issue for now, feel free to reopen if I didn't fully answer your question.

**Comment by JoanThibault** [comment]
Thank you I will look into it :smile:
