### ISSUE TITLE
Bug: Formats dune in a breaking way with pps flags

### ISSUE THREAD

**Issue by davesnx** [ocaml-ppx/ocamlformat#2256]
Hi, and sorry for opening two issues in one day!

ocamlformat formats dune in a breaking way with pps, it breaks into new lines dune and then dune understands each line as one preprocesser, rather than args.

**Describe the bug**

```
(* dune *)

(library
 (name content_explorer)
 (libraries
  bs_css
  bs_css_emotion
  reason_react
  webapi)
 (preprocess
  (pps
   bs-react-intl-ppx.lib
   bs-emotion-ppx.lib
   styled-ppx.lib -- --compat-with-bs-emotion-ppx true)))
```

Gets transformed into 

```
(* dune *)

(library
 (name content_explorer)
 (libraries
  bs_css
  bs_css_emotion
  reason_react
  webapi)
(preprocess
  (pps
   bs-react-intl-ppx.lib
   bs-emotion-ppx.lib
   styled-ppx.lib
   --
   --compat-with-bs-emotion-ppx
   true
)))
```

**Comment by gpetiot** [comment]
When running `dune fmt`, `ocamlformat` only formats .ml(i) files, the formatting of dune files is done by `dune` itself (see: https://github.com/ocaml/dune/blob/main/src/dune_lang/format.ml)

**Comment by davesnx** [comment]
I had no idea, closing this and passing it to dune. Thanks.
