### ISSUE TITLE
opam install ocamlformat wants to downgrade ocaml-version

### ISSUE THREAD

**Issue by Fourchaux** [ocaml-ppx/ocamlformat#2262]
The latest version of ocaml-version is 3.6.0.

Would it be possible to upgrade ocamlformat so that it recognizes this version?

**Comment by Fourchaux** [comment]
It's OK now.
Issue can be closed.
TY

**Comment by gpetiot** [comment]
Sorry for the late reply, we just released ocamlformat 0.25.1 which is fixing this issue. We don't have a habit of patching up older releases of ocamlformat though. This might still happen but we prefer encouraging people to upgrade :)

I'm closing this issue.
