### ISSUE TITLE
Bug: Functions sometimes indented very far when passed as named argument

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#2265]
**Describe the bug**
This input:
```
let () = very_long_function_name ~very_long_argument_label:(fun very_long_argument_name_one very_long_argument_name_two very_long_argument_name_three -> ())
```

Gives this output:
```
let () =
  very_long_function_name
    ~very_long_argument_label:(fun
                                very_long_argument_name_one
                                very_long_argument_name_two
                                very_long_argument_name_three
                              -> ())
;;
```

Either the `(fun` should be split to a new line, or the arguments and function body should be indented somewhere closer to the start of `~very_long_argument_label`, rather than all the way to the right like they are.

This was run with `--profile=janestreet`.

**Comment by gpetiot** [comment]
As a side note, this is not specific to the `janestreet` profile.
