### ISSUE TITLE
Bug: empty functor argument no longer shortened

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#2276]
`module M = F (struct end)`
used to be shortened to:
`module M = F ()`

Now both of them are left untouched. Unless there's a difference in meaning between the two, I'd rather they were both normalized to the same thing. For now, in the `janestreet` profile at least I'd like it to stay as `()` since we're in the middle of changing a lot of other things. Eventually we may prefer `struct end` as a separate change.

**Comment by hhugo** [comment]
They will have a different meaning in the next version I think, see https://github.com/ocaml/ocaml/pull/11984

**Comment by ceastlund** [comment]
Okay, gotcha, thanks. Then the current behavior sounds right.
