### ISSUE TITLE
Bug: Double parenthesis around tupple

### ISSUE THREAD

**Issue by lyrm** [ocaml-ppx/ocamlformat#2278]
**Describe the bug**
Add extra parentheses around a tupple resulting in something like `( (tuple))`

**How to Reproduce**
Ocamlformat version : I tried `0.23.0` and `0.25.1`.
Option : none  (default)

Here is an example where it happens: 
```ocaml
type 'a bar = A of 'a * 'a option

let foo a =
  match a with A (n, m) -> ( (n, match m with None -> None | Some b -> b))
````

**Comment by Julow** [comment]
Thanks for the report, fixed in https://github.com/ocaml-ppx/ocamlformat/pull/2308
