### ISSUE TITLE
Feature request: improve the behavior of `--no-comment-check`

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#2408]
Ideally, `--no-comment-check` should not complain if an unattached doc comment (warning 50) becomes attached.
The current behavior is that we see an "Ast changed" error because there is an extra "doc" atttribute corresponding to that comment.

**Comment by Julow** [comment]
The current error is correct in that the AST changes. Though, that might be acceptable behind a flag.

Do you have an example of an unattached doc comment that becomes attached ?

**Comment by hhugo** [comment]
The purpose of the request is to help classify bugs found in opam, I've added a bunch of problematic files in https://github.com/ocaml-ppx/ocamlformat/issues/985

**Comment by Julow** [comment]
Thanks! I did not expect this bug to be possible but here's one example from your list:

```ocaml
open Vg
;;

(** Images for the documentation. *)
```

becomes:

```ocaml
open Vg

(** Images for the documentation. *);;
```

**Comment by hhugo** [comment]
Looking more into this, it seems that
`Normalize_std_ast.equal ~ignore_doc_comments:true` doesn't ignore floating doc comment inside Pctf_attribute, Psig_attribute, Pstr_attribute and Pcf_attribute
