### ISSUE TITLE
Bug: functor formatting did not stabilize after 10 iterations.

### ISSUE THREAD

**Issue by dbremner** [ocaml-ppx/ocamlformat#2415]
**Describe the bug**
I received the following error message when trying to format the attached file from a fork of an old project [peterburg](https://github.com/dbremner/peterburg). I used the command "ocamlformat --inplace testcase.mli" and am using version 0.26.0.
> ocamlformat: Cannot process "peterburg.mli".
> Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
> BUG: formatting did not stabilize after 10 iterations.

**How to Reproduce**
- What is the formatted file? Please try to minimize the code snippet.
Here is a minimized excerpt that triggers the error message. It's also attached as "testcase.mli.txt". I'm new to OCaml and may have done so incorrectly, so I have also attached the original file as "peterburg.mli.txt". 
```
module Grammar :
  functor (Nonterm : Nonterminal) ->   (* Set of nonterminals                                          *)
  functor (Attr    : Attribute  ) ->
  sig
  end
```
 
- What are the selected options?
AFAIK I'm using the default settings. I have attached copies of my .ocamlformat ("ocamlformat.txt") and the output from --print-config ("printconfig.txt") just in case.
[testcase.mli.txt](https://github.com/ocaml-ppx/ocamlformat/files/12337992/testcase.mli.txt)  
[printconfig.txt](https://github.com/ocaml-ppx/ocamlformat/files/12338006/printconfig.txt)  
[ocamlformat.txt](https://github.com/ocaml-ppx/ocamlformat/files/12338014/ocamlformat.txt)  
[peterburg.mli.txt](https://github.com/ocaml-ppx/ocamlformat/files/12338404/peterburg.mli.txt)  
  
I'm not sure how this excerpt should be formatted, but I didn't expect a crash.

Thanks for considering this bug report. Please let me know if there's anything else I can provide.

**Comment by Julow** [comment]
Thanks for the detailed report :) Should be fixed in https://github.com/ocaml-ppx/ocamlformat/pull/2420

**Comment by dbremner** [comment]
Thank you!
