### ISSUE TITLE
Bug: AST changed on nested with constraints

### ISSUE THREAD

**Issue by rleshchinskiy** [ocaml-ppx/ocamlformat#2416]
**Describe the bug**
Running ocamlformat on
```
module N : S with module type T = (U with module M = M) = struct end
```
results in
```
ocamlformat: Cannot process "/tmp/x/U.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
```

**How to Reproduce**
Paste above into a `/tmp/x/U.ml`, run `ocamlformat --enable-outside-detected-project /tmp/x/U.ml`

**Comment by Julow** [comment]
Thanks for the report, should be fixed by https://github.com/ocaml-ppx/ocamlformat/pull/2419
