### ISSUE TITLE
BUG: ast changed.

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#2435]
```
 let _ =
    match x with
    | [ _ ] ->
        foo
    | _ ->
        begin[@landmark "amc_calib"]
          bar
        end
```

**Comment by hhugo** [comment]
Duplicate https://github.com/ocaml-ppx/ocamlformat/issues/2405, probably fixed on master

**Comment by nojb** [comment]
> Duplicate #2405

Thanks for the reference, but this seems to be a different issue (still broken on `master` as far as I can see).

**Comment by gpetiot** [comment]
On the `main` branch, with default options I get:
```ocaml
let _ =                                
  match x with
  | [ _ ] -> foo
  | _ ->
      begin
        bar
      end
      [@landmark "amc_calib"]
```

**Comment by nojb** [comment]
> On the `main` branch, with default options I get:

Strange. I cloned and built `main` and indeed it passes. However if I do `opam pin --dev ocamlformat` then the resulting binary gives the error reported above. The versions seem to be the same. Not sure what is going on...

**Comment by Julow** [comment]
The formatting code is in the package `ocamlformat-lib` and the pin command do not seem to update it. Perhaps the opam files could be improved to fix that ?

**Comment by nojb** [comment]
> The formatting code is in the package `ocamlformat-lib` and the pin command do not seem to update it. Perhaps the opam files could be improved to fix that ?

I had missed that there were two packages involved. Thanks!

**Comment by nojb** [comment]
> The formatting code is in the package `ocamlformat-lib` and the pin command do not seem to update it. Perhaps the opam files could be improved to fix that ?

From a quick look at the docs, it looks like adding `ocamlformat-lib` (and `ocamlformat-rpc-lib`) to `pin-depends:` section of the OPAM file should do it.

**Comment by nojb** [comment]
The following one still seems to fail, even on `master`:
```
let _ =
  if something_changed then begin[@landmark "linearize"]
    loop
  end
```

**Comment by Julow** [comment]
Fixed by @gpetiot in https://github.com/ocaml-ppx/ocamlformat/pull/2436.

**Comment by nojb** [comment]
Thanks!
