### ISSUE TITLE
Bug: Installed version mismatch error

### ISSUE THREAD

**Issue by yawaramin** [ocaml-ppx/ocamlformat#2447]
Getting an error:

```
ocamlformat: Error while parsing /Users/yawarquadiramin/src/github.com/yawaramin/alcotest/.ocamlformat: Project should be formatted using ocamlformat version "0.25.1", but the installed version is "0.26.0"
```

Output of `opam list`:

```
ocamlformat                 0.26.0      Auto-formatter for OCaml code
```

Expected behaviour: ocamlformat should format the project according to its required version and configuration, without error messages.

**Comment by Julow** [comment]
Every versions of OCamlformat are breaking changes. To avoid different contributors formatting back and forth some pieces of code, projects must specify an exact version of ocamlformat to work with.

The error message is a bit ambiguous but what it says is: You have 0.26.0 but the project requires exactly 0.25.1.

**Comment by yawaramin** [comment]
Thanks. Shouldn't ocamlformat 0.26.0 know how to format with the proper settings for 0.25.1? For example, if I use dune 3 in a `(lang dune 2)` project, it works successfully.

**Comment by Julow** [comment]
Subtle changes to the code can cause subtle change in formatting which are enough to cause back and forth reformatting.

We have no idea how to achieve versioning but we would like to have that at some point.

**Comment by gpetiot** [comment]
This is on our roadmap for ocamlformat 1.0, but as for now this is the expected behavior, not a bug.
