### ISSUE TITLE
Question: is there an option to keep `match` in the same line of a function declaration?

### ISSUE THREAD

**Issue by valmirjunior0088** [ocaml-ppx/ocamlformat#2497]
Hi!

I have begun learning OCaml recently and `ocamlformat` is a joy to use! So far I have only one gripe with the tool, which is the way it formats `match` expressions. I've read the output of `ocamlformat --help` and I haven't found anything related, perhaps because I've missed something.

Suppose the following snippet:

```
let foo one other = match one with
  | Foo -> ...
  | Bar -> ...
```

`ocamlformat` with the default settings will format this as:

```
let foo one other =
  match one with
  | Foo -> ...
  | Bar -> ...
```

Is there any option which makes my code keep the formatting of the first snippet?

**Comment by Julow** [comment]
Hi,

Thanks for asking. This is not possible at the moment.

This is the kind of formatting that is hard to maintain and tends to interact badly with other similar cases.
For maintenance time reasons, I'm not in favor of adding such option.
