### ISSUE TITLE
Bug: Formatter is not stabilizing for a small snippet

### ISSUE THREAD

**Issue by tomaz1502** [ocaml-ppx/ocamlformat#2527]
**Describe the bug**
`ocamlformat` does not stabilize for the following snippet:
```ocaml
(* Does not work *)
ParsingStructureUtilities.exists_in_parsed_function_definition
    is_seq_code_bloc_leaf_has_side_effects (* Check if leaf of sequential code bloc has side effect *)
    is_leaf_has_side_effects (* Check if leaf has side effect *)
    fun_def
```
However, we can make the formatter work by removing part of the commentaries:
```ocaml
(* Works *)
  ParsingStructureUtilities.exists_in_parsed_function_definition
    is_seq_code_bloc_leaf_has_side_effects (* Check  *)
    is_leaf_has_side_effects (* Check  *)
    fun_def
```

**How to Reproduce**
- Start a project with `dune init proj foo`
- Place the problematic snippet in a file `lib/bug.ml`
- Add the following configuration to the file `.ocamlformat`:
```
profile = default
version = 0.26.1
```
- Run the command `ocamlformat --check lib/bug.ml`

## Related Issue
#2457

**Comment by Julow** [comment]
Thanks for the well written issue! I can reproduce the bug with 0.26.1 and it seems fixed on the main branch, could you confirm ?

**Comment by tomaz1502** [comment]
Yes, I confirm!

**Comment by Julow** [comment]
Thanks!
