### ISSUE TITLE
BUG: bad formatting, trailing whitespace

### ISSUE THREAD

**Issue by nojb** [ocaml-ppx/ocamlformat#2538]
```
let _ =
  match c with
  | {issuer = _; (* TODO *)
     _
    } -> ()
```
yields
```
let _ =
  match c with
  | {
   issuer = _;

   (* TODO *)
 _;
  } ->
      ()
```
where there is trailing whitespace in the empty line before the `(* TODO *)`. The behaviour can be reproduced with an empty `.ocamlformat`. Tested on the branch of #2537.

**Comment by Julow** [comment]
Thanks for reporting, should be fixed by https://github.com/ocaml-ppx/ocamlformat/pull/2540

**Comment by Julow** [comment]
The fix is merged.
