### ISSUE TITLE
Bug: `BUG: comment changed`

### ISSUE THREAD

**Issue by Hirrolot** [ocaml-ppx/ocamlformat#2547]
To reproduce, try to format the following file:

```
(* Invariants:
   - x
 *)
```

with the following `.ocamlformat`:

```
version = 0.26.2
profile = janestreet
wrap-comments = true
```

My `ocamlformat` version is `0.26.2`.

**Comment by Julow** [comment]
Thanks for reporting, this has been fixed in #2371, which is not released yet.
