### ISSUE TITLE
Bug: `--parse-docstrings` violates margin

### ISSUE THREAD

**Issue by mmottl** [ocaml-ppx/ocamlformat#2549]
**Describe the bug**

Passing `--parse-docstrings` may lead to output that violates the configured margin.

```sh
❯ ocamlformat --version
0.26.2
```

**How to Reproduce**

Formatted file `foo.ml`:
```ocaml
(** xxxxx xx xxxxxx xxxxxx xxxxxx xxxxx xxxxxxx xxx xxxxxx xxx xxxx
    xxxxxxxxxx. *)
```

Command line (explicitly sets a margin of 80):
```sh
ocamlformat --enable-outside-detected-project -m 80 --parse-docstrings foo.ml
```

Output has an 82 character line:
```ocaml
(** xxxxx xx xxxxxx xxxxxx xxxxxx xxxxx xxxxxxx xxx xxxxxx xxx xxxx xxxxxxxxxx. *)
```

**Comment by Julow** [comment]
Thanks for reporting. Should be fixed by https://github.com/ocaml-ppx/ocamlformat/pull/2550
