### ISSUE TITLE
Feature request: Experimental effect syntax support?

### ISSUE THREAD

**Issue by Zeta611** [ocaml-ppx/ocamlformat#2559]
I'm currently using 5.1.1+effect-syntax variant, and ocamlformat (obviously) fails to work.

**Describe the solution you'd like**
I have actually implemented a rudimentary support for the syntax [here](https://github.com/Zeta611/ocamlformat/tree/effect-syntax) for personal use.

But I'm not sure whether or not or how I should contribute, as this is an experimental syntax support.

**Additional context**
It works:
<img width="958" alt="Screenshot 2024-06-22 at 18 14 27" src="https://github.com/ocaml-ppx/ocamlformat/assets/9553691/3581aadb-edb2-4f2e-a5d7-2e778df8ba18">

**Comment by Julow** [comment]
This is awesome ! I think you can definitely open a PR as the effect syntax is to be released in OCaml 5.3 (I think?)

**Comment by Zeta611** [comment]
Great, I've opened it in #2562!

**Comment by Zeta611** [comment]
#2562 got merged, so closing the issue 🚀
