### ISSUE TITLE
Bug: name/public_name of vendored libs are out of sync

### ISSUE THREAD

**Issue by v-gb** [ocaml-ppx/ocamlformat#2581]
I'm not sure if this is intended, but vendor/ocamlformat_support/dune (among others) contains:

```dune
(library
  (name ocamlformat_format)
  (public_name ocamlformat-lib.format_ocamlformat_format)
  ...
```

which means the entry point module is called `Ocamlformat_format` from inside ocamlformat, but `Format_` for everywhere else.

It seems that `opam install` or `dune pkg` make the public name available, but when I use `opam pin`, I get the private name. So this causes confusing build errors when you switch from one to the other. The same name being used internally and publicly would be net simpler, which is how it worked until https://github.com/ocaml-ppx/ocamlformat/pull/2481 updated only the internal name. This seems like an oversight? i.e. the public name should be made equal to the internal name.

**Comment by Julow** [comment]
When I do `dune build -p ocamlformat-lib`, I see a `ocamlformat_format.cmxa` that contains modules `Ocamlformat_format` and `Ocamlformat_format__Format_`.
What are the steps to observe the shorter name ?

**Comment by v-gb** [comment]
Just `opam install`:

```
$ ls -1 ~/.opam/5.2.0/lib/ocamlformat-lib/format_/*.cmi
~/.opam/5.2.0/lib/ocamlformat-lib/format_/format_.cmi
~/.opam/5.2.0/lib/ocamlformat-lib/format_/format___.cmi
~/.opam/5.2.0/lib/ocamlformat-lib/format_/format___Format.cmi
```

**Comment by v-gb** [comment]
Or I might be confused, if the ocamlformat version (0.26.2) I'm getting from opam predates #2481, despite that PR being almost a year old. Let me and see.

**Comment by v-gb** [comment]
Ok, that was correct: ocamlformat version 0.26.2, which is the latest version, doesn't contain #2481. So building from opam, I get `Format_`, whereas when I use `opam pin`, I use a much more recent revision, so I get `Ocamlformat_format`.

Sorry for the noise.
