### ISSUE TITLE
Style option: don't start lines with punctuation

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-ppx/ocamlformat#264]
It [seems](https://github.com/hhugo/ocaml/commit/9f10047b820103d277392d60b58e30cdcb73a5c9#diff-bfbed4ab457cd252e41f57d62147b4e3R18) that `ocamlformat` currently formats long pairs/lists by breaking before seperators which is somehow at odds with typographic conventions. It would be nice to have an option that breaks after separators (`,`, `;`, `->`, etc.)

**Comment by jberdine** [comment]
Yes, there are a few common styles, and ocamlformat is pretty opinionated in this case. This is in line with the second point from the README:

- Whenever possible, the high-level structure of the code should be obvious by looking only at the left margin, in particular, it should not be necessary to visually jump from left to right hunting for critical keywords/tokens/etc.

But an option would be welcome.

**Comment by dbuenzli** [comment]
I don't find the justification particularly compelling. If I'm reading say a multiline tuple definition newlines and indentation indicate the structure, I don't have to hunt to the right looking for the comma to be sure I'm getting it right.

**Comment by jberdine** [comment]
I can see how the argument isn't compelling. As with most questions about syntax, there are very few arguments that are strong compared to individual experiences and preferences. Which things have burned you, and which you've seen burn others, really matters.

**Comment by dbuenzli** [comment]
> As with most questions about syntax, there are very few arguments that are strong compared to individual experiences and preferences.

Of course but to be honest I believe much more in the established rules and conventions of typography regarding legibility, punctuation and spacing than what seems to have emerged as a fashion among programmers without any compelling justification for it.

What I'm trying to say here is that if you don't have any strong reason not to do so it's better to follow established typographic conventions.

**Comment by gpetiot** [comment]
Closed with #461
