### ISSUE TITLE
Improve parens around infix operator.

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#266]
There have been a bit a back and forth on that topic: https://github.com/ocaml-ppx/ocamlformat/commit/ea5ed9ffeae42fe9caaa1005786f3d83da802157, https://github.com/ocaml-ppx/ocamlformat/issues/115, https://github.com/ocaml-ppx/ocamlformat/pull/141

I'll copy paste comments from ea5ed9ffeae42fe9caaa1005786f3d83da802157:
 
> Add discretionary parens on nested binops with different precedence
> 
> Add parens around an arg of a binop that is also a binop of a
> different precedence, unless the line breaks, in which case the
> nesting structure is indicated by indentation.
> 
> Examples:
```
;; f (a || (b && c))

;; f
     ( aaaaaaaaaaaaaaaaaaaaa
     || (bbbbbbbbbbbbbbbbbbbbb && ccccccccccccccccccccc) )

;; f
     ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
     || bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
        && ccccccccccccccccccccccccccccccccc )

;; f ((a && b) || c)

;; f
     ( (aaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbb)
     || ccccccccccccccccccccc )

;; f
     ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       && bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
     || ccccccccccccccccccccccccccccccccc )
```

**Comment by hhugo** [comment]
cc @mshinwell

**Comment by mshinwell** [comment]
I don't think the rule about using indentation instead of parentheses should ever apply.  It's just too easy to make a mistake here.  Bear in mind this is a long-standing problem, hence the provision of warnings in compilers like GCC, which don't take account of indentation.

(I'm also unclear why there are spaces just inside parentheses in the examples above; that seems highly non-standard.)

**Comment by jberdine** [comment]
See #275 for an option for using parens, and added parens for `not`.

Re `not`, do you think it is special compared to any other application?

This is probably a case where using type information would help, so that only cases which had multiple well-typed interpretations, up to the grammar's ambiguity, would need to be explicitly disambiguated.

**Comment by jberdine** [comment]
@hhugo, @mshinwell, does the current option resolve this issue? Every `not` application that is an arg of an infix op is parenthesized, and for reference, the examples above formatted with the added option:
```
[@@@ocamlformat "infix-precedence=parens"]

;;
f (a || (b && c))

;;
f
  ( aaaaaaaaaaaaaaaaaaaaa
  || (bbbbbbbbbbbbbbbbbbbbb && ccccccccccccccccccccc) )

;;
f
  ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  || ( bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
       && ccccccccccccccccccccccccccccccccc ) )

;;
f ((a && b) || c)

;;
f
  ( (aaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbb)
  || ccccccccccccccccccccc )

;;
f
  ( ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      && bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb )
  || ccccccccccccccccccccccccccccccccc )

[@@@ocamlformat "infix-precedence=indent"]

;;
f (a || (b && c))

;;
f
  ( aaaaaaaaaaaaaaaaaaaaa
  || (bbbbbbbbbbbbbbbbbbbbb && ccccccccccccccccccccc) )

;;
f
  ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  || bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
     && ccccccccccccccccccccccccccccccccc )

;;
f ((a && b) || c)

;;
f
  ( (aaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbb)
  || ccccccccccccccccccccc )

;;
f
  ( aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    && bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  || ccccccccccccccccccccccccccccccccc )
```

Also regarding the spaces inside parens, there is a general pattern ocamlformat tries to follow where parens whose matching paren is on another line have a space inside, while parens matched by a paren on the same line do not have space inside. This has (unscientifically) been observed to help some people visually match parens, especially when using editors that aren't as helpful as e.g. emacs with rainbow-delimiters.

**Comment by jberdine** [comment]
As far as I understand, this has been addressed, please reopen with more info if not.
