### ISSUE TITLE
Format comments supporting ocamldoc syntax

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#268]
In particular, support the following two constructs:
- `{[ string ]}`	set the given string in preformatted source code style.
- `{v string v}`   set the given string in verbatim style.

See https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html

**Comment by jberdine** [comment]
I was thinking that it might be good to do something along the lines of:
* parse docstrings (and also comments?) with [Octavius.parse](https://github.com/ocaml-doc/octavius/blob/master/src/octavius.mli#L25)
* format parsed [Octavius.Types.t](https://github.com/ocaml-doc/octavius/blob/master/src/types.ml#L96) values wrapped to the margin, while preserving parsed form
* for non-docstring comments, preserve string exactly if parsing fails
* extend sanity checking to check equality of Octavius parsed forms

Thoughts?
