### ISSUE TITLE
Option to preserve syntax of extension points.

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#271]
I sometime want to be able to preserve the syntactic difference betrtween 
`[%expr let x in 2]`
and 
`let%expr x in 2`

This is especially important for code using [metaquot](https://github.com/ocaml-ppx/ppx_tools/blob/master/ppx_metaquot.ml)

**Comment by jberdine** [comment]
Possibly implement by comparing the location of `expr` and `let`, choosing the output style that preserves their relative order?
