### ISSUE TITLE
Improve documentation of formatting options.

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#299]
- [x] factorize the documentation of options regarding the syntax in config files
 (e.g. `Can be set in a 
       config file with an 'wrap-fun-args = {true,false}' line.`)
- [x] review existing options and ensure all values, and meaning of booleans, are documented
- [ ] improve support for boolean flags, changing the default value should update the documentation
- [ ] support short forms for inverted boolean flags, e.g. by changing capitalization
- [x] consider using a single env variable to configure ocamlformat
(e.g. `OCAMLFORMAT=opt1=1,opt2=2 ocamlformat`) 
- [x] divide the 'formatting' options and 'operational' options into separate sections

**Comment by gpetiot** [comment]
Can we consider everything on this list is done? (if I understand correctly the 4th point is the "no-" prefix)

**Comment by jberdine** [comment]
I'm not sure we have reviewed all the existing options documentation, but perhaps. The point about improving the docs for boolean flags is to make the documentation change when the default value is changed, which is not done I think. For inverted short forms, the thought was to use e.g. `-G` for the inverted version of `-g`, similarly to how `--no-goo` is the inverted long form of `--goo`.

**Comment by hhugo** [comment]
We can close, https://github.com/ocaml-ppx/ocamlformat/pull/1062 is merged.
