### ISSUE TITLE
Switch from ocaml-migrate-parsetree to ppxlib

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#305]
Instead of depending directly on ocaml-migrate-parsetree, use [ppxlib](https://github.com/ocaml-ppx/ppxlib)'s `Ast`.

Not a high priority currently, but if/when we want to combine ocamlformat with another ppx rewriter, they will need to agree on the Ast version, which ppxlib supports.

**Comment by hhugo** [comment]
@jberdine, what would be a use-case for combining ocamlformat and another ppx ?

**Comment by emillon** [comment]
Duplicate of #1460

**Comment by hhugo** [comment]
Should this be closed ?
