### ISSUE TITLE
Support docstrings specified with attributes

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#308]
Docstrings specified with ocaml.doc attributes trip the comments check, but parsetree seems to be ok. Formatting
```
type t = C of int  (** docstring comment *)

type t = C of int [@ocaml.doc " docstring attribute "]
```
fails even though the two declarations have essentially the same parsetree.

**Comment by hhugo** [comment]
I just got a report about this one (\cc @tiash)

**Comment by hhugo** [comment]
Should we close this one and open another issue about normalizing `[@ocaml.doc " docstring attribute "]` into `(** docstring comment *)`

**Comment by jberdine** [comment]
Yes, see #323 .
