### ISSUE TITLE
Command line args should override config file settings

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#309]
Currently config files are processed after command line arguments, resulting in the command line args being overridden by any setting set in any config file between the file being formatted and the file system root. This is backward, precedence of command line args should be higher than config files.

**Comment by gpetiot** [comment]
I tried to fix this without modifying the whole structure (i.e. processing cmdline before .ocamlformat/attributes) but there is no way to know whether an option has been set on the command line if its value is still equal to the default value, so we cannot decide to only update options (from .ocamlformat/attributes) when the value has not been previously modified by the cmdline.
I am not sure what is the right approach to process the cmdline last, at the moment the processing of arguments (`parse info validate` if I understand) is not parameterized by a conf, so perhaps it is simpler to pass an `~env` to `Term.eval`  that would have been modified by parsing the options in .ocamlformat/attributes (without overriding the existing env). But it still looks overcomplicated, is there a simpler solution that I am not seeing ?

**Comment by jberdine** [comment]
I don't see a simple way. :-( Note that there is another complication: where the .ocamlformat files are searched for depends on the input filename, which is only known by parsing the command line. That might suggest to parse the command line, find the file, read the config files, and parse the command line again. But the call to `parse` sets the backing refs whether the options are specified or not. The approach of using an env for the last parsing of the command line sounds plausible.

**Comment by hhugo** [comment]
We don't want cmdliner to deal with default values. That mean we need cmdliner to return optional values.

One thing I can imagine is,
- keep cmdliner to do validation, error messages, ..
- have cmdliner return unstructured values - `string option` (for example, `Some "max-iters=5"`)
- start with the default config and override config in a specific order with a single code path

```
default
|> update_using_dot_ocamlformat (* split file on newline + parse_n_update  *)
|> update_using_env_variable (* OCAMLFORMAT env variable split on ; or , + parse_n_update *)
|> update_using_cmdline (* fold over the list of string we got from cmdliner to parse_n_update *) 
```

Note that we would drop the environment variable handling from cmdliner and just parse and process a single variable (`OCAMLFORMAT`).

**Comment by samoht** [comment]
A possible way to do this is to have a toplevel `default` config value, which is built by reading the config files (first the global one, then the local one and finally some custom default values). Then the default values for cmdliner will be `default.foo`, `default.bar`, etc.

**Comment by jberdine** [comment]
This approach sounds feasible. Expanding a little:
1. parse command line with cmdliner to find the source files
2. for each source file f
   i. set `default` to an initial config value
   ii. for each config file found between `/` and `dirname f`
      a. process the config file, setting `default`
   iii. parse the command line with cmdliner again, using `default.option` as the default values of options, updating `default`

This would take a bit of reworking the current code in order to set up the right shared refs between the cmdliner defaults and update functions, plus the config file processing code. But it does not seem like a complete rewrite to me at the moment.

Changing to a single environment variable could be done by removing the env vars from the cmdliner spec and adding a phase to process the env var for each source file.

**Comment by gpetiot** [comment]
I think we can close this one now.
