### ISSUE TITLE
Rebase ocaml/ocaml#1229

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#310]
The PR for the extensions of the stdlib's `Format` module that ocamlformat uses, https://github.com/ocaml/ocaml/pull/1229, has fallen behind and needs to be rebased.

**Comment by gpetiot** [comment]
What is the priority of this one? (Is there a good chance it is accepted?)

**Comment by jberdine** [comment]
I expect that getting this accepted will take some rounds of discussion, probably with changes or generalizations of the current difference wrt upstream, etc. It's not high priority, but really ought to be done. It would probably be best to wait for https://github.com/ocaml/ocaml/pull/2002 and use `pp_print_custom_break` instead of `pp_pre_break`.

**Comment by gpetiot** [comment]
The rebase is done, I'm waiting for @jberdine to allow me to push.
