### ISSUE TITLE
Generalize Fmt.fits_breaks to allow break specs within breaks string

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#311]
Support for example:
```
    fits_breaks ".(" " in@ "
```
  instead of requiring
```
    fits_breaks ".(" " in" $ fits_breaks "" "@ "
```

**Comment by gpetiot** [comment]
Parsing of the break removed in #894, and so far the pattern described in this issue is not used in ocamlformat, but feel free to re-open if we need that some day.
