### ISSUE TITLE
Comments dropped from files consisting of only comments

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#32]
Files that contain only comments have no parsetree locations at all, which defeats the comment placement algorithm. It seems that comment-only files need to be specifically recognized and all the comments formatted even though they are not attached.

**Comment by hcarty** [comment]
If someone runs into this and wants a quick work around - adding a made-up annotation (ex. `[@@@unused]`) to the file will allow formatting to complete without hitting an ocamlformat error.

**Comment by jberdine** [comment]
Another work-around is `[@@@ocamlformat.disable]` from https://github.com/ocaml-ppx/ocamlformat/pull/66.
