### ISSUE TITLE
Newlines after PPX sequences

### ISSUE THREAD

**Issue by osener** [ocaml-ppx/ocamlformat#336]
It would be nice to have `;%lwt` sequences formatted closer to regular sequences. Maybe it could also follow the value of `sequence-style`?

```ocaml
let _ =
  Logs_lwt.debug (fun m -> m "Received data: %s" msg) ;%lwt read_loop chan


let _ =
  Logs_lwt.debug (fun m -> m "Received data: %s" msg);
  read_loop chan
```

**Comment by jberdine** [comment]
Just to be explicit, is the output you would prefer with `--sequence-style=terminator` the following:
```ocaml
let _ =
  Logs_lwt.debug (fun m -> m "Received data: %s" msg);%lwt
  read_loop chan
```
That is, with no space before `;` even though `%lwt` is there, or is it only the choice of whether to break the line that you are after?

**Comment by osener** [comment]
> That is, with no space before ; even though %lwt is there, or is it only the choice of whether to break the line that you are after?

Mainly the latter, but it would be nice to have both types of sequences behave the same. Here's an example from [lwt docs](https://ocsigen.org/lwt/3.2.1/api/Ppx_lwt#2_Sequence) where I find the original style looks easier to read:
```ocaml
(* original *)
let _ =  
  let i = ref 0 in
     write stdout "Hello, ";%lwt
     incr i;
     write stdout "world!"

(* ocamlformat output with [--sequence-style=terminator] *)  
let _ =
  let i = ref 0 in
  write stdout "Hello, " ;%lwt incr i; write stdout "world!"
```

**Comment by gpetiot** [comment]
It looks like we fixed this already, I'm closing this one.
