### ISSUE TITLE
Preserve position of comments in `match (*cmt*) expr with`.

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#341]
Refines https://github.com/ocaml-ppx/ocamlformat/pull/330

**Comment by gpetiot** [comment]
I don't see any problem with this code, is the problem still relevant for you ?

**Comment by jberdine** [comment]
The implementation of #330 has the undesired effect of transforming:
```
match
  (* comment about entire pattern matching *)
  e
with
| ...
```
to
```
(* comment about entire pattern matching *)
match e with
| ...
```
What should happen is that the comment stays on whichever side of `match` it is in the source.

**Comment by gpetiot** [comment]
For the record, on master it is now formatted as:
```
;;
match (* comment about entire pattern matching *)
      e with k -> z
```

**Comment by gpetiot** [comment]
Update: on master, this:
```ocaml
let foo =
 match
  (* comment about entire pattern matching *)
  e
with
| x -> x
```
is still rewritten as:
```ocaml
let foo =
  (* comment about entire pattern matching *)
  match e with x -> x
```

**Comment by hhugo** [comment]
#867 might resolve this issue.
