### ISSUE TITLE
build ocamlformat and ocamlformat_support from same branch

### ISSUE THREAD

**Issue by avsm** [ocaml-ppx/ocamlformat#349]
I'm working on a monorepo vendoring tool that uses git-subtree under the hood to allow a number of OCaml tools to be built in one big Dune repository, and embedding ocamlformat is currently a bit problematic.  The reason is that `ocamlformat_support` is built out of a different branch than the main library, and it's difficult to vendor two branches simultaneously.

Would you be willing to accept a PR that merges the support branch directly into master, so that there's a single branch that builds both libraries?  In return, ocamlformat can then be included in the OCaml Platform monorepo.

**Comment by jberdine** [comment]
Does #351 work for you?

**Comment by avsm** [comment]
Thanks again @jberdine!
