### ISSUE TITLE
Align match cases

### ISSUE THREAD

**Issue by samoht** [ocaml-ppx/ocamlformat#360]
Would it be possible for ocamlformat to align match cases?

e.g. having

```ocaml
match f with
| Foo -> toto
| Bar ijx -> bar ijx
```

turned into

```ocaml
match f with
| Foo     -> toto
| Bar ijx -> bar ijx
```

**Comment by samoht** [comment]
> Do you think a "fraction of the margin" approach would be tolerable?

Yes it would be fine. I usually do this only for simple pattern matchings (or simple subset of the set of cases) so I am fine if complex/long cases are not aligned.

**Comment by jberdine** [comment]
Also, the same treatment ought to be applied to align `of` in sum type definitions.
