### ISSUE TITLE
Format only a fragment on the file

### ISSUE THREAD

**Issue by samoht** [ocaml-ppx/ocamlformat#362]
`ocp-indent` has an option to fragment only a portion of a file:

```
-l RANGE, --lines=RANGE (absent=-)
           Only re-indent the lines in RANGE (eg. 10-12), adapting to the
           current indentation of surrounding lines. Lines start at 1.
```

I think it's useful to be integrated with some editors (/cc @AltGr and @emillon)

**Comment by jberdine** [comment]
I think this would clearly be useful, but I don't know how to implement it internally. One option might be to reformat the whole file, compute a patch file using diff, filter the hunks by line number, and then apply the resulting patch.

**Comment by samoht** [comment]
Can't you just extract these lines, parse/format as usual (e.g. the fragment should be valid OCaml) and print the new fragments with the same tabulation as the first extracted line?

**Comment by jberdine** [comment]
I don't know how usable it would be, but perhaps something like that could work:
1. split the input file into 3 files by line numbers: prefix, range, suffix
2. format range to a tmp file range' (if this fails, fail the whole format run)
3. prefix every line of range' with the same leading whitespace as the first line of range
4. concat prefix, range', suffix files to obtain the output

**Comment by gpetiot** [comment]
Is there a not-so-difficult way to link the locations between two iterations of ocamlformat ?
Supposing we only want to format lines 9--13, supposing that means only formatting the items in lines 10--12 (it would be great to adjust the value of `--lines` to 10--12 on the way). Supposing the formatting of items in lines 10--12 results in lines 10--14 (that's where I would like to link 10--12 to 10--14), so we update the value of `--lines` to 10--14, and we should reach a fixpoint.

**Comment by jberdine** [comment]
There is nothing internal to ocamlformat that tracks line numbers. Since 
lines are broken largely by Format, it doesn't seem straightforward to 
add. Something could probably be done by diffing the input and output 
files. Maybe some of the implementation of patdiff could be repurposed 
to do so.

**Comment by gpetiot** [comment]
See discussion in #366
