### ISSUE TITLE
Issue with "break-struct=natural"

### ISSUE THREAD

**Issue by samoht** [ocaml-ppx/ocamlformat#376]
Using `break-struct=natural`, the following code:

```ocaml
module Hash = struct
  include Hash
  module type S = S.HASH
end
```

is reformated as follows:

```ocaml
module Hash = struct include Hash

                     module type S = S.HASH end
```

which looks a bit strange to me.

**Comment by gpetiot** [comment]
I deleted my PR as I am not sure what the expected output is supposed to be in the various cases (and the description of the option does not seem to fit the users expectations).

**Comment by jberdine** [comment]
The output:
```ocaml
module Hash = struct include Hash

                     module type S = S.HASH end
```
is not intended. ocamlformat should never increase indentation by an amount that is sensitive to the width of sections of input code.

**Comment by gpetiot** [comment]
It seems difficult to me to have both:
- everything on the same line if this fits
- breaks two lines if it does not fit (only one linebreak is the standard for hvboxes)

**Comment by jberdine** [comment]
I expect that using (one of the wrappers of) `Format.pp_print_fits_or_breaks` with a "breaks" string containing a newline char ought to be able to break two lines (I think even without leaving trailing whitespace) only when the box doesn't fit.

**Comment by gpetiot** [comment]
I'm struggling a lot on this one, if anyone is willing to pick up this issue? I am not sure it is only a box issue, I doubt the fits/breaks mechanism is powerful enough for what we want here.

**Comment by samoht** [comment]
Can't we just revert to something a bit less broken? I am fine to remove the option completely if it's too hard to implement properly.
