### ISSUE TITLE
How to use ocamlformat as a library?

### ISSUE THREAD

**Issue by thangngoc89** [ocaml-ppx/ocamlformat#377]
Hello, I'm the maintainer of [Sketch.sh](https://sketch.sh) and I'm currently working on converting between ocaml and reason syntax feature, The ocaml output from refmt is pretty bad and sometimes invalid. So I'm looking for a way to output better ocaml code. I would love to have some pointers about where to start using ocamlformat as a library. Thank you very much

**Comment by jberdine** [comment]
I am not sure about your context, but it might be useful to see [here](https://github.com/ocaml-ppx/ocamlformat/blob/a1bbe9d62be79cb4a4aad3ea1d1940330f34fa44/test/Makefile#L94) in the test makefile for the command that has been used to convert reason to ocaml using the ocamlformat_reason executable. Note that the reason support in ocamlformat was last tested with reason 1.13.4, so might need updating.

**Comment by thangngoc89** [comment]
@jberdine Thank you for the quick response. Does ocamlformat compatible with Reason AST be ause I already have refmt in the code, I'm planning to parse Reasonml code with refmt and pass the AST to ocamlformat for OCaml output

**Comment by jberdine** [comment]
ocamlformat_reason accepts a binary serialized ast as produced by refmt. So yes, but modulo possible changes across versions.

**Comment by thangngoc89** [comment]
@jberdine Thank you. let's me look into this. as both project use OMP, this should be easy.

**Comment by jberdine** [comment]
@thangngoc89, are there any further questions, or would it make sense to close this?

**Comment by thangngoc89** [comment]
@jberdine Yeah. thank you for your time. I'm working on this and I think I have everything I need.
