### ISSUE TITLE
Lost comment

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#396]
with the following:
```ocaml
let foo x = (* hello world *) (y : z)
```

**Comment by gpetiot** [comment]
This is rewritten (without the comment) as: `let foo x : z = y`, is it intended or does it has to be fixed before this issue? (looks like relocating the `: z` interferes with relocating the comment)

**Comment by jberdine** [comment]
The output sans comments is as I expect, but I guess that we miss a Cmts.reloc somewhere along the way.
