### ISSUE TITLE
Record literal syntax--asymmetrical spacing around '='

### ISSUE THREAD

**Issue by yawaramin** [ocaml-ppx/ocamlformat#4]
# Observed behaviour

The following:

```ocaml
let x = {a = 1; b = true}
```

is reformatted as:

```ocaml
let x = {a= 1; b= true}
```

# Expected behaviour

One space on either side of the equals sign.

**Comment by jberdine** [comment]
Are there any cases where the space is needed for correct parsing, or is this a style preference point?

**Comment by hcarty** [comment]
I think this is purely a style choice.

**Comment by yawaramin** [comment]
I would say it's about consistency. I support whatever style you think is readable, as long as it's used consistently. E.g., we can achieve that with

```ocaml
let x= {a= 1; b= true}
```

... and other variations, of course, but not with the current output.

**Comment by jberdine** [comment]
I agree that consistency is a good objective, perhaps not the absolute highest priority one, but important.  At times what looks like inconsistent formatting can productively be used to indicate additional information that is present in the parsetree but may not be immediately visually obvious when reading code.

There is an issue in that I don't think that everyone agrees on which sets of constructs ought to be consistent with each other. For example, one position is that every occurrence of the `=` character should be spaced in the same way, and another position is that the `=` in record expressions should be spaced similarly to the `:` in record type definitions, and another position is both of the previous two at once.

**Comment by yawaramin** [comment]
Ah, I'd never heard of this symmetrical positioning rule for `:` and `=`, but I'm seeing it now actually grepping through the OCaml compiler codebase. OK then! 😅

**Comment by ubsan** [comment]
It's quite odd, for me, that you have `val x : int`, but `type x = {x: int}` - why not do `type x = {x : int}` and `let x = {x = 0}`

**Comment by bobbypriambodo** [comment]
I'm also with @ubsan here, and would have preferred the first suggestion (equal spacing on both sides of `=` and `:`). The main reason is perhaps familiarity; I don't think I've ever encountered the form `x= y` anywhere. It also raises the question of whether the attachment has any significance.

I think @ubsan's first suggestion gives both consistency and clarity. Unless I'm wrong and the current style is actually widely adopted...

**Comment by ubsan** [comment]
I think the only people using the current style are those that format with ocamlformat 😄 (I know I use it, because screw manual formatting 😛)
