### ISSUE TITLE
Recognise all sugars for extension points. 

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#410]
Also, consider always preserving the syntax of extension points, rewriting between syntaxes can be done outside ocamlformat.

**Comment by jberdine** [comment]
Could you clarify what is missing from `extension-sugar=preserve` for this?

**Comment by hhugo** [comment]
We currently don't preserve syntax in a bunch of cases:

- `type%ext t = int`
- `let _ = lazy%ext e`
- ...

Just look at all occurrences of `ext_attributes` in the ocaml parser.

**Comment by emillon** [comment]
This is a good list:

https://github.com/ocaml-ppx/ocamlformat/blob/ff6bf96ef935e6665f92a3529805c4c835bbdcf1/test/passing/source.ml#L88-L103

It gets formatted as:

https://github.com/ocaml-ppx/ocamlformat/blob/ff6bf96ef935e6665f92a3529805c4c835bbdcf1/test/passing/source.ml.ref#L97-L129

(this is also available as https://github.com/ocaml-ppx/ocamlformat/blob/ff6bf96ef935e6665f92a3529805c4c835bbdcf1/test/passing/shortcut_ext_attr.ml but this is a fixpoint test so it does not show what is supported and what is not)

**Comment by gpetiot** [comment]
These ones are more difficult due to the attributes, it seems not all of them can be rewritten with the short syntax.

**Comment by emillon** [comment]
What do you mean? the list I linked to is valid syntax, so they can be rewritten.

**Comment by emillon** [comment]
`let open! %ext A in e` exists too and it's special cased because without the space, `!%` is lexed wrongly (there's `open! %M` too).
