### ISSUE TITLE
 formatting did not stabilize after 10 iterations

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#412]
Here are some files taken for opam packages:
- links-postgresql.0.7.3: "core/closures.ml"
- coccinelle.1.0.2: "commons/ograph_extended.ml"
- incr_dom_widgets.v0.11.0: "src/table.ml"

**Comment by gpetiot** [comment]
The issue for links-postgresql.0.7.3: "core/closures.ml" can be reduced to:
```
(* Debug.print ("free var: "^string_of_int x); *)
{< free_vars = IntSet.add x free_vars >}
```

**Comment by gpetiot** [comment]
I do not get any error for incr_dom_widgets.v0.11.0: "src/table.ml".
What options did you use?

**Comment by hhugo** [comment]
Don't manage to reproduce anymore
