### ISSUE TITLE
Configure Emacs for v4.02.3

### ISSUE THREAD

**Issue by SekibOmazic** [ocaml-ppx/ocamlformat#42]
Sorry if this is not the right place for asking the questions. Feel free to close it if so.

I'd like to use `ocamlformat` with OCaml v.4.02.3 because I also use it for ReasonML development. Is that possible somehow? 
I've tried to install it under v4.05.0, switch back to v4.02.3 and configure my Emacs `init.el` like this:
```
(require 'ocamlformat "~/.opam/4.05.0/packages.dev/ocamlformat/emacs/ocamlformat.el")
```
Didn't help at all. The `ocamlformat` works fine from command line.

**Comment by jberdine** [comment]
Did you install by pinning master or some other way? If so, was it before or after #27 was merged, as it changed the installation of ocamlformat.el to actually install it.

**Comment by SekibOmazic** [comment]
@jberdine I did it by pinning master (just followed installation instruction) and it was 3 days ago - so definitely after merging #27 
But I have installed only `ocamlformat` and not `ocamlformat_reason`.

**Comment by jberdine** [comment]
Ok, then `ocamlformat.el` should have been installed to `~/.opam/4.05.0/share/emacs/site-lisp/ocamlformat.el`. That directory is the same one where other packages such as tuareg put their elisp code. For me `(require 'ocamlformat)` after that directory is added to the load-path is enough. Do you use `opam-user-setup` to manage the load-path, and other, configuration? Just make sure you `require` ocamlformat after that runs.

**Comment by SekibOmazic** [comment]
It was my broken Emacs config at the end (I ruined eshell). Now everything works fine.

@jberdine thanks for the help!

I also have `(add-hook 'before-save-hook 'ocamlformat-before-save)` in my config. Maybe this helps someone.
