### ISSUE TITLE
Alternative indentation for patch-match clauses

### ISSUE THREAD

**Issue by hongchangwu** [ocaml-ppx/ocamlformat#432]
Currently `ocamlformat` gives

```ocaml
match f with
| Foo really_long_foo_arg ->
    really_long_foo_arg
| Bar really_long_bar_arg ->
    really_long_bar_arg
```

However a lot of existing OCaml code uses the following alignment:

```ocaml
match f with
| Foo really_long_foo_arg ->
  really_long_foo_arg
| Bar really_long_bar_arg ->
  really_long_bar_arg
```

The second is also the default output of `ocp-indent`, can we add an option to support this style?

**Comment by gpetiot** [comment]
This is planned: https://github.com/ocaml-ppx/ocamlformat/pull/428

**Comment by hongchangwu** [comment]
Awesome, thanks! I only searched the issues and didn't find anything.
