### ISSUE TITLE
Option sequence-style=breaker should not break englobing expressions

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#438]
This should not break:

```
[@@@ocamlformat "break-sequences"]

let f x =
  x.contents
  <- ( print_string "coucou";
       x.contents )
```

**Comment by jberdine** [comment]
I don't understand, we have:
```
[@@@ocamlformat "break-sequences=true"]

let f x =
  x.contents
  <- ( print_string "coucou" ;
       x.contents )

[@@@ocamlformat "break-sequences=false"]

let f x = x.contents <- (print_string "coucou" ; x.contents)
```
which seems to be as intended. Can you clarify?

**Comment by gpetiot** [comment]
This issue has been opened to keep track of a request from Hugo in [this PR](https://github.com/ocaml-ppx/ocamlformat/pull/434#discussion_r217715559) but if everything is as intended I don't mind closing it.

**Comment by jberdine** [comment]
Ok, thanks for the context. I still don't understand what the desired behavior is though.

**Comment by gpetiot** [comment]
Works as intended indeed.
