### ISSUE TITLE
trailing newline at end of file

### ISSUE THREAD

**Issue by hannesm** [ocaml-ppx/ocamlformat#45]
with ocamlformat v0.2, I get at the end of file:
```
   in
-  names, off
+  (names, off)
+
```

this extra newline is imho bad (and git diff complains about it by marking it red).  it would be great if ocamlformat would avoid generating newlines at the end of file. :)

again, thank you for developing ocamlformat.  I'm looking forward to use it and never have to care about formatting of my OCaml code.

**Comment by jberdine** [comment]
These trailing newlines are an unfortunate consequence of details of how let-bindings are formatted. I would like to eliminate them, but have not had the time (It is not an entirely trivial code change.)

**Comment by jberdine** [comment]
Actually, it was pretty trivial.

**Comment by hannesm** [comment]
@jberdine thank you very much for the quick fix!
