### ISSUE TITLE
Revisit setting `--disable-outside-detected-project` in editor integration

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#456]
From #391:

> I've reverted the change to the emacs mode for now so that the behaviour is preserved (to be discussed in another PR)

Do we want to revisit this question now that `--root` and `--disable-outside-detected-project` are supported? It seems to me that there are at least two options:

1. change the editor integration to pass `--disable-outside-detected-project`

2. add some discussion to the user docs about setting it with the env variable

Thoughts?

**Comment by gpetiot** [comment]
I don't know if we always want this option to be passed to ocamlformat. Maybe the best is to give more details about this option in the user doc (maybe it is too much to put both code snippets with and without this option in the user doc?)

**Comment by jberdine** [comment]
I expect it would be enough to mention / give an example of customizing `ocamlformat-command` to e.g. `ocamlformat --disable-outside-detected-project`.

**Comment by gpetiot** [comment]
Closed with PR #468
