### ISSUE TITLE
Allow leaving semicolons at the end of lines in record literals

### ISSUE THREAD

**Issue by Wilfred** [ocaml-ppx/ocamlformat#467]
I'm trying to apply ocamlformat to a codebase that formats records like this:

```ocaml
let my_foo =
  { bar = "a very very very very very long literal";
    baz = "another very very very very very long literal";
    quux = "yet another very very very very very long literal" }
```

I'm hoping that I can use ocamlformat to make code consistent without making too many changes to the current style. Is there any way to force ocamlformat to keep the semicolons at the end of the line here?

The closest to the above style (that I can see) is `field-space = loose`, which gives the following result:

```ocaml
let my_foo =
  { bar = "a very very very very very long literal"
  ; baz = "another very very very very very long literal"
  ; quux = "yet another very very very very very long literal" }
```

I can't see any other options for controlling `;` position in ocamlformat-help.txt. Is it possible?

**Comment by gpetiot** [comment]
This is a duplicate of issue #264, is PR #461 what you would expect ?

**Comment by Wilfred** [comment]
Agreed it's a duplicate, and #461 would certainly meet my needs. Thanks :)
