### ISSUE TITLE
gen_version.sh is not portable

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#470]
Hi,

When `/bin/sh` is not bash, some errors are displayed:

```
          sh src/Version.ml [dev]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
          sh src/Version.ml [release]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
dune build _build/release/ocamlformat-help.txt
          sh src/Version.ml [release]
../tools/gen_version.sh: 7: ../tools/gen_version.sh: [[: not found
../tools/gen_version.sh: 12: ../tools/gen_version.sh: [[: not found
```

The reason is that it's invoked with `(sh)`, but this is a bash script. In particular, it uses `[[` to do pattern matching.

There are some ways to do that in a portable way using vanilla `sh`, but I'm wondering if there's a particular reason not to use `dune subst` for this?

Thanks

**Comment by emillon** [comment]
(I can help port that to plain `sh` or `dune subst`)

**Comment by gpetiot** [comment]
Would this issue be fixed by PR #471 ?

**Comment by jberdine** [comment]
Since `gen_version.sh` starts with, `#!/usr/bin/env bash`, I don't understand how a non-bash sh gets run?

**Comment by jberdine** [comment]
But I'm not opposed to having that script modified to work with more shells.

**Comment by emillon** [comment]
@gpetiot Yes it seems so. I'm not familiar enough with ocamlformat internals to say if there's something fundamentally different here, but many projects using dune are using this mechanism. In particular, I believe that the different use cases outlined in the PR should be compatible with `["dune" "subst"] {pinned}`.  For a more conservative patch, you can also keep the `Version` module and leave the only substitution there (`let version = %%VERSION%%`).

@jberdine the script is invoked using `(sh tools/gen_version.sh)` (see #448). This means that it will be executed using `sh tools/gen_version.sh`. When doing that, the `#!` line is ignored (also, consider that some systems don't have bash installed). Sorry I missed that while reviewing the PR.
