### ISSUE TITLE
`--disable-outside-detected-project` and `.ocp-indent` files

### ISSUE THREAD

**Issue by diml** [ocaml-ppx/ocamlformat#473]
I'm trying to find an emacs configuration that works for both projects that use ocamlformat and projects that don't. I tried the newly added `--disable-outside-detected-project` option which seems good for that. However, when a project doesn't have a `.ocamlformat` file but has a `.ocp-indent` file, then it is considered as using ocamlformat and `ocamlformat --disable-outside-detected-project` does reformat files.

I find this behaviour unexpected as many projects that don't use ocamlformat have `.ocp-indent` files. I suggest that when only a `.ocp-indent` file is found, either:
- files are only re-indented but not reformatted
- nothing special is done and files are printed as it

**Comment by jberdine** [comment]
I think it's a bug for ocamlformat to enable itself in `--disable-outside-detected-project` mode based just on the existence of `.ocp-indent`.
