### ISSUE TITLE
Facebook preset profile

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#474]
The idea is to have the current `default` profile to become a `facebook` profile that could be adopted in the regression tests to reduce the diff with the existing test codebase.
And the new `default` profile could be changed for a better adoption by the community (see the thread on OCaml discuss where the default is not what people expect). Thoughts?

**Comment by jberdine** [comment]
At the moment it doesn't make sense to define a facebook profile, since there isn't just one. We can change default settings without churning ocamlformat by adding the current default settings to the repo's .ocamlformat.
