### ISSUE TITLE
Formatting of code blocks inside documentation comments

### ISSUE THREAD

**Issue by diml** [ocaml-ppx/ocamlformat#478]
It would be nice if code blocks inside documentation comments where formatted just like normal code so that they don't have to be formatted manually.

**Comment by jberdine** [comment]
This sounds like a good idea to me.

If someone wants to manually format a code block, either an attribute could be added to disable ocamlformat, or perhaps a verbatim block could be used. I wonder if it is possible to attach an attribute on the docstring in the source file, or if it is necessary to put the attribute in the code block. The latter would be preferable I think. But either way, I think the first step is to format code blocks, and later see how pressing a disabling solution is.

**Comment by diml** [comment]
Agreed. Personally, I'd be happy to make sure the code snippets are always valid OCaml code so that they can be automatically formatted.

**Comment by gpetiot** [comment]
To do after #721
