### ISSUE TITLE
Functor application and break-struct wrap incorrectly

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ocamlformat#487]
First of all let me say how excited I am about `ocamlformat`, it's a great piece of work and it has evolved really well since the last time I tried it about 10 months ago. Thanks for putting it together!

I started trying it on our codebase at Cryptosense so I'll probably open a bunch of issues as I found some bugs/quirks and also have a few feature requests.

Anyway, I digress.

Consider the following piece of code:

```ocaml
module A = Make(struct type t = int end)(String)

module B = Make(Some_super_long_module_name_that_will_exceed_margin)(Some_other_shorter_module_name)
```

that gets formatted as:

```ocaml
module A =
  Make (struct
      type t = int
    end)
    (String)

module B =
  Make
    (Some_super_long_module_name_that_will_exceed_margin)
    (Some_other_shorter_module_name)
```

while I would expect the first module expr to be formatted in a similar way as the second one, ie something like:

```ocaml
module A =
  Make
    (struct
      type t = int
    end)
    (String)
```

My guess is that it doesn't cope well with `break-struct=force` (which is the default).

I'm of course happy to help fixing this and contribute to the project!

**Comment by jberdine** [comment]
Note that the current behavior is as intended. IIUC the crux of this is a style suggestion to avoid the docked formatting of struct args of functor applications unless they are the last/only arg. @NathanReb, is the presence of the `(String)` arg significant to your suggestion? That is, do you also object to:
```
module A =
  Make (struct
      type t = int
    end)
```

**Comment by NathanReb** [comment]
Interesting, I didn't think of it that way.

I just tried to format the following code with `break-cases=all`:

```ocaml
let _ = some_function (function
    | 1 -> true
    | _ -> false)

let _ = some_function (function
    | 1 -> true
    | _ -> false)
    12
```

which outputs:

```ocaml
let _ =
  some_function (function
    | 1 ->
        true
    | _ ->
        false )

let _ =
  some_function
    (function
      | 1 ->
          true
      | _ ->
          false)
    12
```

This could be considered as the equivalent situtation for regular applications and it does behave differently than in the module expr case.

I think I'm indeed not in favor of:
```ocaml
module A =
  Make (struct
      type t = int
    end)
```
either but I feel like it's completely subjective and is probably a different matter that, if ever, should be configured by a separate option. I'll open a different issue for this!

A consistent behaviour for regular and module application would already be a good start.

**Comment by jberdine** [comment]
Yes, there are definitely some inconsistencies of this sort between the module language and the expression language, and within the module language itself. Most of this is due to current implementation constraints more than choice. Much more flexibility and consistency would be possible if #406 was resolved.

**Comment by gpetiot** [comment]
For info, with #762 your second example is formatted like this:
```ocaml
let _ =
  some_function (function
    | 1 -> true
    | _ -> false )

let _ =
  some_function
    (function
      | 1 -> true
      | _ -> false )
    12
```

For the issues on modules, I don't know what we could do to improve this case without breaking a lot of other cases.
