### ISSUE TITLE
try and match expressions or-pattern cases are handled inconsistently

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ocamlformat#489]
The or-pattern cases in a `try` expression are formatted in a different way than in a `match` expression.

If you set `break-cases=all`, the following code:

```ocaml
let _ =
  try () with
  | End_of_file
  | Not_found ->
      ()

let _ =
  match 1 with
  | 1
  | _ ->
      true
```

is formatted as:

```ocaml
let _ =
  try () with
  | ( End_of_file
  | Not_found ) ->
      ()

let _ =
  match 1 with
  | 1
  | _ ->
      true
```

while I would expect the `try` expression to remain the same.

**Comment by jberdine** [comment]
Yes, with `break-cases=all`, the parens around nested or-patterns aren't needed.
