### ISSUE TITLE
Line endings changed to \r\n on Windows.

### ISSUE THREAD

**Issue by leviroth** [ocaml-ppx/ocamlformat#49]
On Windows, I have some files with the Unix `\n` line endings. However, when running them through ocamlformat, the line endings are changed to the Windows `\r\n` line endings.

Ocamlformat version: 0.2

Sample file (any file should work):

```ocaml
let () =
  let x = () in
  x
```

**Comment by jberdine** [comment]
Thanks for the report. Nothing specific is done with line endings by ocamlformat, it just writes a file in standard text mode. On windows this results in "native" `\r\n` line endings. It may be that switching the file to binary mode would work to prevent newlines from being translated. But there may be other consequences as well, I don't know. There is also the question of whether windows users in general expect windows-specific line endings or not. It would be useful to get input from more windows users on this.

**Comment by leviroth** [comment]
>It may be that switching the file to binary mode would work to prevent newlines from being translated.

If I'm understanding things right, the newline behavior can be modified via the `Formatter.formatter_out_functions` type. Something like:

```ocaml
  let old_out_functions = Format.pp_get_formatter_out_functions fs () in
  let new_out_functions =
    let open Format in
    { old_out_functions with
      out_newline= (fun () -> old_out_functions.out_string "\r\n" 0 2) }
  in
  Format.pp_set_formatter_out_functions fs new_out_functions
```

>There is also the question of whether windows users in general expect windows-specific line endings or not. It would be useful to get input from more windows users on this.

Personally, I think I would expect the line ending type of a given file to be preserved, regardless of platform. So on Windows, formatting a Unix-ending file results in a Unix-ending file, while a Windows-ending file remains a Windows-ending file even if the formatting happens to be done on Unix.

**Comment by jberdine** [comment]
Note that the line ending type used in the original file is not available in the parsetree, AFAIK. Adding a config option to specify the desired line endings seems like a good solution.

**Comment by leviroth** [comment]
Sounds good to me. I assume the Emacs integration would be able to pass that configuration along automatically based on the current buffer?

**Comment by jberdine** [comment]
I guess that the emacs integration could do that, but I don't know emacs very thoroughly.

**Comment by jberdine** [comment]
Question: is there a use case where ocamlformat is run under unix, on files with unix line endings, and output files with windows line endings are desired? @leviroth

**Comment by leviroth** [comment]
I can't think of any, personally.

**Comment by jberdine** [comment]
For visibility, #274 fixes this, but needs to be tested at least once on windows. Just clone the PR branch and `make test`. Any help appreciated.

**Comment by jberdine** [comment]
I don't understand the priority of this one, given that it is only a convenience feature to avoid the need to post-process with e.g. dos2unix.

**Comment by gpetiot** [comment]
I think we can agree it won't be fixed, and that the chosen solution is to run dos2unix.

**Comment by nojb** [comment]
Hello, I am experimenting with `ocamlformat` on our codebase (Windows with LF endings), and this issue is a usability blocker for us mainly because it interferes with the `dune build @fmt` workflow. Using `dos2unix` can fix the issue but it is hardly user-friendly. Just my 2c. I will try to give #274 a try to see if it helps.
