### ISSUE TITLE
Weird module + include formating with break-struct=natural

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#490]
When my .ocamlformat configuration file contains `break-struct=natural`, I get pretty weird formatting in a file that contains only a module and an include. They end up both on the same line. This behavior doesn't happen when there is more content in the file.

The .ocamlformat file:

```
break-struct=natural
```

Original file:

```ocaml
module Json = Yojson.Basic

include B
```

Results in:

```ocaml
module Json = Yojson.Basic include B
```

But a file with more content:

```ocaml
module Json = Yojson.Basic

include EsMappingShared

module T = struct
  let v = x
  let y = 100
  let z = 200
end

module Y = struct let v = x end
```

Ends up in a normal formatting:

```ocaml
module Json = Yojson.Basic
include EsMappingShared

module T = struct
  let v = x

  let y = 100

  let z = 200
end

module Y = struct let v = x end
```

**Comment by jberdine** [comment]
I guess we have an hvbox around (toplevel) structures where you'd rather have a vbox. @gpetiot, @samoht, do you recall if not breaking between items of non-toplevel structures is desired?

**Comment by samoht** [comment]
I agree with @Khady, we should always break after top-level items. I think the aim of that option was simply to write on one-line:

```ocaml
module X = Set.Make (struct type t = int let compare = compare end)
```

**Comment by jberdine** [comment]
Ok, this will need a special case treatment of toplevel structs then.
