### ISSUE TITLE
Don't wrap nested match in parenthesis

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#492]
We have some code like this, using nested `match`:

```ocaml
let () =
  match v with
  | None -> None
  | Some x ->
  match x with
  | None -> None
  | Some x ->
  match x with
  | None -> None
  | Some x -> x
```

When it is reformated, the second and third `match` are parenthesized, which is not very nice and creates some noise. Could it be avoided?

```ocaml
let () =
  match v with
  | None -> None
  | Some x ->
    ( match x with
    | None -> None
    | Some x -> (match x with None -> None | Some x -> x) )
```

ocamlformat config:
```
m=80
doc-comments=before
let-and=sparse
break-cases=fit
break-struct=natural
sequence-style=terminator
cases-exp-indent=2
ocp-indent-compat=true
leading-nested-match-parens=true
break-infix=fit-or-vertical
break-separators=after
type-decl=sparse
```

**Comment by jberdine** [comment]
This is implementable, and was actually done previously, but was removed in the interest of uniformity and ease of refactoring the order of cases. I guess this is another point where there is no single style and another option is needed.
