### ISSUE TITLE
Newline after then instead of before?

### ISSUE THREAD

**Issue by brendanlong** [ocaml-ppx/ocamlformat#499]
Could we get an option to add newlines after `then` instead of `before`? For example:

```
if Error_response.should_print fields ~verbose:conn.verbose
then
  Thread.debug (Error_response.to_string ~verbose:(conn.verbose > 1) fields)
else return ())
```

If a line starts with `if`,  I already know it's an `if` statement so starting the next line with `then` is just noise. I would prefer to format it like this:

```
if Error_response.should_print fields ~verbose:conn.verbose then
  Thread.debug (Error_response.to_string ~verbose:(conn.verbose > 1) fields)
else return ()
```

If the arguments don't fix on line, then adding the `then` on its own line is still good:

```
if Error_response.should_print fields ~verbose:conn.verbose
   && other_tests_here
then
  Thread.debug (Error_response.to_string ~verbose:(conn.verbose > 1) fields)
else return ()
```

Ideally there would also be an option that if either side of the `if` doesn't fit on one line, we break both sides (or even better, an option to always break before the contents of an `if`/`else`):

```
if Error_response.should_print fields ~verbose:conn.verbose then
  Thread.debug (Error_response.to_string ~verbose:(conn.verbose > 1) fields)
else
  return ())
```

**Comment by jberdine** [comment]
Reasonable suggestions. The trouble is expressing them as a nesting of formatting boxes over the parsetree, which we need to do without knowing what subexpressions will break. This probably needs #406.

**Comment by gpetiot** [comment]
Already fixed with master.
