### ISSUE TITLE
Option for list of sequence operators

### ISSUE THREAD

**Issue by brendanlong** [ocaml-ppx/ocamlformat#500]
The "try to fit as much on a line as possible" logic makes complicated async code really hard to read. While there are a few cases where putting multiple monad operators on the same line is nice, I think in terms of logic-a-program-can-do, I'd be happy with "break before all monad operators".

It seems like this is basically the logic `break-sequences` is meant to do, so I wonder if we could add an option to define what sequence operators are.

For defaults, I would suggest the list of monad operators from Core, Async, Rresult, and Lwt:

 - `>>|`
 - `>>=`
 - `>>|?`
 - `>>=?`
 - `>|=`

(Ignoring the backwards ones in Lwt because I've never seen them used and don't know how they should be formatted)

**Comment by jberdine** [comment]
I think this should be reevaluated after #463, and perhaps #464.

**Comment by gpetiot** [comment]
@brendanlong now that #463 is merged, does that new option fit your usecase?
