### ISSUE TITLE
If then else formatting

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ocamlformat#504]
Currently the following code:
```ocaml
let _ =
  if condition then
    let a = 1 in
    let b = 2 in
    a + b
  else if other_condition then
    12
  else
    0
```
is either formatted as:
```ocaml
let _ =
  if condition then
    let a = 1 in
    let b = 2 in
    a + b
  else if other_condition then 12
  else 0
```
or, if `if-then-else=keyword-first`, as:
```ocaml
let _ =
  if condition
  then
    let a = 1 in
    let b = 2 in
    a + b
  else if other_condition
  then 12
  else 0
```
What troubles me the most here is the fact that expressions that wraps are treated differently from expressions that don't.

Internally we always format it as in the original example, the main reasons are:
1. It is more consistent as you don't have expressions on their own line with their own indentation level and expressions "hidden" after a keyword mixed in the same conditional expression.
2. It is more line-diff friendly when expressions get longer.
3. it's (probably subjectively) more legible to separate the conditions and the keywords from the corresponding expressions as they then have different indentation levels.

I would love to have a configuration option in `ocamlformat` that would let me format conditionals that way.
I think it should be independent from the option configuring whether `if-then-else` should always break or be written on a single line if possible (so should `keyword-first` if you ask me) and be part of an option that describe how `if-then-else` should be formatted when they wrap.
Also to clarify my ideal behaviour here, I'd like this formatting to apply to all wrapping conditional expressions ie I'd like this:
```ocaml
let _ =
  if condition_1 then 1
  else if condition_2 then 2
  else 3
```
to be formatted as:
```ocaml
let _ =
  if condition_1 then
    1
  else if condition_2 then
    2
  else
    3
```
mostly on the account of 2. and 3.

Do these concerns seem sensible to you ? Would you be open to splitting `if-then-else` into several options and to have such formatting in `ocamlformat` ?

If so, I'm as I always happy to contribute!

**Comment by jberdine** [comment]
This is related to #358. I think that it is a common desire to synchronize the breaking of the arms of conditional expressions. There are degrees, e.g. if all arms are short, it may be preferably to put them on the same line as their conditions, so it may make sense to leave options for that. But in particular having the ability to produce code in the style of your first example would be good. I expect that your very last example is too sparse for many. One smooth progression could be:
```
if cond1 then arm1 else if cond2 then arm2 else arm3
```
if it all fits on a line, then
```
if cond1 then arm1
else if cond2 then arm2
else arm3
```
if it doesn't, and then
```
if cond1 then
  arm1
else if cond2 then
  arm2
else
  arm3
```
if one of the arms hits the margin.

More configurability would be possible, e.g. an option to skip the first form if there are nested if-then-else expressions, or an option to skip the second form and go straight to the third one.

This may be involved to implement. And care will need to be taken to handle the cases where the conditions themselves break.

**Comment by NathanReb** [comment]
I think the current default behaviour regarding conditions is good and would still apply.
Ie:
```ocaml
let _ =
  if
    some_long_property_that_will_wrap applied_to some_variables_with_long_names
  then
    let a = 10 in
    a + 2
  else
    let b = 11 in
    b - 11
```
Note that in `keyword-first` mode though, it gets formatted as:
```ocaml
let _ =
  if some_long_property_that_will_wrap applied_to
       some_variables_with_long_names
  then
    let a = 10 in
    a + 2
  else
    let b = 11 in
    b - 11
```
which might be a bug since I don't see why it would format differently.

**Comment by NathanReb** [comment]
Ok so I'm trying to wrap my head around all this.

Let's number the different breaking options you mentionned 1, 2 and 3 by order of appearance for future reference.

Am I correct saying that:
1. they should not be mixed (ie no combination of `2` and `3` for different arms of the same conditional expression)
2. they all have a `keyword-first` equivalent, ie `1` stays the same and for `2` and `3` you insert a break before `then` keywords, meaning a separate option `break-if-then-else` would make sense.
3. assuming my two previous assumptions are correct, 3 values for `break-if-then-else` would cover all acceptable cases.  Something like `compact,arms,all` where `compact` uses as little vertical space as possible as you described ie `1` if possible, else `2` if possible, else `3`, `arms` goes straight to `2` and breaks to `3` when necessary, `all` goes straight to `3`.

**Comment by NathanReb** [comment]
I forgot to mention it above but I assume the ocaml guidelines style is independent from breaking, and could be configured from the same option as `keyword-first`.

Am I right there as well?

**Comment by gpetiot** [comment]
@NathanReb I will have a look at this but I can't promise you it will be ready for 0.9 (it shouldn't delay the release)

**Comment by NathanReb** [comment]
Ok thanks! I'm happy to help and try to provide a PR for this. Can work on that today if that helps!

**Comment by jberdine** [comment]
I'd suggest to start by thinking about what nested tree of boxes structure to place the parsetree nodes into which will lead to the code layout you want. It's hard not to get lost in code complexity without first having a reasonably clear idea of that aspect. Happy to see and discuss proposals here.

**Comment by gpetiot** [comment]
I think we can close this one now.
