### ISSUE TITLE
Incorrect indent of anonymous functions

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#505]
The indentation should increase of 2 spaces instead of 4:
```
let _ =
  List.fold_map fields ~init:c ~f:(fun c i ->
      let c =
        match i.pcf_desc with
        | Pcf_attribute atr -> update_config c [atr]
        | _ -> c
      in
      (c, (i, c)) )
```

**Comment by jberdine** [comment]
No, 4 is intended. Otherwise the body changes indent when the `fun` doesn't fit on the first line.

**Comment by jberdine** [comment]
I mean, there could certainly be an option, but the current behavior is not "incorrect".

**Comment by trefis** [comment]
IIUC https://github.com/ocaml/ocaml/pull/8719 would fix the issue (indent of 2 for the body when fun fits on the first line, indent of 2 for fun and 4 for the body otherwise).

I vote for reopening this issue!

**Comment by trefis** [comment]
Oh, but apparently #841 already makes use of that feature.
I think it would be interesting to see what happens when the `fun` doesn't fit on the first line indeed. I'll submit a PR extending the test.
