### ISSUE TITLE
Keyword 'with' on a line by itself

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#507]
Currently when the whole `match`/`try` expression does not fit on one line, we try to fit the `with` expression on a single line:
```
let _ =
  match foooooooooooooooooooo oooooooooooooooooooooooooo ooooooooooooooo
  with foo -> bar
```
Another option would be to write `with` on a line by itself (cf  [Guidelines](https://ocaml.org/learn/tutorials/guidelines.html)):
```
let _ =
  match foooooooooooooooooooo oooooooooooooooooooooooooo ooooooooooooooo
  with
  | foo -> bar
```

**Comment by jberdine** [comment]
Is this still relevant after #552?

**Comment by gpetiot** [comment]
Yes, #552 does not put `with` "alone" on its line when the whole expression does not fit on a single line.
