### ISSUE TITLE
Long indentation on comment after pattern match body

### ISSUE THREAD

**Issue by copy** [ocaml-ppx/ocamlformat#522]
This example looks unnatural to me:

```ocaml
;;
match x with XXXXXXXXXXXXXXXXXXXXXXXXXX -> (* *)
                                           x
```

Related: https://github.com/ocaml-ppx/ocamlformat/issues/341#issuecomment-423521961

**Comment by jberdine** [comment]
Yes, this is suboptimal. In this case the comment was determined to be associated with the following `x`.  If that is logically the right thing to do (it would be useful to know if that is true in you real example), then there should probably be a line break after the `->`. There could be a lot of undesirable collateral damage of such a change done simply though. It will have to be checked.

**Comment by copy** [comment]
> it would be useful to know if that is true in you real example

Yes, in my real code the comment is attached to the following `x` and a line break after the `->` would have been my choice.

**Comment by jberdine** [comment]
Should be fixed now, please re-open if not.
