### ISSUE TITLE
Inconsistent spacing on | in match blocks

### ISSUE THREAD

**Issue by Wilfred** [ocaml-ppx/ocamlformat#544]
Given the code:

```ocaml
module Scope = struct
  let rec rx_of_scope scope =
    match scope with
    | []
    | ScopeItem.Class _ :: _ ->
      Rx.NonRx
    | ScopeItem.Lambda (_, Some rx_level) :: _
    | ScopeItem.LongLambda (_, _, Some rx_level) :: _ ->
      rx_level
    | ScopeItem.Lambda (_, None) :: rest
    | ScopeItem.LongLambda (_, _, None) :: rest ->
      rx_of_scope rest
    | ScopeItem.Method { Ast.m_user_attributes = attrs; _ } :: _
    | ScopeItem.Function { Ast.f_user_attributes = attrs; _ } :: _ ->
      Rx.rx_level_from_ast attrs |> Option.value ~default:Rx.NonRx
end
```

ocamlformat (master at 04f73e2c165fdf0d8d04179935dca41d8dea14d8, default options) produces:

```ocaml
module Scope = struct
  let rec rx_of_scope scope =
    match scope with
    | [] | ScopeItem.Class _ :: _ -> Rx.NonRx
    | ScopeItem.Lambda (_, Some rx_level) :: _
     |ScopeItem.LongLambda (_, _, Some rx_level) :: _ ->
        rx_level
    | ScopeItem.Lambda (_, None) :: rest
     |ScopeItem.LongLambda (_, _, None) :: rest ->
        rx_of_scope rest
    | ScopeItem.Method {Ast.m_user_attributes= attrs; _} :: _
     |ScopeItem.Function {Ast.f_user_attributes= attrs; _} :: _ ->
        Rx.rx_level_from_ast attrs |> Option.value ~default:Rx.NonRx
end
```

I don't understand why `|` is sometimes formatted with a trailing space, but sometimes isn't.

**Comment by Wilfred** [comment]
Simple example. Before:

```ocaml
let is_prim = function
  | "HH\\void" | "HH\\int"
  | "HH\\bool" | "HH\\float"
  | "HH\\string" | "HH\\resource"
  | "HH\\num" | "HH\\noreturn"
  | "HH\\arraykey" | "HH\\mixed"
  | "HH\\nonnull" | "HH\\null" -> true
  | _ -> false
```

After:

```ocaml
let is_prim = function
  | "HH\\void" | "HH\\int" | "HH\\bool" | "HH\\float" | "HH\\string"
   |"HH\\resource" | "HH\\num" | "HH\\noreturn" | "HH\\arraykey"
   |"HH\\mixed" | "HH\\nonnull" | "HH\\null" ->
      true
  | _ -> false
```

**Comment by hcarty** [comment]
IIRC, the no-space-after-`|` formatting is meant to quickly show a reader that there are grouped match cases split across lines.

**Comment by jberdine** [comment]
Yes. In particular, if you had had code such as:
```ocaml
let is_prim = function
  | "HH\\void" | "HH\\int" | "HH\\bool" | "HH\\float" -> false
  | "HH\\resource" | "HH\\num" | "HH\\noreturn" | "HH\\arraykey"
   |"HH\\mixed" | "HH\\nonnull" | "HH\\null" ->
      true
  | _ -> false
```
then the change in the indentation of `| ` vs ` |` would indicate that there is a short body of a nested or-pattern that could be easily missed if formatted as:
```ocaml
let is_prim = function
  | "HH\\void" | "HH\\int" | "HH\\bool" | "HH\\float" -> false
  | "HH\\resource" | "HH\\num" | "HH\\noreturn" | "HH\\arraykey"
  | "HH\\mixed" | "HH\\nonnull" | "HH\\null" ->
      true
  | _ -> false
```
This can be disabled using `indicate-nested-or-patterns=false` if you're happy with the risk. Alternatively, `break-cases=nested` can be used to break after the `->` to avoid the risk at the cost of significantly less compact code.

I'm thinking that this point is FAQ-worthy.

**Comment by Wilfred** [comment]
@jberdine Ooh, clever! Thanks, I didn't know that option existed.

It would be a huge help to have this in an FAQ. I didn't know about this option. I can't see it in `ocamlformat --help`, is that intentional?

Doing `ocamlformat -c indicate-nested-or-patterns=false my_file.ml` does indeed do what I want.

**Comment by Wilfred** [comment]
@gpetiot Perhaps add some docs for this issue, and then close it? I don't feel strongly :)

**Comment by jberdine** [comment]
Added an umbrella issue on moving various discussion of this kind to somewhere central, so closing this.
