### ISSUE TITLE
Closing bracket pushed back on a new line

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#547]
Alternative style for records (used in `dune`) where the closing bracket is pushed back on a new line :
```ocaml
type pps =
    { loc : Loc.t
    ; pps : (Loc.t * Lib_name.t) list
    ; flags : string list
    ; staged : bool
    }
```
Maybe this could be added to the `break-separators` option?

**Comment by jberdine** [comment]
Is this intended for only type definitions, or all types, or types and expressions?

I wonder if there are other stylistic points that involve spending a line just on punctuation, and if they ought to be combined instead?

**Comment by gpetiot** [comment]
From what I've seen on the dune repository it is intended for types and expressions, records and lists (didn't see any arrays but I don't see why it wouldn't be the case).
cc @emillon

**Comment by emillon** [comment]
Yes, that's the case in all expressions, e.g.

```
( a
, b
, c
)

[ x
; y
; z
]
```

This pattern is common in Haskell and present in many OCaml code bases.

**Comment by jberdine** [comment]
What about other embraced expression forms, such as:
```ocaml
List.map xs ~f:(fun x ->
    ...)
```
vs
```ocaml
List.map xs ~f:(fun x ->
    ...
  )
```
Do you think people conflate wanting the closing delimiters on their own line in these case and the "collection" expressions discussed above?

**Comment by jberdine** [comment]
Ok, it seems that a separate option for closing delimiters other than collection expressions is likely needed.

My understanding is that this option only makes sense for `break-delimiters=before`, right? In that case, adding another value to `break-delimiters` seems the right plan.

Cc: @mbarbin: this is something that you brought up I think.

**Comment by emillon** [comment]
Do you mean `break-separators`? Yes, I think that it corresponds to a new value `before-and-something`, but I'm not sure what kind of syntax this option affects besides type declarations.

**Comment by jberdine** [comment]
Yes, sorry, `break-separators` (edited). It also affects the position of `->` in multiline function types, but that is probably not a problem.

**Comment by mbarbin** [comment]
> What about other embraced expression forms, such as:
> 
> ```ocaml
> List.map xs ~f:(fun x ->
>     ...)
> ```
> 
> vs
> 
> ```ocaml
> List.map xs ~f:(fun x ->
>     ...
>   )
> ```
> 
> Do you think people conflate wanting the closing delimiters on their own line in these case and the "collection" expressions discussed above?

I wouldn't feel comfortable merging too many such choices into one toggle, because I have witnessed first hand discussions in which programmers have rationale for defending "inconsistent" choices for those different cases.  I think having multiple toggles for the records, let-in (#562), the parens, etc. seems appealing to me at that time and seems to be a way to help reducing design paralysis.

**Comment by Julow** [comment]
The `space-around-collection-expressions` option already does this. I'm currently working on the handling of this option in polymorphic variants:

```
[@@@ocamlformat "type-decl=sparse"]
[@@@ocamlformat "space-around-collection-expressions"]

type t =
  { x: int
  ; y: int
  }

type t =
  [ `X
  | `Y ]
```

I don't think using the `break-separators` for this is a good idea. In the context of types, I would like to tweak brackets, `;` separators and `|` separators separately.

Also, the `after-and-docked` case only work for records and there is no option to "dock" brackets of polymorphic variants (`before-and-docked` ?).

**Comment by hhugo** [comment]
related https://github.com/ocaml-ppx/ocamlformat/issues/653

**Comment by gpetiot** [comment]
I think we can close this one.
