### ISSUE TITLE
Switch the default value of --doc-comments from after to before

### ISSUE THREAD

**Issue by mrmr1993** [ocaml-ppx/ocamlformat#556]
To avoid confusing type comments with constructor comments, type comments are always placed before the type definition:

```ocaml
(** Your comment on [t] here *)
type 'a t = Some of 'a | None (** Your comment on [None] here *)
```

but the default value for doc comments on values is after:

```ocaml
let f x y = x + y
(** Your comment on [f] here *)
```

It would be much nicer for comments to have a consistent position across the different structure item types.

Since the type comment can't be moved, I would like to propose changing the default to `--doc-comments=before`.

**Comment by jberdine** [comment]
Note that by default docstrings on values in structures come before the definition, and docstrings on types in structures and signatures come before the definition, while docstrings on value declarations in signatures come after the declaration. So there are several dimensions that could be chosen if consistency along one of them was taken as the main objective.

FWIW, the reasoning behind the current defaults is that definitions are often longer than their docstrings, while declarations are often shorter. Additionally, docstrings on value declarations often make more sense when read in the context of knowing the type of the value. This is less prevalent for type definition since the explanations that benefit from the context of the type definition are often in the docstrings for individual constructors or fields, which come after their types.

**Comment by mrmr1993** [comment]
Thanks for explaining.

Perhaps I have misunderstood, but it seems that we still don't have dimensions to choose among if we want consistency: doc-comments still have to go before type definitions/declarations.

Since the mental load of the inconsistency is something we can practically fix, but the 'types before comments' isn't (for value definitions), it still seems we should switch to `--doc-comments=before` by default.

**Comment by jberdine** [comment]
If you want to add an option to place the docstrings after type definitions, it should be possible. The complication is that you will need to ensure that there is no ambiguity between the docstring for the entire definition and that for the final constructor/other item. The way to resolve such ambiguity is to add an empty docstring to the final item. Another option could be to place the docstring before in cases that lead to such ambiguity, but it is unclear whether it would be more surprising to people to have the formatter seemingly randomly put some docstrings before, or to insert empty docstrings.

Re "the mental load of the inconsistency", to be useful we need concrete examples of what you mean here. Appreciate that nearly every option could be set either way, or else they wouldn't exist, and there are many perspectives and different code bases. What distinguishes this notion of consistency from choosing one of several ways in which code can be made to superficially look more similar? In general, such forms of consistency are non-goals. In this particular case, it would be useful to have something more along the lines of an argument that generally it is better to read the docstring for a value prior to reading its type.

**Comment by gpetiot** [comment]
So we could split `--doc-comments` into `--doc-comments-values` and `--doc-comments-types`, would that work for you @mrmr1993 ? FWIW this feature is one of the things users complain the least about so I don't think the default value should change, #560 has very low chance of being merged.

**Comment by mrmr1993** [comment]
> would that work for you @mrmr1993 ?

Not really; I have an issue with the default position of the value doc comments, not with the ability to move the type doc comments.

To be more concrete, I find it slower and more difficult to find the appropriate doc comment for a value when the comments are 'jumping about':

```ocaml
(** Option type *)
type 'a option = Some of 'a | None

val some : 'a -> 'a option
(** Function version of [Some] *)

(** Another type *)
type t = A of int * int * bool | B of * int * bool | C of bool

val a : int -> int -> bool -> t
(** Function version of [A] *)

val b : int -> bool -> t
(** Function version of [B] *)

val c : bool -> t
(** Function version of [C] *)

(** Wrapper around t *)
type s = D of t

val d : t -> s
(** Function version of [D] *)
```

as opposed to being in a consistent position:
```ocaml
(** Option type *)
type 'a option = Some of 'a | None

(** Function version of [Some] *)
val some : 'a -> 'a option

(** Another type *)
type t = A of int * int * bool | B of * int * bool | C of bool

(** Function version of [A] *)
val a : int -> int -> bool -> t

(** Function version of [B] *)
val b : int -> int -> bool -> t

(** Function version of [C] *)
val c : bool -> t

(** Wrapper around t *)
type s = D of t

(** Function version of [D] *)
val d : t -> s
```
