### ISSUE TITLE
Kill Emacs buffers open by ocamlformat once formating is  done

### ISSUE THREAD

**Issue by ludwigpacifici** [ocaml-ppx/ocamlformat#557]
**Reproduce issue**
1. Open Emacs with an Ocaml file.
2. `C-x C-b` and check there are no buffer opened by ocamlformat. For information, an opened buffer should show a line similar to:
```
ocamlformatg4iM...      2705 Tuareg           /tmp/ocamlformatg4iMVt.ml
``` 
3. I modify the file then `M-x ocamlformat` to trigger the formatter (cf. Emacs configuration below).
4. `C-x C-b` again and check there is a new open buffer by ocamlformat.
5. Repeat steps 3 and 4 to see additional buffers opened.

Actual behavior: after running `ocamlformat` a new buffer is left opened.
Expected behavior: after running `ocamlformat` **no** new buffer is opened.

**Environment**

* ocamlformat version: `0.8`
* Emacs version `GNU Emacs 27.0.50`
* ocamlformat Emacs configuration: 
```elisp
(require 'ocamlformat)
```

PS: [reformatter.el](https://github.com/purcell/reformatter.el) was released recently by an Emacs maintainer, it might be interesting for ease of integration.

Edit: After some debugging, looks like there is a missing call to `kill-buffer` at the end of `ocamlformat` function in `ocamlformat.el` file. Let me know if you want me to create a PR.

**Comment by jberdine** [comment]
FYI I can't repro this, with current ocamlformat and emacs 26.1. Perhaps there is a difference in behavior between emacs 26.1 and 27? Either way, it would be great if you could write a PR.

I looked briefly at reformatter.el. Is your understanding that all the current functionality of ocamlformat.el could be reimplemented in terms of reformatter.el?

**Comment by hhugo** [comment]
The difference in behavior could come from https://github.com/ocaml-ppx/ocamlformat/pull/345

**Comment by ludwigpacifici** [comment]
> FYI I can't repro this, with current ocamlformat and emacs 26.1. Perhaps there is a difference in behavior between emacs 26.1 and 27? Either way, it would be great if you could write a PR.

Yes, very likely to be a difference between Emacs 26.1 and 27. With the following to versions:

 * `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.3) of 2019-01-20` has bad behavior
 * `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05` has good behavior.

Now, looking at #345, especially the value of [ocamlformat.el#L176](https://github.com/ocaml-ppx/ocamlformat/blob/master/emacs/ocamlformat.el#L176), there is a difference of behavior between the two Emacs versions:

* 27.0.50 is evaluated to `t`
* 26.1 is evaluated to to `nil`

With Emacs 27, if I force to use the else of [ocamlformat.el#L243](https://github.com/ocaml-ppx/ocamlformat/blob/master/emacs/ocamlformat.el#L243), i.e. use `ocamlformat--patch-buffer`, then there is no issue.

`ocamlformat--patch-buffer` calls `kill-buffer`. On the other hand, `replace-buffer-contents` seems to require a `kill-buffer` afterwards. From the doc:

```
replace-buffer-contents
...
As far as possible the replacement is non-destructive, i.e. existing
buffer contents, markers, properties, and overlays in the current
buffer stay intact.
Warning: this function can be slow if there’s a large number of small
differences between the two buffers.
```

Let me know what you think. If you are happy with that, I'll send a PR.

> I looked briefly at reformatter.el. Is your understanding that all the current functionality of ocamlformat.el could be reimplemented in terms of reformatter.el?

Yes, I believe so. reformatter.el looks handy. Would you be interested with the result if I try to use it with ocamlformat?

**Comment by jberdine** [comment]
Thanks a lot for the investigation! It does seem like a call to `kill-buffer` needs to be added. It would be great if you could send a PR!

For reformatter.el, it is preserving the options for error display and margin setting that I was immediately unsure of. But I would definitely welcome using existing code for what we can, presuming that reformatter.el is easily available widely / essentially to everyone. I'd rather not get into vendoring in  GPL code.
