### ISSUE TITLE
ocamlformat-diff installation

### ISSUE THREAD

**Issue by giltho** [ocaml-ppx/ocamlformat#558]
Hello,
I installed `ocamlformat` and wanted to use its integrated difftool. The documentation about how to set that up with git is quite well written, except that I get the following error message : `ocamlformat-diff: command not found`

Shouldn't `ocamlformat-diff` be installed as part of the `ocamlformat` package ? I haven't been able to find that information.

I'd be happy to help and improve the documentation on that point if there are additional steps to go through.

Thanks !

**Comment by hhugo** [comment]
Ocamlformat-diff is not yet part of an official release. Using the version on master should do it. `opam pin add ocamlformat - - dev`

**Comment by giltho** [comment]
That explains it, thank you very much !!
