### ISSUE TITLE
Syntax sugar for ppx

### ISSUE THREAD

**Issue by bobbypriambodo** [ocaml-ppx/ocamlformat#56]
Follow up to Josh's comment [here](https://discuss.ocaml.org/t/ppx-aesthetics-discussion/1248/12), ocamlformat currently desugars ppx syntax:

```ocaml
let _ =
  let%lwt foo = Lwt.return 1 in
  Lwt.return_unit
```

becomes

```ocaml
let _ =
  [%lwt
    let foo = Lwt.return 1 in
    Lwt.return_unit]
```

Which becomes even weirder with multiple ppx usages in a row:

```ocaml
let _ =
  let%lwt foo = Lwt.return 1 in
  let%lwt bar = Lwt.return 1 in
  let%lwt baz = Lwt.return 1 in
  Lwt.return_unit
```

becomes

```ocaml
let _ =
  [%lwt
    let foo = Lwt.return 1 in
    [%lwt
      let bar = Lwt.return 1 in
      [%lwt
        let baz = Lwt.return 1 in
        Lwt.return_unit]]]
```

(`ocamlformat --version == v0.2`)

The expected behavior is that the syntactic sugar remains unchanged.

**Comment by hcarty** [comment]
Thank you!
