### ISSUE TITLE
should ocamlformat try to parse files when explicity disabled ?

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#564]
I'm using an `.ocamlformat` file with just `disable` in it to disable ocamlformat entirely in a directory.
When using `dune build @fmt`, dune will call ocamlformat on every files and do nothing (which is good)

However, if one of the file (that is not supposed to be formatted) is not valid according to ocamlformat, `dune build @fmt` will error out.

Here is a trace on the js_of_ocaml codebase.
```
$ cat benchmarks/.ocamlformat 
disable
```
```
$ dune build @benchmarks/fmt
 ocamlformat benchmarks/.formatted/report.ml (exit 1)
(cd _build/default/benchmarks && ocamlformat --impl report.ml --name ../../../benchmarks/report.ml -o .formatted/report.ml)
ocamlformat: ignoring "../../../benchmarks/report.ml" (syntax error)
File "../../../benchmarks/report.ml", line 1, characters 0-2:
Error: Syntax error
 ocamlformat benchmarks/.formatted/run.ml (exit 1)
(cd _build/default/benchmarks && ocamlformat --impl run.ml --name ../../../benchmarks/run.ml -o .formatted/run.ml)
ocamlformat: ignoring "../../../benchmarks/run.ml" (syntax error)
File "../../../benchmarks/run.ml", line 1, characters 0-2:
Error: Syntax error
EXIT STATUS 1
```
```
$ ocamlformat benchmarks/report.ml  --print-config > /dev/null
sequence-style=terminator (.ocamlformat:1)
margin=90 (.ocamlformat:2)
if-then-else=keyword-first (.ocamlformat:3)
infix-precedence=parens (.ocamlformat:4)
parens-tuple=multi-line-only (.ocamlformat:5)
type-decl=sparse (.ocamlformat:6)
break-collection-expressions=fit-or-vertical (.ocamlformat:7)
break-infix=fit-or-vertical (.ocamlformat:8)
break-struct=force (.ocamlformat:9)
field-space=loose (.ocamlformat:10)
wrap-fun-args=false (.ocamlformat:11)
wrap-comments=false (.ocamlformat:12)
disable=true (benchmarks/.ocamlformat:1)
ocamlformat: ignoring "benchmarks/report.ml" (syntax error)
File "benchmarks/report.ml", line 1, characters 0-2:
Error: Syntax error
EXIT STATUS 1
```
I'm not sure if a solution should come from `dune` or `ocamlformat` ..
cc @diml @rgrinberg

**Comment by jberdine** [comment]
Indeed, ocamlformat tries to parse the input file prior to checking if formatting is completely disabled. That is not useful, and probably not the right thing to do.

Independently, dune could optimize the process by not forking an ocamlformat process for each file, but I don't know how much dune ought to get into looking at the ocamlformat config.

**Comment by jberdine** [comment]
Note that if ocamlformat is passed `-o`, then even when formatting is disabled, it should copy the input into the specified output file.
