### ISSUE TITLE
Issues preventing Janestreet adoption

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#569]
This is some issues that are blocking Janestreet adoption of Ocamlformat

# ~Or patterns on the same line~

Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/536

# ~Non-doc comments in record definitions~

Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/580

# ~Extra space before doc comments in record definitions~

Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/575

# Inconsistent break before module signature when there is constraint

Issue: https://github.com/ocaml-ppx/ocamlformat/issues/572

# ~Missing break before closing bracket of polymorphic variants~

Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/583

# Type annotation on first-class modules

Issue: https://github.com/ocaml-ppx/ocamlformat/issues/629

# Configure strategies for breaking long functions declarations

Issue: https://github.com/ocaml-ppx/ocamlformat/issues/626

# Keep tag-only doc comments on the same line

Issue: https://github.com/ocaml-ppx/ocamlformat/issues/627

# Break before multi-line expression in `let module X =` body

Issue: https://github.com/ocaml-ppx/ocamlformat/issues/628

# Extra break in first-class module syntax

~Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/585~

# ~Extra break in module pack type~

Pull request: https://github.com/ocaml-ppx/ocamlformat/pull/600

**Comment by jberdine** [comment]
It would be good to separate these into individual issues so that we can discuss and track progress.

**Comment by Julow** [comment]
Splitted.
