### ISSUE TITLE
Inconsistent break before module signature when there is constraint

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#572]
When `with type ...` constraints are present, an extra break is added before the `sig`

```
module O :
  sig
	type t
  end
  with type t := t = struct end
```

Without constraints:

```
module O : sig
  type t
end = struct end
```

**Comment by jberdine** [comment]
So the desired output is:
```
module O : sig
    type t
  end
  with type t := t
= struct end
```
or something else?

**Comment by Julow** [comment]
I think it is
```
module O : sig
  type t
end
with type t := t = struct end
```

Yes, the last line is hard to read. Is there currently a cases where the `=` is on the beginning of a line ?

**Comment by jberdine** [comment]
I think we need to consider the general case where the struct is non-empty:
```
module O : sig
  type t
end
with type t := t = struct
  let () = ()
end
```
Formatting it as above leads readers to consider the `let` to somehow be inside the `with type`, which is wrong, hence the alternative:
```
module O : sig
  type t
end
with type t := t
= struct
  let () = ()
end
```
Perhaps
```
module O : sig
  type t
end
with type t := t =
struct
  let () = ()
end
```
would also work, but might get strange when the constraints get more complex:
```
module O : sig
  type t
end
with type t := t
 and type s := s =
struct
  let () = ()
end
```
But this seems no worse than the analogous situation with function args.

In all of these, it is a bit incongruous with the rest of the formatting to allow the `with` to not be indented from the `module`, but maybe that is ok.

Starting a line with `=` is uncommon, but can happen for let bindings with args of just the right length.
