### ISSUE TITLE
option -pp ?

### ISSUE THREAD

**Issue by houndofsound** [ocaml-ppx/ocamlformat#588]
hello folks,

I just went to use ocamlformat to turn my modified language parsetree back to standard,
and found there was no -pp pre-processor option. shock... horror!

there's a feature request then :)
or would you accept a PR from me? (first timer!)

**Comment by hhugo** [comment]
By `-pp`, you mean a pre-processor from source to source, behaving more or less like:  
`mypp input.ml | ocamlformat --name input.ml -`
 ?

**Comment by hhugo** [comment]
I don't understand what you mean by `your format didn't work for me!`.

What format is your preprocessor reading ? what does it emit ? regular ocaml ?

**Comment by houndofsound** [comment]
"mypp input.ml | ocamlformat --name input.ml -"

is a format!

I took you to mean ocamlformat already handled input from a -pp preprocessor
and tried it out.
since it didn't work for me I have some doubt that you meant that after all!

the preprocesser I am running works with [ocamlc -pp].

**Comment by houndofsound** [comment]
it's output is a serialisation of the parsetree constructor type
together with magic numbers etc.

**Comment by houndofsound** [comment]
sorry - I remember now that -pp doesn't have to be a serialisation at all....

**Comment by hhugo** [comment]
The ocaml parsetree does not include comments. To implementing your feature request, we would have to drop comments on the floor.

Ocamlformat can format Reason code to ocaml (https://github.com/ocaml-ppx/ocamlformat#reason). You might be able to leverage that code path after tuning your preprocessor to emit the same format as Reason.

**Comment by houndofsound** [comment]
ok, so you're using your own AST.
do you think the conversion from Parsetree to your AST (modulo
comments) would be straightforward?
with such a thing available would you consider adding the feature?
even with the comment-related facilities of ocamlformat put aside,
getting formatted code is a huge win.

but perhaps it would tie ocamlformat to the compiler too closely.
maybe it is better as a job for the compiler, to spit out a
simple-minded rendering of the parsetree, and keep source-code
processors independent.
....

**Comment by hhugo** [comment]
This is not what I said.
Ocamlformat uses the parsetree from the compiler internally (or for translating back from reason). I'm saying that the parsetree alone is not enough to preserve the comments.

**Comment by houndofsound** [comment]
pprintast is ideal - I never knew about it.
thank you

**Comment by gpetiot** [comment]
Let me know if we can close this issue.

**Comment by houndofsound** [comment]
certainly
