### ISSUE TITLE
Extension point ppx syntax sugar for match, try, if, for, while

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#59]
Similar to #56 it would be nice to have `keyword%ext` support for other keywords.  Lwt's ppx, for example, benefits from `match%lwt`, `try%lwt`, `if%lwt`, `for%lwt` and `while%lwt`.

**Comment by jberdine** [comment]
I see, good point. Actually, in general the short form should probably be generated for all cases where `ext_attributes` appears in [parser.mly](https://github.com/ocaml/ocaml/blob/trunk/parsing/parser.mly).

**Comment by jberdine** [comment]
Shall we close this now that #63 has been merged?

**Comment by hcarty** [comment]
Yes, thanks!
