### ISSUE TITLE
Replace break-cases=all with break-cases=toplevel ?

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#597]
(not for 0.9)

The option `break-cases=toplevel` introduced in #536 is a variant of `break-cases=all` where or-patterns are kept on the same line whenever possible.
`break-cases=all` is kept for ocamlformat 0.9 but we could replace it with `toplevel` for the major release.

Any thoughts on this?

**Comment by jberdine** [comment]
Let's remove `break-cases=all` in 0.10 and see how loud the complaints are.

**Comment by gpetiot** [comment]
Maybe we can modify `break-cases=all` so that it is equivalent to `break-cases=toplevel`with [Hugo's patch](https://github.com/janestreet/ocamlformat/commit/a6af924d9bf4184b7c64d697824f4d51d8bd6a29)? (breaking the or-patterns)
