### ISSUE TITLE
Syntax failure on type annotation

### ISSUE THREAD

**Issue by leviroth** [ocaml-ppx/ocamlformat#60]
Code:

```ocaml
let x : unit = ()
```

Running `ocamlformat foo.ml --inplace` results in `Error: Syntax error`.

The intermediate file looks like this:

```ocaml
let x : . unit : unit = ()
```

Version: 0.2
OCaml: 4.06.0
OS: Reproduced on Windows and Ubuntu

**Comment by jberdine** [comment]
This seems to be fixed in 0.3. Please re-open if you can still repro this with 0.3.
