### ISSUE TITLE
Ignore files based on .ocamlformat or .ocamlformat-ignore file ?

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#605]
https://github.com/ocaml/dune/issues/1793

**Comment by jberdine** [comment]
How much flexibility in terms of how many ignore files and where they are do you think would be needed? Would it suffice to have just one in the project root? Would a list of paths relative to the project root be enough, or are globs or regexps needed?

**Comment by hhugo** [comment]
Explicit filename, no regexp. either at the root or in sub-directories.
I'm not sure if it should live in ocamlformat or dune.

The use case is:
- use dune+ocamlformat to format the js_of_ocaml codebase
- some generated files (parsers, lexers) are committed in the tree but should not be reformatted.

**Comment by jberdine** [comment]
Internally we have makefiles that call `find` with various filters to select the files to be formatted and exclude others, so I think that the use case is reasonably general. It would be unfortunate for people to have to configure things twice, once for dune and once for the other invocations of ocamlformat. So unless we envision that people will only run ocamlformat via dune, then I think it makes sense to have support in ocamlformat. (FWIW, internally we do run ocamlformat from machines that do not have dune. I don't know whether to expect that to be common.) Also, if it is configured only in dune, how can we expect the editor integrations to do the right thing when an ignored file is edited and saved? On the other hand, it's nice to have fewer config files.
