### ISSUE TITLE
"Syntax error" on recursive signature definitions

### ISSUE THREAD

**Issue by grievejia** [ocaml-ppx/ocamlformat#61]
Simplified repro (test.mli):
```ocaml
module rec A : sig
  type t =
    | AA of B.t
end
and B : sig
  type t =
    | BB of A.t
end
```
Running `ocamlformat test.mli` results in `Error: Syntax error`.
The intermediate file looks like this:
```ocaml
module rec A : sig
  type t = AA of B.t
end
and module rec B : sig
  type t = BB of A.t
end
```
There are extra words `module rec` after the `and` keyword.
Version: 0.3
OCaml: 4.06.0

**Comment by jberdine** [comment]
Thanks!
