### ISSUE TITLE
Comment placement regression in infix op applications

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#617]
#548 seems to have had some unfortunate effects on the placement of comments in infix op applications. Consider:
```ocaml
let () =
  xxxxxxxxxx
  || (* xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx *)
     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Before, this formatted to itself. After, it formats to:
```ocaml
let () =
  xxxxxxxxxx
  (* xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx *)
  || xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Note that the comment has moved from after the infix op to after it.

**Comment by gpetiot** [comment]
We can just revert #548 at this point.

**Comment by jberdine** [comment]
I don't think it is so bad as that. #548 improved many cases and avoids some really broken formatting.

This issue does not look like a problem with fiddly box nesting. Looking quickly at the code that sugars infix op applications, and formats the sugared form, it looks like it is a matter of not keeping the comments for arguments on the arguments, they instead get moved to the application.

**Comment by gpetiot** [comment]
I spent some time trying to fix this issue, but no success so far, the issue doesn't look like it comes from the sugaring though.
