### ISSUE TITLE
Version change 0.3 -> v0.2 considered upgrade by OPAM

### ISSUE THREAD

**Issue by bbc2** [ocaml-ppx/ocamlformat#62]
OPAM seems to consider v0.2 to be the latest version whereas 0.3 is installed:

```
> opam upgrade ocamlformat
  ...
  ↗  upgrade   ocamlformat           0.3 to v0.2    
  ...   
```

I'm using opam 2.0.0~beta5 but I guess it is the same with opam 1.2.

**Comment by jberdine** [comment]
Attempting to fix this with https://github.com/ocaml/opam-repository/pull/11191

**Comment by jberdine** [comment]
Should be fixed in opam now, please re-open if you still have trouble.
