### ISSUE TITLE
Strange indentation in function type with function arguments

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#622]
```
val abcdef :
     aaaaaaaaaaaaa
  -> bbbbbbbbbbbbbb
  -> ccccccccccc
  -> (   dddddddddd
      -> eeeeeeeeeeeee
      -> ffffffffffffffff
      -> gggggggggggggg
      -> hhhhhhhhhhhhhhhhhhhhhhh
      -> iiiiiiiiiiiiiiiiiiii
      -> jjjjjjjjjjjjjjjjjjjjjjjj)
  -> unit
```

Janestreet profile: The spaces after the opening `(` are not necessary and there is too much indentation.

**Comment by jberdine** [comment]
Just to check, my impression before was that vertical alignment of 
argument types was desired by JS. Removing the space after the `(` will 
break that alignment. Also, if that space is removed in the JS profile, 
it should probably be removed whether or not there is a paren.

Aligning from before rather than after the paren would be a fix across 
the board though.

**Comment by gpetiot** [comment]
I guess the expected output is:
```
val abcdef :
     aaaaaaaaaaaaa
  -> bbbbbbbbbbbbbb
  -> ccccccccccc
  -> (dddddddddd
   -> eeeeeeeeeeeee
   -> ffffffffffffffff
   -> gggggggggggggg
   -> hhhhhhhhhhhhhhhhhhhhhhh
   -> iiiiiiiiiiiiiiiiiiii
   -> jjjjjjjjjjjjjjjjjjjjjjjj)
  -> unit
```

or
```
val abcdef :
     aaaaaaaaaaaaa
  -> bbbbbbbbbbbbbb
  -> ccccccccccc
  -> ( dddddddddd
    -> eeeeeeeeeeeee
    -> ffffffffffffffff
    -> gggggggggggggg
    -> hhhhhhhhhhhhhhhhhhhhhhh
    -> iiiiiiiiiiiiiiiiiiii
    -> jjjjjjjjjjjjjjjjjjjjjjjj )
  -> unit
```

**Comment by jberdine** [comment]
I don't know, the negative indentation is unexpected to me, we tend not 
to do that and it creates lots of corner cases and is hard to get right. 
But expectations and opinions will vary. More objectively, it seems like 
not a bad idea to make a large distinction between the arguments of the 
argument function and the arguments of the function.

**Comment by Julow** [comment]
The example in the PR is with the default profile. Running it with `profile=janestreet` outputs the same indentation (except for the `:`).

**Comment by gpetiot** [comment]
Here is the output on master (with the janestreet profile):
```ocaml
val abcdef             
  :  aaaaaaaaaaaaa
  -> bbbbbbbbbbbbbb
  -> ccccccccccc
  -> (dddddddddd
      -> eeeeeeeeeeeee
      -> ffffffffffffffff
      -> gggggggggggggg
      -> hhhhhhhhhhhhhhhhhhhhhhh
      -> iiiiiiiiiiiiiiiiiiii
      -> jjjjjjjjjjjjjjjjjjjjjjjj)
  -> unit
```

**Comment by gpetiot** [comment]
Closing this one for now, feel free to re-open.
