### ISSUE TITLE
Comments on record fields

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#623]
https://github.com/ocaml-ppx/ocamlformat/pull/580 did not fix edge cases:

```
type t =
  { a :
      int option
      (* aaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbb cccccccccccccccccccccccccccc ddddddddddddddddd eeeee *)
  ; b : float
        (* aaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbb cccccccccccccccccccccccccccc ddddddddddddddddd eeeee *)
  }
```

That's because the first comment is "attached" to the type and the second to the label declaration.

A fix could be to "steal" the comment and attach it to the label declaration. [example](https://github.com/ocaml-ppx/ocamlformat/compare/master...Julow:break_comment_record_steal_comment_from_type#diff-3153f72c4aa078a76f6423aa0e574aa3)

**Comment by jberdine** [comment]
Maybe not helpful in the immediate term, but note that these comments 
really should just be docstrings and then they would format fine.
