### ISSUE TITLE
Type annotation on first-class modules

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#629]
This code:

```
let x : (module S) = (module struct end)
```

is rewritten as:
```
let x = (module struct end : S)
```

Extra parenthesis solve the problem:
```
let (x : (module S)) = (module struct end)
```

**Comment by gpetiot** [comment]
Looks related to https://caml.inria.fr/mantis/view.php?id=7758

**Comment by Julow** [comment]
@gpetiot Do you think we should preserve `let x = (module struct end : S)` or is it OK to format it as `let x : (module S) = (module struct end)` every time ?

**Comment by gpetiot** [comment]
I think that just like for #791 this is a case where it's okay to rely on the input to preserve the initial formatting.

**Comment by gpetiot** [comment]
Can be done after #812 to re-use the new functions.
