### ISSUE TITLE
Switch to OCaml 4.08 Ast ..

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#630]
.. once https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/50 is addressed.
 
Here is a non-exhaustive list of interesting changes for ocamlformat: 
1. GPR#1970: fix order of floatting documentation comments in classes  (makes the sorting unnecessary in https://github.com/ocaml-ppx/ocamlformat/blob/85cfc0f9a360e5cfe4268b1aacc364de7d65474a/src/Fmt_ast.ml#L2248 and https://github.com/ocaml-ppx/ocamlformat/blob/85cfc0f9a360e5cfe4268b1aacc364de7d65474a/src/Fmt_ast.ml#L2292). the sort could be implemented in migrate_parsetree when upgrading from 4.07 to 4.08.
2. GPR#1958: allow [module M(_:S) = struct end] syntax (one can lift the restriction on the underscore https://github.com/ocaml-ppx/ocamlformat/blob/85cfc0f9a360e5cfe4268b1aacc364de7d65474a/src/Sugar.ml#L280)
3. GPR#1960: The parser keeps previous location when relocating ast node. (should be able to help with https://github.com/ocaml-ppx/ocamlformat/blob/85cfc0f9a360e5cfe4268b1aacc364de7d65474a/src/Source.ml#L113)
4. GPR#1705: Allow @@attributes on exceptions. (we should be able to address https://github.com/ocaml-ppx/ocamlformat/blob/85cfc0f9a360e5cfe4268b1aacc364de7d65474a/src/Fmt_ast.ml#L3027)
5. GPR#1954: Add locations to toplevel directives
6. GRP#1953: Add locations to attributes in the parsetree.

**Comment by hhugo** [comment]
This makes me think that we might need a flag to specify the targeted version of the OCaml compiler.
For instance, it would be incorrect to use the following syntax in 4.07. 
`module M(_:S) = struct end`

**Comment by jberdine** [comment]
My position has always been to try to support the latest released version and the one preceding for "a while" to make it possible to upgrade non-atomically. That's not very generous, I know. But I'm not sure of the cost:value ratio for supporting old versions for dev tools, especially when they are so closely tied to compiler internals. Also, I don't know if it makes sense to commit/try to ensure that everyone can use the same compiler version to build ocamlformat as to build the code they are formatting. I'm definitely open to alternative, but just to say that I haven't already been convinced that something like dune's approach to legacy support is the right choice here.

For examples like the particular case of `module M(_:S) = struct end`, would it make more sense wrt community-wide effort to make a ppx that could be used with eg 407 that would convert the 408 ast to the expanded form that 407 can handle?

**Comment by hhugo** [comment]
@jberdine, let's move that discussion to a different issue.

**Comment by hhugo** [comment]
-> https://github.com/ocaml-ppx/ocamlformat/issues/633

**Comment by Armael** [comment]
Regarding 4.08 support (not necessarily using the AST, just building on 4.08):

I would like to know to which extent [this](https://github.com/ocaml-ppx/ocamlformat/blob/5821d9365f99778193328f38d54d4b2b575515a4/src/Translation_unit.ml#L88) is needed, and if it could be done differently.
This is related to ocaml-ppx/ocaml-migrate-parsetree#50: in ocaml 4.08 the name and type of this hook changed, and the `Location` module currently isn't snapshotted by omp. So this code won't work on ocaml 4.08. I'm wondering whether:
- this feature (overriding the warnings hook) is really needed; in which case we will have to come up with a "portable" API for this in omp (and implement it differently across versions -- this is fairly annoying but possible);
- this could be achieved differently on the ocamlformat side; in which case we wouldn't have to do anything on the omp side.

**Comment by hhugo** [comment]
The code you pointed out is needed to give better error messages (introduced in https://github.com/ocaml-ppx/ocamlformat/pull/243).
With the current interface of `location.mli` and `docstring.mli`, I don't see how to implement that differently. I'll try to take another look later this week.

**Comment by hhugo** [comment]
In term of API, I think we would like something like 
`val capture_warnings : (unit -> 'a) -> (Location.t * Warning.t) list * 'a`

**Comment by hhugo** [comment]
4.08 support has been merged in ocaml-migrate-parsetree. I'm not sure if anything else is blocking ..

**Comment by hhugo** [comment]
I've done some work in #831 regarding (1) and (4)

**Comment by hhugo** [comment]
All the points above are now addressed in #831 and #867
