### ISSUE TITLE
Version 0.8 on opam fixed to janestreet < v0.12

### ISSUE THREAD

**Issue by pkel** [ocaml-ppx/ocamlformat#641]
Ocamlformat on opam (0.8) requires janestreet < v0.12 and effectively blocks the update. Is this intentional?

**Comment by mseri** [comment]
All packages in opam have been upper bounded to exclude the new release, see here for more information: 
https://discuss.ocaml.org/t/experimenting-with-a-new-opam-repository-release-strategy-for-large-libraries/2918/21

We will start gradually relaxing the upper bounds, but if you see that ocamlformat works well with janestreet packages v0.12, feel free to send us a PR on ocaml/opam-repository to relax the upper bounds

**Comment by pkel** [comment]
I see, thanks!
