### ISSUE TITLE
Make ocamlformat documentation easy to find online

### ISSUE THREAD

**Issue by yawaramin** [ocaml-ppx/ocamlformat#647]
It would be good to put up the ocamlformat documentation somewhere online or at least in an easy-to-find location in the repo so that potential users don't have to install ocamlformat to find it. Best-case scenario would be something like this: https://scalameta.org/scalafmt/docs/configuration.html

**Comment by jberdine** [comment]
What about just linking the checked-in output of [`ocamlformat --help`](https://github.com/ocaml-ppx/ocamlformat/blob/master/ocamlformat-help.txt) from the readme?

**Comment by yawaramin** [comment]
@jberdine sure, that'd work. I haven't been able to find it so far :-)

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/blob/master/ocamlformat-help.txt
