### ISSUE TITLE
space before closing parenthesis doesn't seem consistent

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#653]
With default configuration, ocamlformat puts a space before a closing parenthesis when it is not on the same line as the opening parenthesis IIUC. But this is not true when using the keyword `function`. It seems to be the only case where it doesn't apply.

```ocaml
let l =
  List.filter_map
    (function
      | [] -> None
      | "" :: _ -> "Some long string to tke some spalce"
      | h :: _ -> Some h)
    l

let l =
  List.filter_map
    (fun s ->
      match s with
      | [] -> None
      | "" :: _ -> "Some long string to tke some spalce"
      | h :: _ -> Some h )
    l

let v =
  match l with
  | [] -> []
  | llllllllllllll -> (
    match llllllllllllll with
    | [] -> []
    | llllllllllllll ->
        let l = llllllllllllll in
        l )
```

**Comment by jberdine** [comment]
Yes, this is a bug, thanks for reporting. Your understanding of when spaces should be added before closing parens is correct.
