### ISSUE TITLE
Add a --check flag for pre-commit hooks

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#655]
Something I value highly in Prettier et al., is the ability to ensure divergent code doesn't make it into the master branch. Towards that end, most of them provide a feature [like `--check`](https://prettier.io/docs/en/cli.html#check), that doesn't actually *write* reformatted files to disk, but simply *checks* whether reformatting causes any changes, and dumps a list of disagreeing files to stdout if there are any.

If it exists with a failure status-code, this can even be used as a git [`pre-commit` hook](https://git-scm.com/docs/githooks#_pre_commit) to ensure that commits with non-conforming code are rejected — and then can be used with tools like [`lint-staged`](https://github.com/okonet/lint-staged#examples) to slot in alongside similar tools in one's codebase.

**Comment by gpetiot** [comment]
There is no such flag so far, but as noted by Josh in #530 it can be handled by the shell with something like: `ocamlformat file.ml | diff file.ml -` and then check whether diff returned 0 or 1.

**Comment by ELLIOTTCABLE** [comment]
The thing is, relying on external tools increases the weight of dependencies to use this tool — and makes the issue a lot gnarlier when supporting Windows. (The entire point of the linked tool, in fact, is to do what one shell command can do … without requiring the user have a sane shell to-hand. `)=`)

It's of course fine to triage something that may be out-of-scope, but I'd really suggest that this would be a nice feature to have built-in!

(One big deal is that the `diff` approach only handles a single file; whereas I'd suggesting that `--check` allow multiple files to be checked in one pass. To do *that* with external tools would probably require copying everything to a temp-directory, running `--inplace`, and then `diff`'ing over the entire directory … either that, or invoking `ocamlformat` a bajillion times, once per file. Way simpler to build it into the tool and make it nice and cross-platform!)

**Comment by jberdine** [comment]
It might not have the best ui for this use case, but note that you can use the existing fixed-point check for this, just requiring that formatting has stabilized after only one iteration. See how this done in [make test](https://github.com/ocaml-ppx/ocamlformat/blob/master/Makefile#L75) for ocamlformat itself. We use this as part of the travis ci job, but it could go into a pre-commit hook or whatever.

**Comment by Julow** [comment]
If you use git you have `diff`.

**Comment by ELLIOTTCABLE** [comment]
@Julow Having `diff` doesn't imply you have `|` … Windows doesn't provide a reliable shell for all users. That's a lot to assume …
