### ISSUE TITLE
Change some default values of options

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#656]
Here is a list of options we could change the value, to better match what people want for the default profile (we will still keep the original value for the ocamlformat code)

| option | old value | new value | details |
| ----------- | --------------- | ---------------- | ------------ |
|  `break-separators`               |  `before`                 |   `after`                     |  Having the semicolon at the beginning of the line frightens a lot of first time users, maybe it's better to switch to this more common style.        |
| `break-infix-before-func` | `true` | `false` |   I think having no space before an infix operator like `>>=` looks better to almost everyone and it is the style that is used when manually writing this code, so maybe it's better to switch this option. Here is an [what this option does](https://github.com/ocaml-ppx/ocamlformat/pull/463/files#diff-cd895127c62a405c640b661a92e3f27f).   |
| `break-sequences` | `false` | `true` | It's more readable to split the sequence of instructions, and looks more like a manually written code.  |
| `field-space` | `tight` | `loose` |  I heard a lot of complaints about the `x= y` style, most people are wondering why there is a space after but not before, maybe it's better to switch this option. |
| `indicate-nested-or-patterns` | `true` | `false` | The removal of the space confuses a lot of people. |
| `sequence-style` | `separator` | `terminator` | Here again having a space before a semicolon does not look like what most people do when manually writing code. |

Any idea of more options that we could change on the default profile?

**Comment by gpetiot** [comment]
cc @samoht @avsm @Julow @jberdine @hhugo @emillon @dinosaure @NathanReb gathering your opinion before linking this issue on the OCaml discuss

**Comment by emillon** [comment]
Thanks for taking the time to do this!

- `break-separators`: I agree. I personally use semicolon-first, but separators after seems more sensible as a default.
- `break-infix-before-func`: can you add an example? I'm not sure what it controls, especially compared to `break-infix`.
- `field-space`: agree, that's a weird default and my main problem with the default profile

In addition, I think that we should consider changing `sequence-style` to `terminator` and setting `break-sequence` to true. That matches how imperative programs are usually written, not only in OCaml (see RWO), but also in C, Javascript, etc.

**Comment by gpetiot** [comment]
Thanks! I agree for the 2 options you suggested, and I added a link for what `break-infix-before-func` does.

**Comment by emillon** [comment]
Cool. I don't have a strong opinion on that one then. I expect that in the long run, `( let+ )` will be used for these cases anyway.

**Comment by jberdine** [comment]
Individual choices need some more consideration, but a high level point I want to make is that the defaults should be set in a way that provides as close to a self-consistent style across the whole range of code as possible. Also, changing options that conflict with the principles of the style described in the readme should come with an alternative for the readme. I think that it really takes looking at, comparing, and commenting on the output on a lot of code with the suggested sets of options.

My expectation is that changing `break-sequence` and `field-space` are likely to be not problematic. I am worried about `break-separators` as so much of the rest of the formatting has been designed with a structure-indicated-by-the-left-margin approach.

We also need to be clear about what the defaults are trying to optimize. It will be much more productive to choose the defaults after the objective has been set. My position is that the defaults should optimize for steady-state development, in particular for after people have used auto-formatting for long enough to have forgotten the initial shock of a style change, where the longer-term points such as quick accurate code legibility are much more important than any sort of familiarity.

**Comment by samoht** [comment]
> We also need to be clear about what the defaults are trying to optimize. 

For me: they should maximise adoption.

**Comment by dinosaure** [comment]
I don't have a strong opinion about that when style is a subjective opinion. So an arbitrary layout (even if I don't like it) is what I want.

**Comment by gpetiot** [comment]
Maybe we can create a new profile named `structure-left-margin` or something that would keep the current defaults.
And create a new profile that could be named `beginner` (or `c-style`) with the new defaults. This new profile would be the default profile (but not named `default` since it gives the idea that everyone should use this one and it's not the case).

**Comment by gpetiot** [comment]
Maybe `indicate-nested-or-patterns` should be switched from true to false, as it seems to confuse a lot of people.

**Comment by jberdine** [comment]
It is too dangerous to set `indicate-nested-or-patterns = false` by default. But we could set `break-cases = nested` by default, which would avoid the spacing around `|` that people find surprising. Then the documentation for `indicate-nested-or-patterns` can be expanded to clarify its point (no one thinks it's beautiful as far as I know) and then people willing to take the risk can change the default.

**Comment by gpetiot** [comment]
#663 has been merged and everyone can now try the `conventional` profile. If this profile is good enough for now, can we close this issue?

**Comment by samoht** [comment]
I'm still not convinced by the choice of the `indicate-nested-or-patterns` default, especially by the need to use an odd number of spaces for this.

**Comment by jberdine** [comment]
Note that #663 changed the default for break-cases to nested, which avoids the strange indentation, with the drawback of less compact code.
