### ISSUE TITLE
Removing spaces between bar and pattern in matches

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#666]
So `ocamlformat` is producing a lot of diffs along these lines in my codebase,

```diff
 let token_body tok =
-   match tok with
-   | COUNT s
-   | COMMENT_CHUNK s
-   | COMMENT_LINE s
-   | IDENTIFIER s
-   | LONG_FLAG s
-   | SHORT_FLAGS s
-   | URL s ->
-      Some s
-   | _ -> None
+  match tok with
+  | COUNT s
+   |COMMENT_CHUNK s
+   |COMMENT_LINE s
+   |IDENTIFIER s
+   |LONG_FLAG s
+   |SHORT_FLAGS s
+   |URL s ->
+     Some s
+  | _ -> None
```

… with the invocation `ocamlformat --ocp-indent-config --ocp-indent-compat --wrap-comments --inplace`, this `.ocamlformat` …

```ini
margin = 90

field-space = loose
let-binding-spacing = sparse

let-open = auto
```

… and this `.ocp-indent.conf`:

```ini
base=3
type=3
ppx_stritem_ext=3
max_indent=9

strict_with=auto
match_clause=6
strict_else=auto
```

Not sure what's going on! It's not a huge deal, but hey, thought I'd drop a report.

**Comment by gpetiot** [comment]
Hi, the removal of the space is intended but you can disable this option with `--no-indicate-nested-or-patterns`, or put `indicate-nested-or-patterns = false` in your `.ocamlformat` file.

**Comment by ELLIOTTCABLE** [comment]
Ah! Thanks!
