### ISSUE TITLE
--wrap-comments chokes on ` * *)`

### ISSUE THREAD

**Issue by vphantom** [ocaml-ppx/ocamlformat#667]
Just getting started with OCaml, and I managed to "break" `ocamlformat` version 0.8. :pensive: The following input (typical of how Vim seems to format multi-line comments if I let it) suffices to reproduce the issue:

```ocaml
(* This is a test
 * *)

let
answer
= 42
```

I get the following output:

```text
$ ocamlformat --profile=janestreet --wrap-comments of_bug.ml
ocamlformat: Cannot process "of_bug.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: comments changed.
```

Without `--wrap-comments`, I get the expected behavior.  If I change the last comment line from `* *)` to simply `*)` then `--wrap-comments` works fine.

**Comment by hhugo** [comment]
I think this is fixed on master. The next release (0.9) should be released soon.

**Comment by gpetiot** [comment]
Fixed in master indeed.
