### ISSUE TITLE
Keep post-variant comments location

### ISSUE THREAD

**Issue by g2p** [ocaml-ppx/ocamlformat#688]
This comment gets moved two lines after, and shouldn't be:

```
type insertable =
  | InsValue of string
  | InsChild of int64 * int64 option (* loc, alloc_id *)
```

**Comment by jberdine** [comment]
Note that that comment should probably be a docstring, `(** loc, alloc_id *)`, in which case it will appear where you want IIUC.

**Comment by gpetiot** [comment]
Comment attachment is tricky, I tried a lot of things (like extending the location in the same way it's done for attributes) but eventually the comment is always considered to be outside of the type declaration's location and thus is attached after.

**Comment by jberdine** [comment]
Added to #306
