### ISSUE TITLE
Doesn't support ocaml 4.03.0

### ISSUE THREAD

**Issue by mroch** [ocaml-ppx/ocamlformat#7]
`opam switch 4.03.0; make` fails:

```
(cd _build/opt && /Users/mroch/.opam/4.03.0/bin/ocamlc.opt -safe-string -strict-formats -strict-sequence -principal -w +a-4-6-9-40-41-42-44-45-48@50-21 -short-paths -bin-annot -keep-docs -keep-locs -unboxed-types -noassert -bin-annot -no-alias-deps -I format -open Format___ -o format/format_.cmi -c -intf format/format_.mli)
/Users/mroch/.opam/4.03.0/bin/ocamlc.opt: unknown option '-unboxed-types'.
```

**Comment by mroch** [comment]
also uses `Filename.extension` which is 4.04+

the opam file doesn't have a version restriction. would be awesome to still support 4.03 instead of restricting it to 4.04, though!

**Comment by mroch** [comment]
#8 gets it building in 4.03, but it gets Lexer errors when built with 4.03. what determines which ocaml versions are supported?

**Comment by mroch** [comment]
re: the comments:

https://github.com/ocaml/ocaml/blob/4.03/parsing/lexer.mll#L415
https://github.com/ocaml/ocaml/blob/4.04/parsing/lexer.mll#L422

in 4.03, `(*****` is a `COMMENT` token that includes the `(*`, but 4.04 excludes it. `Cmts` prefixes it with another `(*` anyway.

https://github.com/ocaml-ppx/ocamlformat/blob/f6b50d4a72011288dbbc93aed609dd39f4c4fef5/src/Cmts.ml#L501

**Comment by jberdine** [comment]
Yes, in 4.04 there were a number of improvements relating to comments and docstrings made in the context of improving the documentation generation tools, etc. I expect that the handling of comments and docstrings in ocamlformat relies significantly on those improvements. I worked off of trunk while developing ocamlformat, and those improvements were already in place.

**Comment by jberdine** [comment]
I'm going to close this for now. If someone really need 4.03 support and wants to work around all the issues with comments, please reopen.
