### ISSUE TITLE
Weird break for parens

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#706]
```
$ echo "let _ = List.map rows ~f:(fun row -> Or_error.try_with (fun () -> fffffffffffffffffffffffff row))" | _build/dev/src/ocamlformat.exe --name a.ml --profile janestreet  -
let _ =
  List.map rows ~f:(fun row -> Or_error.try_with (fun () -> fffffffffffffffffffffffff row)
  )
;;
```

**Comment by jberdine** [comment]
For code that *just* reaches the margin, this sort of output is expected. Do you think we should instead force-break the preceding code if the closing parens don't fit? There will be several cases where that could be easily done, but doing it systematically would be quite involved I think.

**Comment by hhugo** [comment]
I would expect to force a break and have.
```ocaml
let _ =
  List.map rows ~f:(fun row ->
    Or_error.try_with (fun () -> fffffffffffffffffffffffff row)
  )
```
related to https://github.com/ocaml-ppx/ocamlformat/pull/689#issuecomment-474830357.

**Comment by gpetiot** [comment]
#708 generated this expected output, @jberdine you don't like the fix but given the box configuration it looks like it's the only feasible fix.

**Comment by jberdine** [comment]
I remain unhappy with the approach implemented in #708. Apart from the concerns already raised, what about cases where the expression spans multiple lines but the last one just reaches the margin. The basic approach in #708 can't AFAIU handle such cases, it is too specific to the repro.

**Comment by hhugo** [comment]
Is there any hope to see this address soon-ish ? This is one of the last "regression" we see on our codebase.

**Comment by jberdine** [comment]
I'm not sure I understand this issue. From the initial description, I thought you didn't want a closing paren on a line by itself. But the later comment with the expected output still has such a paren. I'm not sure what distinguishes the two. Can you expand?

**Comment by hhugo** [comment]
```
let _ =
  List.map rows ~f:(fun row ->
    Or_error.try_with (fun () -> fffffffffffffffffffffffff row))
```
would be fine as well.

As far as I can see, it's only a problem with function application with a trailing `fun` and `function` argument. I would expect to either see the entire last argument to fit on one line (including closing parens) or force a break after the arrow.

**Comment by jberdine** [comment]
In that case, an approach that might work is to omit the break hint before the closing paren. It will also be necessary to fiddle the spacing to keep the closing parens from violating the margin. Perhaps something like adding `Format.fprintf fs "@<1>%s" ""` inside of the box preceding the closing paren, and `Format.fprintf fs "@<-1>%s" ""` outside of the box.
