### ISSUE TITLE
special case some doc-comment   

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#707]
`odoc` uses some doc-comment tags to controls its behavior (`@canonical`, `@inline`, `@open` and `@closed`).

Theses tags are usually standalone and usually fit on the same line as the item they comment.

Can we create a special case so that they are printing after the item. For instance:
```ocaml
include Base.Fn (** @open *)
```
instead of
```ocaml
(** @open *)
include Base.Fn
```

**Comment by hhugo** [comment]
cc @mbarbin

**Comment by gpetiot** [comment]
This is possible with `--doc-comments-tag-only=fit`

**Comment by hhugo** [comment]
```
echo "include Base.Fn  (** @open *)" | /j/office/app/dev-tools/prod/apply-style/1.4-5/ocamlformat --profile janestreet  --name a.ml --doc-comments-tag-only=fit -
(** @open *)
include Base.Fn
```
