### ISSUE TITLE
[@@@ocamlformat "disable"] annotation has no effect

### ISSUE THREAD

**Issue by Khady** [ocaml-ppx/ocamlformat#709]
I have an ocaml file that starts with an annotation to disable ocamlformat.

```
[@@@ocamlformat "disable"]

open Printf

open Unix
```

When I run `ocamlformat test.ml`, the file is reformatted, the annotation is not respected.

```
[@@@ocamlformat "disable"]

open Printf
open Unix
```

Tested with ocamlformat 0.8 and master

**Comment by hhugo** [comment]
More precisely, `[@@@ocamlformat "disable"]` will disable formatting for individual items but will still reformat spaces around items.

**Comment by Khady** [comment]
Oh, I guess this is expected. Should be fine for us, we will use `.ocamlformat-ignore` for files that should stay totally intact. So this can probably be closed.
