### ISSUE TITLE
Uneven spaces inside parentheses

### ISSUE THREAD

**Issue by pascutto** [ocaml-ppx/ocamlformat#722]
Hi !
Thanks again for your work on ocamlformat !

With default options and master branch, this example code
```
let _ =
  ( module Ephemeron (HHHHHHHHHHHHHHHHHHHHHHHHHH) (HHHHHHHHHHHHHHHHHHHHHHHHHH)
  : Ephemeron.S )
```
gets formatted to
```
let _ =
  (module Ephemeron (HHHHHHHHHHHHHHHHHHHHHHHHHH) (HHHHHHHHHHHHHHHHHHHHHHHHHH)
  : Ephemeron.S )
```

I'm not sure why the space after the open parenthesis was removed while the close one was kept, but that does not seem right to me.

**Comment by jberdine** [comment]
Thanks for reporting, you're right.
