### ISSUE TITLE
Doc comment for modules do not follow --doc-comments option

### ISSUE THREAD

**Issue by pascutto** [ocaml-ppx/ocamlformat#723]
Hi !
Using master, and `--doc-comments=after`,
```
(** This is a comment *)
module Make = Map.Make
```
is left unchanged by ocamlformat, while the comment should be moved after the module.

**Comment by jberdine** [comment]
The doc for `--doc-comments` is misleading, it currently only affects elements of value bindings, so `let` in structures and `val` in signatures. We should clarify that.

Also, it could be extended to apply in other cases. I don't recall particular issues.
