### ISSUE TITLE
fix for the upcoming ocaml compiler (4.08)

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#737]
- base : https://github.com/janestreet/base/pull/70
- migrate-parsetree : https://github.com/hhugo/ocaml-migrate-parsetree/tree/408-2
- octavius https://github.com/hhugo/octavius/tree/408

**Comment by jberdine** [comment]
ocamlformat_support is not needed for ocamlformat 0.7 onward, so I don't think there is any reason to do anything but put a version bound in the opam file, right?

**Comment by hhugo** [comment]
Ah, I forgot about that.
Well the diffs linked above will probably have to be included in lib/import then, probably with some conditional compilation of some sort so that we can build in both 4.07 and 4.08.

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/pull/763
