### ISSUE TITLE
Unsugared extension point formatted badly

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#74]
Maybe related to some of the issues found during #63 with commenting/uncommenting of code sections.

Given:
```ocaml
let () = [%ext expr]; ()
```
ocamlformat `master` errors out, outputting:
```ocaml
let () = [%ext fun -> expr] ; ()
```
when run with `-g`.

**Comment by hcarty** [comment]
Sorry about the blank initial submission!  Misclick on my part.  The description has been updated.

**Comment by hcarty** [comment]
If I comment out [these] lines then it formats to:
```ocaml
let () =
  [%ext expr] ;
  ()
```

[these]: https://github.com/ocaml-ppx/ocamlformat/blob/dae2991aa297df058b2b6fb826e24341bb80ddfb/src/Fmt_ast.ml#L821-L862

**Comment by jberdine** [comment]
I can't look in detail at the moment, but it seems that `call_fun` and `retn_fun` in that pattern matching are too permissive, and probably need to be replaced with patterns that only match `fun` expressions.

**Comment by hcarty** [comment]
@jberdine Ah thanks!  I think I may have a fix using that suggestion.  It works for at least the simple case in the issue description.  I'll put a PR in.
