### ISSUE TITLE
--wrap-comment interfering with preformatted bits

### ISSUE THREAD

**Issue by vphantom** [ocaml-ppx/ocamlformat#741]
I saw #268 is closed in v0.9, so I don't know if what I'm seeing is a bug or expected behavior.  Suppose I have the following:

```ocaml
(** This is a thing

    Example usage:
    {[
      let s = "string" in
      let i = 42 in
    ]}
*)
```

In order to adhere with established OCaml formatting conventions, which my Vim setup doesn't match for comments, I want to use `--wrap-comments`.  However I can't, because it wraps preformatted strings:

```ocaml
(** This is a thing

    Example usage: {[ let s = "string" in let i = 42 in ]} *)
```

Is this the expected behavior?  I have the same results with `{v ... v}`.

**Comment by jberdine** [comment]
Did you pass `--parse-docstrings`? The structured formatting, rather than blindly wrapping, is only intended to work with that option. It has some rough corners, and currently we're changing docstring parsers, so maybe try with https://github.com/ocaml-ppx/ocamlformat/pull/721.

**Comment by vphantom** [comment]
Ah ha! I was using `--profile=janestreet --wrap-comments` and with your shiny new `--print-config` I can see that no, that left `--parse-docstrings` to false.  With that option enabled, I now get the expected behavior. :)

I see that the documentation for `--wrap-comments` mentioned "comments and docstrings", but I had mistakenly assumed that the "docstrings" here were OCaml's multi-line `{|string|}` syntax.  I had only seen the terms "preformatted" and "verbatim" in manuals regarding ocamldoc.  It makes much more sense that it was referring to comments of course.

**Comment by jberdine** [comment]
Yes, 'docstring' might be mostly unknown other than a compiler-internal term. But it's simple, the content of a 'two star' comment `(** docstring *)` is a docstring, and other comments are just comments.

**Comment by jberdine** [comment]
Closing as seems to be resolved. Please re-open if not.
