### ISSUE TITLE
Should `--disable-outside-detected-project` be the default?

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#745]
It seems that most of the time the safe default is to use `--disable-outside-detected-project`. What do others think?

**Comment by gpetiot** [comment]
By the way, if `--disable-outside-detected-project` is set, the file in $XDG_CONFIG_HOME is ignored, shall we change this behavior if the default changes?

**Comment by jberdine** [comment]
I suspect not. If someone wants to use the global config for a number of source trees, then empty .ocamlformat files can be put in them. Given that we are in the time before enough tooling for people to use their personal preferred style seemlessly on codebases with other contributors, the use cases for the global config are very narrow.
