### ISSUE TITLE
BUG: ast changed with Pexp_function inside match

### ISSUE THREAD

**Issue by anmonteiro** [ocaml-ppx/ocamlformat#754]
The following snippet causes ocamlformat to emit the "BUG: ast changed." error:

```ocaml
match foo with
| 1 ->
  bar >>= (function | _ -> ())
| other -> ()

```

**Comment by gpetiot** [comment]
I don't get any error on master, do you use any specific options?

**Comment by anmonteiro** [comment]
@gpetiot oops I forgot to check config. The following will trigger the error:

```conf
profile = sparse
break-infix-before-func = false
```

**Comment by gpetiot** [comment]
More precisely this issue arises when these two options are combined:
```
leading-nested-match-parens=true
break-infix-before-func=false
```
