### ISSUE TITLE
Improper formatting of strings with newlines.

### ISSUE THREAD

**Issue by soverysour** [ocaml-ppx/ocamlformat#770]
Hi, I've looked through the issues and I didn't find one similar to this one.

The problem is that ocamlformat breaks some string literal in a weird way - and some other string literal in another really weird way. Note that this string 'formatting' doesn't result in equivalent string literals.

`ocamlformat --version` -> `0.9`; Installed through opam.

Ocamlformat command:
`ocamlformat -i --profile=janestreet  > /dev/null 2>&1 filename`

Here is some example code which is broken:

```ocaml
let test =
  print_string
    "\n--------------------------------------------------------------------------------\n"
;;
```

That should be 80 `-` characters.

That is formatted to:

```ocaml
let test =
  print_string
    "\n\
     --------------------------------------------------------------------------------\n"
;;
```

After running ocamlformat on the same file again, nothing changes, however, running the same command on code like this:

```ocaml
let test =
  print_string
    "\n
     --------------------------------------------------------------------------------\n"
;;
```

Turns it into:

```ocaml
let test =
  print_string
    "\n\n\
    \     \
     --------------------------------------------------------------------------------\n"
;;
``` 

Which doesn't seem right.

Note that the code examples behave like that when formatting a file containing just them.

It looks like a current workaround for this is to have the first newline literal in a string by itself.

**Comment by jberdine** [comment]
Can you provide a case where a non-equivalent string literal is produced, since they are equivalent in the examples you gave. What is the output that you expect? Have you tried different alternative for `--break-string-literals`?

**Comment by soverysour** [comment]
I've checked again the cases above, I was confused by something unrelated - everything is as expected.

Sorry for the caused confusion here!
