### ISSUE TITLE
java style ite

### ISSUE THREAD

**Issue by c-cube** [ocaml-ppx/ocamlformat#777]
it would be very nice if `parens-ite` could have a mode where instead of:

```ocaml
if x1 then foo1
else if x2 then (
  foo2;
  bar2 )
else (
  foo3 )
```
it would print

```ocaml
if x1 then foo1
else if x2 then (
  foo2;
  bar2
) else (
  foo3
)
```

that is, the closing paren is on its own line, but can be followed by `else` (like braces in the standard java style).

**Comment by jberdine** [comment]
I thought this was K&R style, but still, I agree that embracing `else` would be better. I tried to implement this at some point, but it is not clear how given the Format API. Unconditionally parenthesizing all conditional arms would be more doable in the short term, e.g.:
```
if x1 then (
  foo1
) else if x2 then (
  foo2;
  bar2
) else (
  foo3
)
```
Would an option for that that be better?

**Comment by c-cube** [comment]
with `Format` you may want to try negative indentations in a v box, I think. Parenthesizing all arms or none is perfectly fine for me! :smile:
