### ISSUE TITLE
`<-` isn't always indented

### ISSUE THREAD

**Issue by c-cube** [ocaml-ppx/ocamlformat#778]
see [this line](https://github.com/AestheticIntegration/minisat-ml/blob/06ddb50dd5da52466432c431ddf9d16d5ea34d7c/src/lib/Minisat_solver.ml#L965)

I think

ocaml
```
x <- foo
```

should become, when a break is inserted:

```ocaml
x
  <- foo
``` 

rather than

```
x
<- foo
```

**Comment by jberdine** [comment]
Q: do you think the same should hold for other infix binary operators as well, or you'd prefer `<-` to be treated specially? That is, if there was some other infix op with return type `unit`, would your preferred style be the same as you suggest for `<-`? Currently ocamlformat operates on the untyped parsetree, so can't make decisions based on types. So far the tension between treating infix ops with different names non-uniformly (trying to guess the return type from the symbol name) versus the most legible indentation for `unit`-returning ones has come down in favor of uniformity. It might be that `unit`-returning infix ops are rare enough that the non-uniformity is ok. Thoughts?

**Comment by c-cube** [comment]
personally I always indent in this case. Indentation helps me see the structure, and for a simple expression I'd definitely find

```
x
  + 1
```

more readable than

```
x
+ 1
```
