### ISSUE TITLE
Unecessary break before structure

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#789]
With the `janestreet` profile.

The `struct` keyword should be on the `let module` line:

```ocaml
let f x =
  let module M =
    struct
      let x = x
    end
  in
  ()
;;
```

**Comment by hhugo** [comment]
I'm not sure struct on the same line plays nicely with ocp-indent

**Comment by mbarbin** [comment]
@hhugo I think it's good now that we are running ocp-indent >= 1.7.0

**Comment by Julow** [comment]
Is this the expected behavior ?
```ocaml
let f x =
  let module M = struct
    let x = x
  end in
  ()
;;
```
The `end` keyword is on the same line as `in` and the structure is less indented.

**Comment by jberdine** [comment]
@Julow, intended: yes, very carefully thought through: no. It's that way since with `let module` there is nothing that can come between `end` and `in`, so it's all just "the punctuation at the end" and put on one line.

**Comment by gpetiot** [comment]
This is contrary to what was asked in #628 (see #768), can you try with the option `--let-module=compact`?
