### ISSUE TITLE
Coercion in records

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#791]
In record expressions, type annotations are moved from expressions to field names:

```patch
-let _ = x { a = (a' : string); b = (b' : string) }
+let _ = x { a : string = a'; b : string = b' }
```

In patterns:
```patch
 let x = function
-  | { a = (_ : string); _ } -> ()
+  | { a : string = _; _ } -> ()
```

**Comment by hhugo** [comment]
This was triggered by https://github.com/ocaml-ppx/ocamlformat/issues/374.
I'm not sure what we want here.

**Comment by Julow** [comment]
Does it make sense to add an option for this ?
What do you think, @mbarbin ?

**Comment by mbarbin** [comment]
In Julow's example, the green line is the tip of master, and the red is how jane is currently formatted.  I was suggesting to have a toggle for now so we can maintain the status quo in jane while upgrading to 0.10, and have more time to decide whether we want to opt-in into the sugared form as an asynchronous decision after we're running 0.10.  Jane has a surprisingly high occurrences of such pattern, thus allowing to dissociate that change from the upgrade has value in my opinion.

**Comment by jberdine** [comment]
The parsetree is indistinguishable between the cases where the type annotation is on the field versus the expression, right? It would be irritating, but we could perhaps test whether the location of the type comes before or after the expression, and choose the output style based on that.
