### ISSUE TITLE
Syntax error on signatures

### ISSUE THREAD

**Issue by chrismamo1** [ocaml-ppx/ocamlformat#795]
If my file `a.mli` looks like this:

```ocaml
module X :
  (Y with type t := Z.t)
```

then I get a `Syntax error` message when trying to format it. What could be causing this?

**Comment by Julow** [comment]
It works fine for me. Maybe you file is parsed as an implementation file (eg. `a.ml`) ?

**Comment by gpetiot** [comment]
I don't get any error either, what options did you use?

**Comment by chrismamo1** [comment]
I'm no longer able to reproduce this error, it appears to have been an issue with my usage, since my `ocamlformat` invocation appeared deep an a shell script, something else went wrong along the way.
