### ISSUE TITLE
Invalid syntax generated when trying to always use extension sugar on opens

### ISSUE THREAD

**Issue by chrismamo1** [ocaml-ppx/ocamlformat#796]
I get this error:

```
BUG: generating invalid ocaml syntax.
```

when trying to format anything like this:

```ocaml
open%any_extension M
```

with configuration `extension-sugar` set to `always`

**Comment by Julow** [comment]
I cannot reproduce. What version of ocamlformat are you using ? Could you share your configuration ?

**Comment by chrismamo1** [comment]
That example seems not to be the one actually causing me problems. I think my problem may in fact be related to the following:

```ocaml
let value =
  f
    [%any_extension
      function
      | 0 -> false
      | _ -> true 
    ]
```

**Comment by chrismamo1** [comment]
Apologies, my workflow must have gotten messed up because after a shell restart, I'm no longer having problems.

**Comment by Julow** [comment]
I can reproduce the bug with your second example with `--extension-sugar=always`. So I reopen.
