### ISSUE TITLE
Support setting string escape mode using annotations

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#81]
It may be worth adding some (short) annotations to support inline escaping definitions.  For now, given this file:
```ocaml
let _ = "hello world"
```
`ocamlformat string_example.ml --escape-strings=hex` prints:
```ocaml
let _ = "\x68\x65\x6c\x6c\x6f\x20\x77\x6f\x72\x6c\x64"
```
while `dec` and `pre` format the input without any changes.  Is that intentional?

**Comment by jberdine** [comment]
Yes, the hex escaping is rather aggressive, and the per-file granularity of the setting is probably too coarse. I agree that adding an annotation to control the escaping setting would be a good idea. I'm not sure if rando ppxs are supposed to steal short unqualified names from the annotation space though. `[@ocamlformat.hex]` should be fine, but I wouldn't be surprised by complaints if ocamlformat used `[@hex]`.

**Comment by jberdine** [comment]
Related to https://github.com/ocaml-ppx/ocamlformat/issues/10

**Comment by hhugo** [comment]
I suspect this one can be closed now that ocamlformat preserve escaping. Or is your use case different ?

**Comment by hcarty** [comment]
The preservation of strings takes care of my use cases so I'm OK with closing this issue. Annotations could still be useful in some cases but I don't know if that's something worth adding to ocamlformat itself.

**Comment by jberdine** [comment]
Yes. We can reopen if and when setting the encoding is needed in e.g. a code generation use case.
