### ISSUE TITLE
Apply --space-around-collection-expressions differently for lists and records

### ISSUE THREAD

**Issue by grievejia** [ocaml-ppx/ocamlformat#824]
For `--space-around-collection-expressions`, the rule applies for lists and records in the same way. This means that I either get
```ocaml
type t = {x: int; y: int}
let _ = [1; 2]
let _ = {x= 1; y= 2}
```
or
```ocaml
type t = { x: int; y: int }
let _ = [ 1; 2 ]
let _ = { x= 1; y= 2 }
```
Is there a way to apply the rule differently and let me get this:
```ocaml
type t = { x: int; y: int }
let _ = [1; 2]
let _ = { x= 1; y= 2 }
```

**Comment by gpetiot** [comment]
This is not in our plans for the moment. Of course it is still possible to add more options in the future, i.e replace space-around-collection-expressions with space-around-arrays, space-around-lists, space-around-variants, space-around-record, but I'm afraid we already have too many options (maintaining them and checking there is no inconsistencies and bugs when combining them is already difficult).

**Comment by grievejia** [comment]
Thanks for the response! Personally I am ok with whatever exiting style says. But when I try to push `ocamlformat` adoption to our team there were some pushbacks on things like this. As I did not closely follow the development of `ocamlformat`, it's not 100% clear to me which of my team's formatting requirements can be easily supported and which of them I need to work on to persuade my teammates to live with. Hence the question.

Feel free to close this issue if you feel that the requested features is not likely to get supported in the foreseeable future.
