### ISSUE TITLE
Apply --field-space differently for declaration and construction

### ISSUE THREAD

**Issue by grievejia** [ocaml-ppx/ocamlformat#825]
I'm trying to find a way to treat `:` and `=` differently. At the moment I can do this:
```ocaml
type t = {x: int; y: int}
let _ = {x= 1; y= 2}
```
Or this:
```ocaml
type t = {x : int; y : int}
let _ = {x = 1; y = 2}
```
But is it possible to do this:
```ocaml
type t = {x: int; y: int}
let _ = {x = 1; y = 2}
```

**Comment by gpetiot** [comment]
My answer in #824 stands here as well, maybe @Julow has a different opinion (following up #819)

**Comment by Julow** [comment]
I'm in favor of this as it can be done by adding a case to an existing option.
