### ISSUE TITLE
RFC: formatting of generated-code VS preserving users choices

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#834]
I think there is a tension between the use case of formatting generated code and preserving users choices, which I hadn't really thought of before.

Consider the following pattern, by which generated code is formatted using ocamlformat for readability:

```
Ast Generation
|> Pprintast (from ppxlib)
|> Ocamlformat
```

Before the introduction of functionality of the kind 'perserve the author's intent', the resulting syntax would have little dependency into Pprintast, and be quite stable as long as Pprintast would write a syntactically correct code.

With a newer version of ocamlformat, there are more control giving back to the original contents, which means that some choices are preserved.  As a result here, the resulting code start having more dependency into what Pprintast does.  If one were to care about the predictability of the output, one would have to start duplicating some formatting effort into Pprintast, which seems undesirable, given that this functionality is already in Ocamlformat.

The particular example that prompted this is a generated code making use of the inline directive, which Ocamlformat let one place right behind the let ...

```
let[@inline always] f x = expr
```
... or at the end of the body
```
let f x = expr [@@inline always]
```

Before #681 the generated file would end up in form 1, but Pprintast generates form 2, and with that patch the style of the generated file changes.

I am not sure what to think.

Independently from that specific example, perhaps it would make sense for it to exists an option that one could pass to Ocamlformat to inform that the source was generated.  In the implementation of those style branches that extract information from the source, when that flag is supplied, Ocamlformat would instead resort to picking up a default instead?

**Comment by xclerc** [comment]
(Not certain it is relevant, but once https://github.com/ocaml-ppx/ppxlib/pull/79 is merged,
the `Pprintast` from ppxlib will be indistinguishable from the one
upstream.)

**Comment by gpetiot** [comment]
We can create options instead of blindly rely on the original source, but this will result in a least 2 different values for each option (in addition to the `preserve` value).

So how do we decide which value to pick if a `generated` option (most likely a profile) is set? Since I think a "default" value (used in a default profile I mean) would most likely be the `preserve` value, because that's what most users want. So we arbitrarily pick one of the two other values as default? Or the value used for the JS profile? which would most likely make the `generated`profile a JS-oriented profile.

**Comment by gpetiot** [comment]
So do you want to change the behavior for `let[@inline always] f x = expr` or is it not necessary since https://github.com/ocaml-ppx/ppxlib/pull/79 is merged? (and we can close this issue)

**Comment by mbarbin** [comment]
Thank you for the follow up.  I'm personally happy to close this issue.  We can refer to this issue if a new compelling case resurfaces.  Thanks!
