### ISSUE TITLE
Incomplete implementation of break-cases=after-and-docked

### ISSUE THREAD

**Issue by grievejia** [ocaml-ppx/ocamlformat#835]
I believe currently the first field in the record behaves slightly differently from the rest:
```ocaml
let long_variable_name =
  { xxx = 1;
    yyy = 2;
    zzz = 3 }
in
```
Would it be possible to support a style where all fields get the same indentation? For example,
```ocaml
let long_variable_name =
  {
    xxx = 1;
    yyy = 2;
    zzz = 3
  }
in
```
Or a docked varaint (which I believe is already supported for record type declarations):
```ocaml
let long_variable_name = {
    xxx = 1;
    yyy = 2;
    zzz = 3
  }
in
```

**Comment by grievejia** [comment]
ditto for lists, arrays, etc.

**Comment by gpetiot** [comment]
Would the output of #856 be enough? We cannot put the opening `{` on the previous line right now, due to the current implementation of expressions.

**Comment by grievejia** [comment]
@gpetiot Thank you so much for working on this! Yes as long as the indentations are consistent for all items it would be good enough for me.
