### ISSUE TITLE
ocamlformat strips carriage returns from string literals when input comes from stdin

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#839]
Inside {| ... |} string literals, ocamlformat treats DOS-style CR/LF newlines inconsistently. If I pass input to ocamlformat from a file (give a filename on the command line, whether the output is in-place or stdout), ocamlformat preserves the CR/LF newlines in the string literal. If I pass input to ocamlformat from stdin (pass "-" and a "--name=" option on the command line), ocamlformat strips the carriage returns and produces a string literal with UNIX-style newlines.

I believe the correct behavior should be to preserve the carriage returns in all cases, as removing them changes the value of the string literal.

**Comment by hhugo** [comment]
@ceastlund, what version did you try ?
I was not able to reproduce the issue with master using 
```
echo -e "let x = {|\r\n|}" | ~/l/ocamlformat/_build/dev/src/ocamlformat.exe - --name a.ml --enable-outside-detected-project
```

I was however able to reproduce the issue with the version used a janestreet.

**Comment by ceastlund** [comment]
Looks like you're right, the latest version of master that we've built for testing does not reproduce this.
