### ISSUE TITLE
Spaces may be dropped in string literals

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#84]
The following input, with -m 90:
```
let f = function
  | () ->
    raise_s [%sexp "Xxxx xxx xxxx xx xxxxxx xx xxx xxxxxxx xxxxxx, xxxxxxx \
                    xxxxxxxxxx xx xxxx.  Xxxx."
                 , 0]
```
triggers the error: _Internal Error: formatting changed ast_.

Using the _DEBUG_ mode reveals:
```diff
31c31
< Pexp_constant PConst_string("Xxxx xxx xxxx xx xxxxxx xx xxx xxxxxxx xxxxxx, xxxxxxx xxxxxxxxxx xx xxxx.  Xxxx.",None)
---
> Pexp_constant PConst_string("Xxxx xxx xxxx xx xxxxxx xx xxx xxxxxxx xxxxxx, xxxxxxx xxxxxxxxxx xx xxxx. Xxxx.",None)
```

The two spaces that immediately preceded the last word of the literal are replaced by a single space through the reformatting.  This is sort of hard to reproduce as the break point inserted has to be right at the two space location, thus this funny looking example.  It may be possible to further simplify.

**Comment by jberdine** [comment]
Thanks for reporting! Looks like a bungled corner case in the wrapping code.
