### ISSUE TITLE
Bug: comment dropped 

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#845]
```
$ (echo "class type i = object (* test *)"; echo "inherit oo end") | ~/l/ocamlformat/_build/dev/src/ocamlformat.exe - --name a.ml --enable-outside-detected-project
ocamlformat.exe: Cannot process "a.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: comments changed.
```

**Comment by gpetiot** [comment]
The error only arises when there is a newline, so it's not caused by comments at some location being forgotten by the formatting. Do you have an idea of what is happening?

**Comment by hhugo** [comment]
The newline will change where we attach the comment in the Ast.
- With the newline the comment get attached after the `self`.
- Without the newline, the comment get attached before `inherit`

In the example above, we don't display `self`, so the comment is never printed.

**Comment by hhugo** [comment]
https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Fmt_ast.ml#L2216 is likely to blame
