### ISSUE TITLE
Ignore directories in .ocamlformat-ignore

### ISSUE THREAD

**Issue by sinancepel** [ocaml-ppx/ocamlformat#865]
For our project, we regularly pull in some third-party code where it doesn't make sense to ocamlformat the files, as we need to regularly pull in updates (what we're doing is definitely questionable, but that's a separate discussion). 

Is it possible with the current ocamlformat-ignore implementation to blacklist an entire directory? I tried the `/directory_to_ignore` and `directory_to_ignore/*` syntaxes, which didn't work, and couldn't find documentation.

Thanks!

**Comment by hhugo** [comment]
not perfect by note that you can have an `.ocamlformat` file containing `disable` to disable ocamlformat in part of your codebase.

**Comment by sinancepel** [comment]
That works well enough for my case :) I respect that you might not want to introduce feature creep into the .ocamlformat-ignore files, so feel free to close this issue if you feel like this isn't a priority.

**Comment by gpetiot** [comment]
I added this question+answer to the [FAQ](https://github.com/ocaml-ppx/ocamlformat/wiki/Frequently-asked-questions)
