### ISSUE TITLE
When --name is provided, it could try to use that name to infer --intf or --impl

### ISSUE THREAD

**Issue by mbarbin** [ocaml-ppx/ocamlformat#87]
To be confirmed, as I haven't looked at the code, but I do have an mli file for which I witness the following behavior:

```
ocamlformat -m 90 --name 'a.mli' /tmp/afb5focamlformat
File "/tmp/afb5focamlformat", line 18, characters 0-0:
Error: Syntax error
EXIT STATUS 1
```
But adding **--intf** solves the issue:
```
ocamlformat -m 90 --name 'a.mli' /tmp/afb5focamlformat --intf
EXIT 0
```

This is a minor enhancement proposal: not require --intf or --impl if the kind of the file can be deduced from the --name argument.

**Comment by jberdine** [comment]
Thanks! This was an oversight.
