### ISSUE TITLE
"generating invalid ocaml syntax" on recursive module definition

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#871]
The code:

`module rec M : sig end with type t := a = struct end`

The error message:

> ocamlformat: Cannot process "worker0.ml".
>   Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
>   BUG: generating invalid ocaml syntax.

**Comment by gpetiot** [comment]
I don't get this error with the master branch of ocamlformat (I tested the default profile and the `janestreet` profile).

**Comment by ceastlund** [comment]
I'm testing against the latest now. If it's fixed I'll close this issue. Thanks for looking into it.

**Comment by ceastlund** [comment]
Looks like this is fixed in master, sorry for the spurious report.
