### ISSUE TITLE
Compatibility with dune's future_syntax

### ISSUE THREAD

**Issue by NathanReb** [ocaml-ppx/ocamlformat#888]
I recently ran into an error while formatting code that used dune's `future_syntax` feature that allows you to use custom `let` operators ahead of 4.08.

It seems that at the moment `ocamlformat` isn't compatible with that feature, I assume it's due to the fact that the code simply doesn't parse although I didn't take time to investigate this yet.

We discussed this with @Julow and I was wondering whether `ocamlformat` could always use the latest parser, or at least the one that correspond to the AST version it uses internally. I haven't given it much thought yet but it seems like it could potentially fix this issue without breaking anything else since it wouldn't change the AST used to produce the formatted code.

Using dune's `future_syntax` parser wouldn't work as it doesn't parse them to `letop` and the formatted code would look nothing like what the author originally wrote.

Would you be willing to make `ocamlformat` compatible with `future_syntax` and does that sound like a good approach to you?

**Comment by NathanReb** [comment]
cc @diml as you probably know all about `future_syntx`!

**Comment by NathanReb** [comment]
Hmm, reading https://discuss.ocaml.org/t/what-is-holding-you-back-from-upgrading-to-the-latest-ocaml-compiler/3753/5?u=nathanreb it would not necessarily make sense to support.

If it's as simple as using the latest parser it might still be worth it though.

**Comment by Julow** [comment]
This is not possible currently. OCamlformat works on the lastest AST, thanks to `ocaml-migrate-parsetree` but, from the `Parse` module of omp:
```
   The parser used is the one from current compiler-libs.  The resulting AST is
   then converted to the desired version.
```

It does not have the last version of the parser, only of the AST.

**Comment by bikallem** [comment]
I just tried the latest dev-repo of ocamlformat on a repo that is 4.08 and uses the `let*` and `let+` synatax and it is giving error.

**Comment by Julow** [comment]
@bikallem 4.08 support has been merged yesterday and will be released in a few days.

**Comment by gpetiot** [comment]
Now that ocamlformat 0.10 is released can we close this issue?

**Comment by NathanReb** [comment]
Yeah I think so. The solution definitely is develop and format using OCaml 4.08 and ocamlformat 0.10 while using `future_syntax` to ensure compatibility with older versions.

It would have been nice to have that if it was easy to implement but since it would at least require embedding the 4.08 parser in ocamlformat I don't think it's worth it. We can wait for 4.08 adoption!
