### ISSUE TITLE
field-space: loose doesn't apply inside ppx directives

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ocamlformat#890]
I'm not sure if this is intended behaviour, a bug, or if `ocamlformat` simply doesn't consider the body of ppx annotations within-scope; but:

With the config

    field-space = loose

I'm getting this diff being applied to my code:

```diff
-[@@bs.deriving jsConverter] [@@deriving to_yojson { optional = true }]
+[@@bs.deriving jsConverter] [@@deriving to_yojson {optional = true}]
```

**Comment by bbc2** [comment]
That's not what `field-space` is for:

>>>
        --field-space={tight|loose}
           Whether or not to use a space between a field name and the rhs. This option affects records and objects.
           tight does not use a space between a field name and the punctuation symbol (`:`or `=`). loose does. The
           default value is tight.
>>>

Tight:

```ocaml
type foo = {a: int} [@@deriving yojson {optional= true}]

let foo = {a= 0}
```
Loose:

```ocaml
type foo = {a : int} [@@deriving yojson {optional = true}]

let foo = {a = 0}
```

You are actually looking for:

>>>
       --space-around-collection-expressions
           Add a space inside the delimiters of collection expressions (lists, arrays, records).
>>>

or, if you use the master branch:

>>>
       --space-around-arrays
           Add a space inside the delimiters of arrays.

       --space-around-lists
           Add a space inside the delimiters of lists.

       --space-around-records
           Add a space inside the delimiters of records.

       --space-around-variants
           Add a space inside the delimiters of variants.
>>>

**Comment by gpetiot** [comment]
Exactly, the option you are looking for is `space-around-records`. I'm closing this issue.
