### ISSUE TITLE
v0.9 doesn't build with OCaml 4.08 

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#891]
I've backported fixes on top of v0.9
https://github.com/ocaml-ppx/ocamlformat/tree/v0.9.1

Can someone take care of releasing a fix in opam ?

**Comment by hakuch** [comment]
Should we expect that OCaml 4.08 will be supported in a future release of ocamlformat?

Unless I've misunderstood, it's not currently possible to use ocamlformat with a 4.08 opam switch.

**Comment by gpetiot** [comment]
> Should we expect that OCaml 4.08 will be supported in a future release of ocamlformat?
> 
> Unless I've misunderstood, it's not currently possible to use ocamlformat with a 4.08 opam switch.

It is possible to use the master branch with 4.08, sorry the release is a bit late.

**Comment by gpetiot** [comment]
> I've backported fixes on top of v0.9
> https://github.com/ocaml-ppx/ocamlformat/tree/v0.9.1
> 
> Can someone take care of releasing a fix in opam ?

Patch submitted https://github.com/ocaml/opam-repository/pull/14343

**Comment by gpetiot** [comment]
Fixed with ocaml/opam-repository#14343
