### ISSUE TITLE
Improve the contributor-friendliness

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#897]
Right now very few people contribute to `ocamlformat`, here are some things we should improve: (if you were a potential contributor to ocamlformat, let us know what made you give up on submitting a PR)

# Code
- [ ] for each `.mli` file, document each function and add examples when appropriate
- [ ] distinguish the formatting code and the parameters, it has been started by moving the parameters from Fmt_ast.ml to Params.ml
- [ ] Fmt_ast.ml is a scary beast, any idea to split this file is welcome

# OCaml ecosystem
- [x] dunify more parts of the project, see #881, and update the contibuting guide accordingly

**Comment by gpetiot** [comment]
I'm doing a few things to improve the clarity of the project here on github:

# Changing the labels: https://github.com/ocaml-ppx/ocamlformat/labels

- reduce the number of different colors, some were really not easy to read, I think it's better to now have 1 color per kind of tag
  * green for status
  * orange for priority
  * blue for kind except for the bugs (red) that need to be easily identifiable
  * yellow for Good first issue and Help wanted
- I added emoticons for Good first issue (:+1:), Help wanted (:fire:) and Bug (:x:) as they are the ones that need to be the more identifiable, and I think the result looks good: https://github.com/ocaml-ppx/ocamlformat/issues
- I think we can remove the Priority labels (Low, Medium, High, Critical) as we never use them and the priority is most of the time determined by the kind of issue anyway:
  * style suggestions, docs and discussions are low priority
  * feature requests are often medium priority
  * bugs are high priority
- I also think the Status labels could be simplified: "More info needed" and "Triage" are both rarely used, we could maybe remove "More info needed", and make "Triage" the default tag when an issue is created?

Note: don't forget to update the contributing guide after all that.

# Using a project by feature kind

I created new projects (instead of the default one Ocamlformat that was not used) so we can group some issues/PRs together depending on the nature of the feature:
- Comments
- Docstrings
- Tooling: compatibility with the OCaml ecosystem (compiler, ppx, dune, merlin, ocp-indent, editors)

**Comment by Julow** [comment]
Nice !
For status labels I think we can remove them entirely. They are redundant with open/close status on issues and PRs and may easily be out of sync with the discussion in the issue or PR.
More-info-needed, triage and acknowledge => issue is open.
Regression and Fixed-need-test on PRs => PR is open, exact status is probably more complicated than that.
Fixed => PR is merged and the issue closed. 
Awaiting-feedback may be useful on its own but I don't think people are regularly checking if it's set or waiting to give their feedback.

**Comment by gpetiot** [comment]
I agree with that, they are not really used in practice and it will simplify the contribution guidelines.

**Comment by gpetiot** [comment]
Progress has been made on the labels, the doc, and on the file splitting, but as this will never been really over, I'm closing it.
