### ISSUE TITLE
Changing begin...end to (...)

### ISSUE THREAD

**Issue by yawaramin** [ocaml-ppx/ocamlformat#9]
# Observed

ocamlformat is changing `begin ... end` to `(...)`

# Excpected

It retains `begin ... end`.

Note that I'm actually not sure if this is intentional. I just think it's a good idea to keep `begin ... end` because it's often used to design a nice DSL-like syntax for code.

**Comment by jberdine** [comment]
This is expected, the formatter does not produce `begin`/`end`. The parsetree does not explicitly represent or distinguish between parens and `begin`/`end`. The formatter adds parens where necessary to disambiguate (and in a few cases that are not strictly necessary). It would be technically possible to add a configuration option and query it in the formatting code to automatically choose to generate `begin`/`end` in some situations.

**Comment by jberdine** [comment]
Closing as this is not currently feasible to implement. Please feel free to submit a PR with a configurable mode to generate `begin`/`end` in some situations.
