### ISSUE TITLE
;%ext doesn't format properly

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#91]
The following will fail to format - the `%ext` is dropped from `;%ext`.

```ocaml
let () =
  f (fun () -> ()) ;%ext
  f ()
```

**Comment by hcarty** [comment]
This is a bit more relevant now that Lwt's latest ppx release supports this syntax.

**Comment by hcarty** [comment]
The issue seems to be here: https://github.com/ocaml-ppx/ocamlformat/blob/1942d331197335258e545a16bb7ab6c5eafb0a57/src/Fmt_ast.ml#L1411

I think the fixed `" ;@;<1000 0>"` format is the issue here.

**Comment by hcarty** [comment]
A possibly more complete/useful example that fails to format properly:
```ocaml
let () =
  f (fun () -> ()) ;%ext
  g (fun () -> ()) ;
  h (fun () -> ()) ;%ext
  i ();
  j ();%ext
  f ()
```
The latest `master` branch drops all but the last `%ext`.

**Comment by hcarty** [comment]
Thank you @jberdine!

**Comment by hcarty** [comment]
@jberdine I just tested the code [here](https://github.com/ocaml-ppx/ocamlformat/issues/91#issuecomment-372543476) a similar problem remains.  The `;%ext` is duplicated on all except the last function application.

Original:
```ocaml
let () =
  f (fun () -> ()) ;%ext
  g (fun () -> ()) ;
  h (fun () -> ()) ;%ext
  i ();
  j ();%ext
  f ()
```
Formatted output from `ocamlformat -g` (using latest `master` with 799ea94 included):
```ocaml
let () =
  f (fun () -> ()) ;%ext
  g (fun () -> ()) ;%ext
  h (fun () -> ()) ;%ext
  i () ;%ext
  j () ;%ext f ()
```

**Comment by jberdine** [comment]
Argh, yes, extensions violate associativity. That will take a somewhat more involved change to fix.

**Comment by hcarty** [comment]
Thank you for the fix!
