### ISSUE TITLE
[RFC] Move the comments in the AST

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#922]
As it has already been suggested in some PRs/issues before, maybe it would be a good idea to move the comments in the AST, so that we would not have as many comments dropped or missplaced.
The more natural choice would be to put them in attributes `[@ocaml.cmt "this is a comment"]` where the doc comments already are, so that we would not have to modify the types of AST nodes.

I think it was mentioned somewhere that there is 1 node of the AST that has a location (therefore may have comments attached) but not attributes, so that may be an issue but it could be fixed later anyway.
Any comments? cc @jberdine @hhugo @Julow

**Comment by avsm** [comment]
I'd be interested to know if this makes ppx generation of comments possible or easier, so that ppx can customise the odoc output for autogenerated functions.

**Comment by gpetiot** [comment]
See also #110

**Comment by Julow** [comment]
There is a lot of node in the AST that have a location but no attribute.

For example every `Longident.t loc`, `string loc` and `label loc`. Some of them are only a tiny part of their parent node, so there could be comment around them, a few examples:
- Type constructors ident (`... t`)
- Row tag label (``[ `A of ... ]``)
- Object tag ident (`< t : ... >`)
- Constructor ident in patterns and expressions (`A ...`)
- Record field idents in patterns and expressions

Alternatively we could move these comments to a near node, so at least these changes are defined and done in a single pass. For example  `'a (* a *) t` to `(* a *) 'a t` or `{ a (* a *) : t }` to `{ a : (* a *) t }`

**Comment by gpetiot** [comment]
I don't have any issue with moving the comments (if there is no attribute) like you suggested, moving comments is already something that is done (but it's not documented and it is a source of headaches). But this way you can improve the situation:
- the node has attributes -> no doubt about which comments are attached to it
- no attribute -> move the comments to the closest parent node having attributes (1st case)
- no comment should move in any other case

Of course if we want to preserve the position of comments at all costs, we could still have our own custom AST, with an extra field for the comments on each node, but I find the first solution less invasive.

**Comment by gpetiot** [comment]
Won't probably be done, but #1193 should improve the situation.
