### ISSUE TITLE
break before sequences

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#938]
Is it possible to format
```ocaml
let _ =
  do_ ;
  job_1 ;
  job_2 ;
  return ()
```
as
```ocaml
let _ = do_
  ; job_1
  ; job_2
  ; return ()
```
Can `ocamlformat` have such option like `sequences-style=[before|after]` or even `infix-style=[before|after]`?

**Comment by gpetiot** [comment]
I don't think we will do:
```ocaml
let _ = do_
  ; job_1
  ; job_2
  ; return ()
```
this one:
```ocaml
let _ =
  do_
  ; job_1
  ; job_2
  ; return ()
```
would be closer to the style we are supporting in ocamlformat

**Comment by Pitometsu** [comment]
The second one still acceptable as for me, the goal is to indent it as prefixes for more readable formatting, and better diffs.
