### ISSUE TITLE
Not so nice @@deriving indentation

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#940]
Actual:
```ocaml
type t =
  | A of a
  | B of b
[@@deriving sexp]
```
Expected:
```ocaml
type t =
  | A of a
  | B of b
  [@@deriving sexp]
```

**Comment by emillon** [comment]
Should this be closed now that #945 is merged?

**Comment by Pitometsu** [comment]
@emillon is #945 really merged? @gpetiot ?

**Comment by gpetiot** [comment]
No it was not merged since we did not agree on modifying the default behavior, and we are not sure about adding another option for this.
Adding options is a sensitive topic these days (our policy rather tends towards removing options).

**Comment by Pitometsu** [comment]
Is it hard to maintain all the invariants?

What would be the proper way to choose the proper variant: voting, syntax aesthetic discuss, semantic logic discuss, author's will?

**Comment by cemerick** [comment]
Where does this stand? I agree with the OP that not grouping such attributes with their types is unfortunate.

**Comment by gpetiot** [comment]
It seems that's also the default style promoted by ocp-indent, `@@` -attributes are item attributes, attached to the whole type item, so it makes sense to align it under the `type` keyword, and it looks like the most commonly accepted style.
I'm closing this issue then.
