### ISSUE TITLE
Style suggestion: arguments right-alignment by keys

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#958]
Is it possible to align by right side of argument's keys like that:

```ocaml
include (struct
  let fn (type a') (type b') (type e') (type f') ~a:(a': a')
                                                ~(b: b')
                                                 ~c:c'
                                                 ~d
                                                 ?e:(e': e' option)
                                                ?(f: f' option)
                                                 ?g:g'
                                                 ?h
  : _
  -> unit
  = let fn
    : 'i. 'i
    -> _
    = fun _ ->
      failwith "undefined"
  in fn
end : sig
  val fn
  :   a:'a
  ->  b:'b
  ->  c:'c
  ->  d:'d
  -> ?e:'e
  -> ?f:'f
  -> ?g:'g
  -> ?h:'h
  -> 'i
  -> unit
end)

let _ =
  let d = 42
  and g = Option.some 42
  and h = 42
   in fn ~a:42
         ~b:42
         ~c:42
         ~d
         ~e:42
         ?f:(Option.some 42)
         ?g
         ~h
```

**Comment by Pitometsu** [comment]
Not sure about which variant would be better for long key indentation:
```ocaml
fn              ~a:42
  ~veryLongKeyHere:42
                ~c:42
```
vs
```ocaml
fn
                ~a:42
  ~veryLongKeyHere:42
                ~c:42
```
Also, is it worth to include colon in key name, or letters only.

**Comment by gpetiot** [comment]
It looks oddly specific to me, it is the first time I see this style, is this really used in a lot of projects?

Generally speaking we are not too keen on adding too many styles/options that are not already widely used, as it makes ocamlformat more difficult to maintain. And these days we aim at removing options instead of adding new ones, to progressively reduce the number of different styles out there.

**Comment by Pitometsu** [comment]
That style was inspired by Objective-C methods formatting. Just curious, so issue is pretty minor and not necessary to implement.
