### ISSUE TITLE
Odd behaviour when mixing infix operators with comments

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#961]
OCamlformat currently converts the following input
```ocaml
let () =
  (* Open the repo *)
  initialise >>=
  (* Perform a subsequent action *)
  subsequent_action >|=
  (* Keep going... *)
  another_action |> fun t ->
  (* And finally do this *)
  final_action t
```
to this output:
```ocaml
let () =
  (* Open the repo *)
  initialise >>= (* Perform a subsequent action *)
                 subsequent_action >|= (* Keep going... *)
                                       another_action
  |> fun t ->
  (* And finally do this *)
  final_action t
```
which looks odd to me.

**Comment by gpetiot** [comment]
Do you have some feedback on how #986 looks on your code?

**Comment by CraigFe** [comment]
The behaviour on the code snippet above is now:
```ocaml
let () =
  (* Open the repo *)
  initialise
  >>= (* Perform a subsequent action *)
  subsequent_action
  >|= (* Keep going... *)
  another_action
  |> fun t ->
  (* And finally do this *)
  final_action t
```

As a user, I see this as OCamlformat being opinionated about where I should put my binds (which I don't particularly mind, save for some concerns about compatibility with `let+` syntax). If I listen to OCamlformat and move my comments to be before the infix operators, I would give this as input:
```ocaml
let () =
  (* Open the repo *)
  initialise
  (* Perform a subsequent action *)
  >>= subsequent_action
  (* Keep going... *)
  >|= another_action
  (* And finally do this *)
  |> fun t -> final_action t
```
Which unfortunately becomes this:
```ocaml
let () =
  (* Open the repo *)
  initialise (* Perform a subsequent action *) >>= subsequent_action
  (* Keep going... *)
  >|= another_action
  (* And finally do this *)
  |> fun t -> final_action t
```
If OCamlformat is to force bind operators to the start of lines, this seems like a very unpleasant interaction with comments.

**Comment by Julow** [comment]
The incorrect formatting is fixed in https://github.com/ocaml-ppx/ocamlformat/pull/986. Should we close this (by merging) and open new issues for the formatting and for the placement of operators ?

**Comment by gpetiot** [comment]
I improved the case when the comment is before the operator.

**Comment by CraigFe** [comment]
The new behaviour seems good to me; thanks :slightly_smiling_face:

**Comment by Julow** [comment]
Fixed in https://github.com/ocaml-ppx/ocamlformat/pull/986. Feel free to open a new issue to discuss the placement of operators.

**Comment by CraigFe** [comment]
Cool, thanks. The follow-up is https://github.com/ocaml-ppx/ocamlformat/pull/986.
