### ISSUE TITLE
Harvest most used ocamlformat configurations from github projects

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#979]
Maybe it would useful to have a tool that would extract the more used `.ocamlformat`configurations from the github project, so that we wouldn't have to ask for feedback on the ocaml discuss or the slack?

- number of projects (weighted with number of files in said project) using this option/profile?
- percentage of selection for each value of each option?

Is there already an API that could be useful for that?

**Comment by Julow** [comment]
Github allows that https://github.com/search?l=&q=filename%3A.ocamlformat&type=Code (API too https://developer.github.com/v3/search/#search-code).
I'll try to make a script to do that.

**Comment by Julow** [comment]
I've found that measuring the size of a project is too slow and that the "score" computed by Github does not means anything useful.
For now I have a simple script that gives the number of projects that use each option, value pair. https://gist.github.com/Julow/110dc94308d6078225e0665e3eccd433
What do you mean by your second point ?

**Comment by gpetiot** [comment]
I mean we could distinguish
- option `o=v` is explicitely selected in the .ocamlformat file
- option `o=v` is set because profile `p` is selected and the option is set by the profile

but this is just an idea I don't know what can be useful yet, I just wish we can see some values of options have 0% use and we can safely remove them without upsetting anyone.

**Comment by Julow** [comment]
Updated the script to show which option:value pair are not used and to count options set by profiles.

**Comment by gpetiot** [comment]
Can we do the same on duniverse?
So far we can start by removing the option `comment-check`.

**Comment by Julow** [comment]
I updated the script to the new options and to show the projects that use the least used options (https://gist.github.com/Julow/110dc94308d6078225e0665e3eccd433)
Options that are set by profiles are counted (this can be disabled in the script)

**Comment by gpetiot** [comment]
I guess we can exclude the numerical options from this list (like `margin` and the ones about indentation)

**Comment by Julow** [comment]
I added them back because some are never used (eg. the indent options).

**Comment by gpetiot** [comment]
I forgot to close this issue, the survey was very helpful, thanks!

**Comment by hhugo** [comment]
I think it would be helpful to compute the number of lines of code automatically formatted instead of the number of projects.
