### ISSUE TITLE
Bug: --doc-comments doesn't apply to all type definitions

### ISSUE THREAD

**Issue by Wilfred** [ocaml-ppx/ocamlformat#981]
Given the code:

```
(** one *)
type foo = Bar | Baz

(** two *)
type foo2 = {push: bool; state: bool}
```

ocamlformat produces:

```
(** one *)
type foo = Bar | Baz

type foo2 = {push: bool; state: bool}
(** two *)
```

I'd expected:

```
type foo = Bar | Baz
(** one *)

type foo2 = {push: bool; state: bool}
(** two *)
```

This issue seems to occur for both `--doc-comments=before` (the default, shown here) and `--doc-comments=after` (where the `foo` type doesn't end up with its doc comment before).

**Comment by Wilfred** [comment]
Based on my understanding of #556, this might just be a documentation issue? The help for `--doc-comments` suggests it applies to all doc comments.

**Comment by Julow** [comment]
Documentation comments cannot be placed after variant declarations. Otherwise it would be attached to the last constructor and not the full declaration.
This should be added to the documentation.
